In [70]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# DATA CLEANING AND NEW FEATURES

In [71]:
import pandas as pd
import numpy as np

file_path = "/content/drive/MyDrive/PROJECT SYNTHESIS I/260319_GrauIAI_data.xlsx"    #with this we don't have to upload the data every time
df_dict = pd.read_excel(file_path, sheet_name=None)   #this creates a dictionary for our data where each key corresponds to a datasheet

df_dict.keys()

dict_keys(['Data', 'Schedules', 'Clients', 'TranslatorsCost+Pairs'])

In [72]:
#lets define a variable for each individual datasheet
df1 = df_dict['Data']
df2 = df_dict['Schedules']
df3 = df_dict['Clients']
df4 = df_dict['TranslatorsCost+Pairs']

df1.head()

,PROJECT_ID,PM,TASK_ID,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,TRANSLATOR,ASSIGNED,...,CLOSE,HOURS,HOURLY_RATE,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_SECTOR,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY
0,216606,KMT,10691707,2018-12-20 10:03:00,2018-12-21 18:00:00,DTP,English,Spanish (Iberian),Abigail,2018-12-20 10:04:03,...,2018-12-21 12:18:38,0.50,19.0,9.50,8,MedClean Innovations,Health Care,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
1,216606,KMT,10691442,2018-12-20 09:00:00,2018-12-21 13:00:00,ProofReading,English,Spanish (Iberian),Abelardo,2018-12-19 14:59:03,...,2018-12-21 12:23:19,0.31,17.0,5.27,7,MedClean Innovations,Health Care,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
2,216606,KMT,10691441,2018-12-19 12:47:00,2018-12-20 16:00:00,Translation,English,Spanish (Iberian),Margarita,2018-12-19 14:58:45,...,2018-12-21 12:23:16,0.92,13.0,11.96,8,MedClean Innovations,Health Care,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
3,217166,KMT,10690432,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),Italian,Davide,2018-12-17 11:31:15,...,2018-12-20 09:07:07,0.86,32.0,27.52,8,HealthyLife,Health Care,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear
4,217166,KMT,10690430,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),German,Paul,2018-12-17 11:30:44,...,2018-12-20 09:07:21,0.86,31.0,26.66,8,HealthyLife,Health Care,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear

In [73]:
#we get rid of the columns we are not interested in
df1 = df1.drop(columns=['PROJECT_ID', 'PM', 'TASK_ID', "ASSIGNED", "RECEIVED", "CLOSE", "HOURLY_RATE", "MANUFACTURER_SECTOR"])

In [74]:
df1.head()

,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,TRANSLATOR,READY,WORKING,DELIVERED,HOURS,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY
0,2018-12-20 10:03:00,2018-12-21 18:00:00,DTP,English,Spanish (Iberian),Abigail,2018-12-21 10:42:27,2018-12-21 10:42:44,2018-12-21 12:18:33,0.50,9.50,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
1,2018-12-20 09:00:00,2018-12-21 13:00:00,ProofReading,English,Spanish (Iberian),Abelardo,2018-12-20 14:23:30,2018-12-21 10:11:42,2018-12-21 10:40:08,0.31,5.27,7,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
2,2018-12-19 12:47:00,2018-12-20 16:00:00,Translation,English,Spanish (Iberian),Margarita,2018-12-20 09:04:34,2018-12-20 13:30:55,2018-12-20 14:23:29,0.92,11.96,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
3,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),Italian,Davide,2018-12-18 09:40:40,2018-12-19 11:27:00,2018-12-19 11:43:06,0.86,27.52,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear
4,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),German,Paul,2018-12-18 13:39:03,2018-12-19 20:58:00,2018-12-19 21:44:41,0.86,26.66,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear

In [75]:
#we put the "TRANSLATOR" column in first position
cols = ['TRANSLATOR'] + [c for c in df1.columns if c != 'TRANSLATOR']
df1 = df1[cols]

df1.head()

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,HOURS,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY
0,Abigail,2018-12-20 10:03:00,2018-12-21 18:00:00,DTP,English,Spanish (Iberian),2018-12-21 10:42:27,2018-12-21 10:42:44,2018-12-21 12:18:33,0.50,9.50,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
1,Abelardo,2018-12-20 09:00:00,2018-12-21 13:00:00,ProofReading,English,Spanish (Iberian),2018-12-20 14:23:30,2018-12-21 10:11:42,2018-12-21 10:40:08,0.31,5.27,7,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
2,Margarita,2018-12-19 12:47:00,2018-12-20 16:00:00,Translation,English,Spanish (Iberian),2018-12-20 09:04:34,2018-12-20 13:30:55,2018-12-20 14:23:29,0.92,11.96,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies
3,Davide,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),Italian,2018-12-18 09:40:40,2018-12-19 11:27:00,2018-12-19 11:43:06,0.86,27.52,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear
4,Paul,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),German,2018-12-18 13:39:03,2018-12-19 20:58:00,2018-12-19 21:44:41,0.86,26.66,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear

In [76]:
df1['START'] = pd.to_datetime(df1['START'], errors='coerce')
df1['END'] = pd.to_datetime(df1['END'], errors='coerce')

df1['TASK_LENGTH'] = (df1['END'] - df1['START']).dt.total_seconds() / 3600

df1['WORKING'] = pd.to_datetime(df1['WORKING'], errors='coerce')
df1['DELIVERED'] = pd.to_datetime(df1['DELIVERED'], errors='coerce')

df1['TRANSLATOR_WORKING_TIME'] = (df1['DELIVERED'] - df1['WORKING']).dt.total_seconds() / 3600

df1.head(10)

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,HOURS,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY,TASK_LENGTH,TRANSLATOR_WORKING_TIME
0,Abigail,2018-12-20 10:03:00,2018-12-21 18:00:00,DTP,English,Spanish (Iberian),2018-12-21 10:42:27,2018-12-21 10:42:44,2018-12-21 12:18:33,0.50,9.50,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,31.950000,1.596944
1,Abelardo,2018-12-20 09:00:00,2018-12-21 13:00:00,ProofReading,English,Spanish (Iberian),2018-12-20 14:23:30,2018-12-21 10:11:42,2018-12-21 10:40:08,0.31,5.27,7,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,28.000000,0.473889
2,Margarita,2018-12-19 12:47:00,2018-12-20 16:00:00,Translation,English,Spanish (Iberian),2018-12-20 09:04:34,2018-12-20 13:30:55,2018-12-20 14:23:29,0.92,11.96,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,27.216667,0.876111
3,Davide,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),Italian,2018-12-18 09:40:40,2018-12-19 11:27:00,2018-12-19 11:43:06,0.86,27.52,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,40.000000,0.268333
4,Paul,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),German,2018-12-18 13:39:03,2018-12-19 20:58:00,2018-12-19 21:44:41,0.86,26.66,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,40.000000,0.778056
5,Sabine,2018-12-17 10:14:00,2018-12-19 16:00:00,Translation,Spanish (Iberian),German,2018-12-17 11:29:17,2018-12-18 10:21:24,2018-12-18 13:39:03,2.81,81.49,5,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,53.766667,3.294167
6,Alessandro,2018-12-17 10:13:00,2018-12-18 16:00:00,Translation,Spanish (Iberian),Italian,2018-12-17 10:36:56,2018-12-18 09:40:34,2018-12-18 09:40:40,2.81,87.11,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,29.783333,0.001667
7,Daiana Rosario,2018-12-13 11:07:00,2018-12-14 19:00:00,Miscellaneous,Spanish (Iberian),English,2018-12-14 12:17:29,2018-12-14 15:54:08,2018-12-17 12:06:41,0.00,0.00,7,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,31.883333,68.209167
8,Francisco Jose,2018-12-17 09:00:00,2018-12-18 10:00:00,ProofReading,English,Spanish (Iberian),2018-12-17 07:56:47,2018-12-18 09:00:35,2018-12-18 10:15:43,0.95,14.25,7,Axiom Services,Industrial Services & Distributors,Industrial & Leasing Services,Commercial & Industrial Services,25.000000,1.252222
9,Daiana Rosario,2018-12-13 11:07:00,2018-12-14 19:00:00,Miscellaneous,Spanish (Iberian),English,2018-12-13 11:09:33,2018-12-14 12:17:53,2018-12-14 12:17:57,0.00,0.00,6,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,31.883333,0.001111

In [77]:
#we observe some inconsistencies. For example, that some task_length values are negative (shown below), some costs are 0, some TRANSLATOR_WORKING_TIME is
#too close to 0, or some source and target language being the same
df1[df1['TASK_LENGTH'] < 0]

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,HOURS,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY,TASK_LENGTH,TRANSLATOR_WORKING_TIME
6405,Victor,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.00,0.00,9,SunTech,Technology Hardware & Peripherals,"Technology Hardware, Communications & Peripherals",Technology Hardware & Equipment,-18.216667,0.000556
6406,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.00,0.00,7,SunTech,Technology Hardware & Peripherals,"Technology Hardware, Communications & Peripherals",Technology Hardware & Equipment,-18.216667,0.001389
6407,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscelaneous,Catalan,Spanish (Global),2013-10-31 13:16:51,2013-10-31 13:16:54,2013-10-31 13:16:58,0.00,0.00,6,SunTech,Technology Hardware & Peripherals,"Technology Hardware, Communications & Peripherals",Technology Hardware & Equipment,-18.216667,0.001111
32655,Gala,2023-01-02 09:55:00,2023-01-02 09:53:00,ProofReading,English,Galician,2023-01-02 08:50:15,2023-01-02 09:01:20,2023-01-02 09:13:20,0.02,0.32,6,AeroSysTech,"Software, Internet & IT Services",Software,Systems & Infrastructure Software,-0.033333,0.200000
32663,Ildefonso Ambrosio,2023-01-02 16:21:00,2023-01-02 16:19:00,ProofReading,English,Spanish (LA),2023-01-02 15:38:45,2023-01-02 15:41:17,2023-01-02 16:43:43,2.64,39.60,5,AeroSysTech,"Software, Internet & IT Services",Software,Systems & Infrastructure Software,-0.033333,1.040556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955581,Pol,2012-10-15 09:47:17,2012-10-12 18:00:00,ProofReading,English,Catalan,2012-10-15 10:05:42,2012-10-15 10:05:42,2012-10-15 10:05:42,0.08,1.28,7,TrueConnect,"Media, Entertainment & Interactive Services",Internet Infrastructure & Services,Internet Infrastructure & Services,-63.788056,0.000000
983886,Aurelio Cayo,2014-10-29 10:58:00,2014-10-17 17:00:00,ProofReading,English,Portuguese (Brazil),2014-10-29 12:43:16,2014-10-29 13:09:52,2014-10-29 13:10:30,0.07,1.19,2,AeroSysTech,"Software, Internet & IT Services",Software,Systems & Infrastructure Software,-281.966667,0.010556
983887,Artemio Ramon,2014-10-29 10:58:00,2014-10-17 16:00:00,Translation,English,Portuguese (Brazil),2014-10-29 10:58:00,2014-10-29 11:49:19,2014-10-29 12:43:16,0.23,3.91,8,AeroSysTech,"Software, Internet & IT Services",Software,Systems & Infrastructure Software,-282.966667,0.899167
990579,Artemio Ramon,2014-04-28 11:35:21,2014-04-18 18:00:00,Translation,English,Portuguese (Brazil),2014-04-28 11:35:21,2014-04-28 15:01:37,2014-04-28 15:10:12,0.09,1.53,8,AeroSysTech,"Software, Internet & IT Services",Software,Systems & Infrastructure Software,-233.589167,0.143056
991480,Artemio Ramon,2014-03-25 09:47:55,2014-03-15 16:00:00,Translation,English,Portuguese (Brazil),2014-03-25 09:47:55,2014-03-25 11:44:15,2014-03-25 11:55:06,0.08,1.36,8,AeroSysTech,"Software, Internet & IT Services",Software,Systems & Infrastructure Software,-233.798611,0.180833

In [78]:
#let's clean the data
df1 = df1[(df1['TASK_LENGTH'] > 0.01) & (df1['TRANSLATOR_WORKING_TIME'] > 0.01) & (df1['SOURCE_LANG'] != df1['TARGET_LANG']) & (df1['COST'] > 0)]

df1.head(10)

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,HOURS,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY,TASK_LENGTH,TRANSLATOR_WORKING_TIME
0,Abigail,2018-12-20 10:03:00,2018-12-21 18:00:00,DTP,English,Spanish (Iberian),2018-12-21 10:42:27,2018-12-21 10:42:44,2018-12-21 12:18:33,0.50,9.50,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,31.950000,1.596944
1,Abelardo,2018-12-20 09:00:00,2018-12-21 13:00:00,ProofReading,English,Spanish (Iberian),2018-12-20 14:23:30,2018-12-21 10:11:42,2018-12-21 10:40:08,0.31,5.27,7,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,28.000000,0.473889
2,Margarita,2018-12-19 12:47:00,2018-12-20 16:00:00,Translation,English,Spanish (Iberian),2018-12-20 09:04:34,2018-12-20 13:30:55,2018-12-20 14:23:29,0.92,11.96,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,27.216667,0.876111
3,Davide,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),Italian,2018-12-18 09:40:40,2018-12-19 11:27:00,2018-12-19 11:43:06,0.86,27.52,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,40.000000,0.268333
4,Paul,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),German,2018-12-18 13:39:03,2018-12-19 20:58:00,2018-12-19 21:44:41,0.86,26.66,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,40.000000,0.778056
5,Sabine,2018-12-17 10:14:00,2018-12-19 16:00:00,Translation,Spanish (Iberian),German,2018-12-17 11:29:17,2018-12-18 10:21:24,2018-12-18 13:39:03,2.81,81.49,5,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,53.766667,3.294167
8,Francisco Jose,2018-12-17 09:00:00,2018-12-18 10:00:00,ProofReading,English,Spanish (Iberian),2018-12-17 07:56:47,2018-12-18 09:00:35,2018-12-18 10:15:43,0.95,14.25,7,Axiom Services,Industrial Services & Distributors,Industrial & Leasing Services,Commercial & Industrial Services,25.000000,1.252222
10,Abelardo,2018-12-12 11:42:00,2018-12-17 10:00:00,Translation,English,Spanish (Iberian),2018-12-12 11:47:27,2018-12-14 14:06:51,2018-12-17 07:56:47,3.09,52.53,5,Axiom Services,Industrial Services & Distributors,Industrial & Leasing Services,Commercial & Industrial Services,118.300000,65.832222
11,Abigail,2018-11-13 18:00:00,2018-11-14 12:00:00,DTP,English,Spanish (Iberian),2018-11-14 11:48:26,2018-11-14 11:48:36,2018-11-14 13:21:13,2.00,38.00,6,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,18.000000,1.543611
12,Carles,2018-11-13 15:00:00,2018-11-14 09:00:00,ProofReading,English,Spanish (Iberian),2018-11-13 09:26:22,2018-11-13 19:30:48,2018-11-13 22:03:14,3.58,53.70,7,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,18.000000,2.540556

In [79]:
#finally let's create a new column to keep track of on-time/late deliveries
#there appears a warning due to pandas not knowing what it has to modifiy. If someone knows how to fix it do it please. Create a copy or whatever
df1['END'] = pd.to_datetime(df1['END'])
df1['DELIVERED'] = pd.to_datetime(df1['DELIVERED'])

df1['ON_TIME'] = (df1['END'] >= df1['DELIVERED']).astype(int)
df1.head()

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,HOURS,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY,TASK_LENGTH,TRANSLATOR_WORKING_TIME,ON_TIME
0,Abigail,2018-12-20 10:03:00,2018-12-21 18:00:00,DTP,English,Spanish (Iberian),2018-12-21 10:42:27,2018-12-21 10:42:44,2018-12-21 12:18:33,0.50,9.50,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,31.950000,1.596944,1
1,Abelardo,2018-12-20 09:00:00,2018-12-21 13:00:00,ProofReading,English,Spanish (Iberian),2018-12-20 14:23:30,2018-12-21 10:11:42,2018-12-21 10:40:08,0.31,5.27,7,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,28.000000,0.473889,1
2,Margarita,2018-12-19 12:47:00,2018-12-20 16:00:00,Translation,English,Spanish (Iberian),2018-12-20 09:04:34,2018-12-20 13:30:55,2018-12-20 14:23:29,0.92,11.96,8,MedClean Innovations,"Health Care Equipment, Supplies & Technology",Health Care Equipment & Devices,Medical Equipment & Supplies,27.216667,0.876111,1
3,Davide,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),Italian,2018-12-18 09:40:40,2018-12-19 11:27:00,2018-12-19 11:43:06,0.86,27.52,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,40.000000,0.268333,1
4,Paul,2018-12-18 19:00:00,2018-12-20 11:00:00,ProofReading,Spanish (Iberian),German,2018-12-18 13:39:03,2018-12-19 20:58:00,2018-12-19 21:44:41,0.86,26.66,8,HealthyLife,Health Care Providers & Services,"Health Care Providers, Services & Facilities",Footwear,40.000000,0.778056,1

# TRANSLATOR STATISTICS/INFORMATION DATASHEET

In [80]:
#now, we'll use the data we have above to create a new datasheet with all the information we want for each translator

In [81]:
import pandas as pd

translators_df = pd.DataFrame()

In [82]:
#first we want to know the time availavility of each translator
cols = [c for c in df2.columns]
translators_df = df2[cols]

translators_df.head()

           NAME     START       END  MON  TUES  WED  THURS  FRI  SAT  SUN
0         Aaron  09:00:00  19:00:00    1     1    1      1    1    0    0
1         Abdon  10:00:00  20:00:00    1     1    1      1    1    1    1
2  Abdon Isaias  09:00:00  19:00:00    1     1    1      1    1    1    1
3    Abdon Luis  04:00:00  14:00:00    1     0    1      1    1    0    1
4    Abel Irene  07:00:00  17:00:00    0     1    0      1    1    0    1

In [83]:
#PROBLEM! before adding the source-target language information, let's check if all translators are in both df2 (which we used to create the column of trabnslators)
#and df4 (where the source-target language information is)
missing_in_df4 = set(df2['NAME']) - set(df4['TRANSLATOR'])
missing_in_df2 = set(df4['TRANSLATOR']) - set(df2['NAME'])

print("Missing in df4:", missing_in_df4)
print("Missing in df2:", missing_in_df2)

Missing in df4: set()
Missing in df2: set()

In [84]:
#it is normal that we're missing a lot of names in df4 (as we're currently using a small dataset)
#the important thing is that there are no missing names in df2

#now, I asked chatGPT this:
#"I want to do is to create new columns (or just one) for each translator in translators_df indicating which source-target language task
#they can manage. In the datasheet df4, many translators have multiple rows, one for each language pair, and each row has a different hourly_rate cost. How do I
#incorporate all that information in a single row for every translator in translators_df? Do I create a column for every possible language pair, do I create a single
#column which contains a dictionary for every translator where keys are language pairs and values are hourly_rate cost, or is it better to do another thing?"

#and it told me that for pandas, the best thing is to create a new column for each language pair, so that's what we're gonna do :D

In [85]:
# 1. Create language pair column in df4
df4['PAIR'] = df4['SOURCE_LANG'] + "_" + df4['TARGET_LANG']

# 2. Pivot df4 → one row per translator, one column per language pair
pivot = df4.pivot_table(
    index='TRANSLATOR',
    columns='PAIR',
    values='HOURLY_RATE',
    aggfunc='first'
).reset_index()

# 3. Merge into translators_df (NAME ↔ TRANSLATOR)
translators_df = translators_df.merge(
    pivot,
    left_on='NAME',
    right_on='TRANSLATOR',
    how='left'
)


translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Spanish (LA)_Spanish (Global),Spanish (LA)_Spanish (Iberian),Spanish (LA)_Spanish (LA),Spanish (LA)_Spanish (US),Spanish (Mexico)_English,Spanish (Mexico)_English (US),Spanish (Mexico)_Spanish (LA),Spanish (Mexico)_Spanish (Mexico),Spanish (SOURCE)_English,Swedish_Spanish (Iberian)
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdon Luis,04:00:00,14:00:00,1,0,1,1,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abel Irene,07:00:00,17:00:00,0,1,0,1,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
#We chack that it's working
translators_df.loc[translators_df['NAME'] == 'Aaron', 'English_Spanish (Iberian)'].values[0]

np.float64(17.0)

In [87]:
#this creates a column with the average quality of each translator
#the minimum of this column should be 0 and the maximum 10. If not data in df1 was found for the translator, the value is NaN
translators_df = translators_df.merge(
    df1.groupby('TRANSLATOR')['QUALITY_EVALUATION']
        .mean()
        .reset_index()
        .rename(columns={
            'TRANSLATOR': 'NAME',
            'QUALITY_EVALUATION': 'AVERAGE_QUALITY'
        }),
    on='NAME',
    how='left'
)

translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Spanish (LA)_Spanish (Iberian),Spanish (LA)_Spanish (LA),Spanish (LA)_Spanish (US),Spanish (Mexico)_English,Spanish (Mexico)_English (US),Spanish (Mexico)_Spanish (LA),Spanish (Mexico)_Spanish (Mexico),Spanish (SOURCE)_English,Swedish_Spanish (Iberian),AVERAGE_QUALITY
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.206897
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.997932
3,Abdon Luis,04:00:00,14:00:00,1,0,1,1,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000
4,Abel Irene,07:00:00,17:00:00,0,1,0,1,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
#this creates a column with the ON_TIME_SCORE of each translator
#the minimum of this column should be 0 and the maximum 1. If not data in df1 was found for the translator, the value is NaN
translators_df = translators_df.merge(
    df1.groupby('TRANSLATOR')['ON_TIME']
        .mean()
        .reset_index()
        .rename(columns={
            'TRANSLATOR': 'NAME',
            'ON_TIME': 'ON_TIME_SCORE'
        }),
    on='NAME',
    how='left'
)

translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Spanish (LA)_Spanish (LA),Spanish (LA)_Spanish (US),Spanish (Mexico)_English,Spanish (Mexico)_English (US),Spanish (Mexico)_Spanish (LA),Spanish (Mexico)_Spanish (Mexico),Spanish (SOURCE)_English,Swedish_Spanish (Iberian),AVERAGE_QUALITY,ON_TIME_SCORE
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.206897,0.896552
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.997932,0.807719
3,Abdon Luis,04:00:00,14:00:00,1,0,1,1,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,1.000000
4,Abel Irene,07:00:00,17:00:00,0,1,0,1,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
#this creates a column for the task experience of each translator (one column per task type)

df1['TASK_TYPE'] = df1['TASK_TYPE'] + "_experience"

#Pivot df1 → one row per translator, one column per task type
pivot = df1.pivot_table(
    index='TRANSLATOR',
    columns='TASK_TYPE',
    values='TRANSLATOR_WORKING_TIME',
    aggfunc='sum'
).reset_index()

# Rename TRANSLATOR → NAME BEFORE merging
pivot = pivot.rename(columns={'TRANSLATOR': 'NAME'})


# Merge cleanly (no _x / _y columns)
translators_df = translators_df.merge(
    pivot,
    on='NAME',
    how='left'
)

# Replace NaN with 0 ONLY in experience columns
exp_cols = [c for c in translators_df.columns if c.endswith('_experience')]
translators_df[exp_cols] = translators_df[exp_cols].fillna(0)

translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Management_experience,Miscellaneous_experience,PostEditing_experience,ProofReadingOnly_experience,ProofReading_experience,Spotcheck_experience,TEST_experience,Training_experience,TranslationOnly_experience,Translation_experience
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,0.000000,28.980278,1132.313889,0.0,36.430278,0.0,0.000000,0.0,0.0,606.052222
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,2024.208333,41654.309444,8893.448056,0.0,37544.968333,0.0,24.991111,0.0,0.0,30435.375278
3,Abdon Luis,04:00:00,14:00:00,1,0,1,1,1,0,1,...,0.000000,0.000000,125.238333,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
4,Abel Irene,07:00:00,17:00:00,0,1,0,1,1,0,1,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000

In [90]:
#this create a column called TIME_TO_START, whose value will be calculated later when the task starting date is provided. The value of the column will be in how much time
# the translator will be available, calculated by comparing the task starting date and the translator schedules

translators_df["TIME_TO_START"] = np.nan

translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Miscellaneous_experience,PostEditing_experience,ProofReadingOnly_experience,ProofReading_experience,Spotcheck_experience,TEST_experience,Training_experience,TranslationOnly_experience,Translation_experience,TIME_TO_START
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,NaN
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,28.980278,1132.313889,0.0,36.430278,0.0,0.000000,0.0,0.0,606.052222,NaN
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,41654.309444,8893.448056,0.0,37544.968333,0.0,24.991111,0.0,0.0,30435.375278,NaN
3,Abdon Luis,04:00:00,14:00:00,1,0,1,1,1,0,1,...,0.000000,125.238333,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,NaN
4,Abel Irene,07:00:00,17:00:00,0,1,0,1,1,0,1,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,NaN

In [91]:
# Checking the area of expertise of each translator (from more specific to less specific)

# Create Specific Subindustry Columns (e.g., 'SUB_Footwear')
df1['SUB_CLEAN'] = "SUB_" + df1['MANUFACTURER_SUBINDUSTRY'].astype(str)
sub_pivot = df1.pivot_table(index='TRANSLATOR', columns='SUB_CLEAN', values='TRANSLATOR_WORKING_TIME', aggfunc='sum').reset_index()
sub_pivot = sub_pivot.rename(columns={'TRANSLATOR': 'NAME'})
translators_df = translators_df.merge(sub_pivot, on='NAME', how='left')

# Create Specific Industry Columns (e.g., 'IND_Health Care Equipment & Devices')
df1['IND_CLEAN'] = "IND_" + df1['MANUFACTURER_INDUSTRY'].astype(str)
ind_pivot = df1.pivot_table(index='TRANSLATOR', columns='IND_CLEAN', values='TRANSLATOR_WORKING_TIME', aggfunc='sum').reset_index()
ind_pivot = ind_pivot.rename(columns={'TRANSLATOR': 'NAME'})
translators_df = translators_df.merge(ind_pivot, on='NAME', how='left')

# Create Broad Sector Columns (e.g., 'GRP_Health Care Equipment, Supplies & Technology')
df1['GRP_CLEAN'] = "GRP_" + df1['MANUFACTURER_INDUSTRY_GROUP'].astype(str)
grp_pivot = df1.pivot_table(index='TRANSLATOR', columns='GRP_CLEAN', values='TRANSLATOR_WORKING_TIME', aggfunc='sum').reset_index()
grp_pivot = grp_pivot.rename(columns={'TRANSLATOR': 'NAME'})
translators_df = translators_df.merge(grp_pivot, on='NAME', how='left')

# Clean up NaNs (Replace with 0 hours of experience for all prefixes)
exp_cols = [c for c in translators_df.columns if str(c).startswith('SUB_') or str(c).startswith('IND_') or str(c).startswith('GRP_')]
translators_df[exp_cols] = translators_df[exp_cols].fillna(0)

# CSP

In [97]:
# ==========================================
# THE CSP SOLVER CLASS
# ==========================================

class TaskAssignmentCSP:
    """
    This class acts as the 'Decision Engine' that connects HR Data (translators_df),
    CRM Data (df3 / clients), and Historical Data (df1) to find the perfect match
    using hard constraints, schedule parsing, and automatic constraint relaxation.
    """
    def __init__(self, translators_df):
        # We create a safe copy of the translator database so we can filter and manipulate
        # the data without corrupting the original dataframe.
        self.translators_df = translators_df.copy()

    def build_client_requirements(self, company_name, clients_df, historical_df, task_date, task_deadline, task_start_time, task_end_time, task_length_hours, language_pair,
                                  task_type='Translation', followed_by=None, previous_translator_experience=0.0):
        # STEP 1 & 2: (Keep your existing CRM and History extraction exactly the same)
        client_data = clients_df[clients_df['CLIENT_NAME'] == company_name]
        if client_data.empty: return None

        max_rate = client_data['SELLING_HOURLY_PRICE'].iloc[0]
        min_quality = client_data['MIN_QUALITY'].iloc[0]
        min_on_time = client_data['MIN_ON_TIME_SCORE'].iloc[0] if 'MIN_ON_TIME_SCORE' in client_data.columns else 0.0
        wildcard = str(client_data['WILDCARD'].iloc[0]).strip().lower() if 'WILDCARD' in client_data.columns else 'balanced'

        company_history = historical_df[historical_df['MANUFACTURER'] == company_name]
        if company_history.empty:
            subindustries, industries, groups = [], [], []
        else:
            subindustries = [str(x).strip() for x in company_history['MANUFACTURER_SUBINDUSTRY'].dropna().unique()]
            industries = [str(x).strip() for x in company_history['MANUFACTURER_INDUSTRY'].dropna().unique()]
            groups = [str(x).strip() for x in company_history['MANUFACTURER_INDUSTRY_GROUP'].dropna().unique()]

        # --- NEW: CALCULATE THE DEADLINE WINDOW ---
        # Instead of calculating effort, we calculate how many days they have to spread the work out!
        try:
            start_dt = pd.to_datetime(task_date)
            end_dt = pd.to_datetime(task_deadline)
            window_days = max(1, (end_dt - start_dt).days + 1)
        except Exception:
            window_days = 1

        # STEP 3: Compile everything
        task_reqs = {
            'language_pair': language_pair,
            'task_date': task_date,
            'task_deadline': task_deadline,
            'task_start_time': task_start_time,
            'task_end_time': task_end_time,
            'task_length_hours': task_length_hours,
            'window_days': window_days,
            'max_hourly_rate': max_rate,
            'min_quality': min_quality,
            'min_on_time_score': min_on_time,
            'wildcard': wildcard,
            'task_type': task_type,
            'followed_by': followed_by,
            'previous_translator_experience': previous_translator_experience,
            'required_subindustry': subindustries,
            'required_industry': industries,
            'required_industry_group': groups,
            'min_subindustry_experience': 1.0,
            'min_industry_experience': 1.0,
            'min_industry_group_experience': 1.0
        }

        print(f"\n--- AUTO-LOADED PROFILE FOR: {company_name} ---")
        print(f">> Task Effort: {task_length_hours:.2f} hours of work")
        print(f">> Project Window: {window_days} days to deliver")

        return task_reqs

    def diagnose_bottleneck(self, task_reqs):
        """
        THE DIAGNOSTIC TOOL: This applies constraints one by one to print EXACTLY which rule
        eliminates candidates. It is used when the system returns a Fatal Error, allowing
        Project Managers to see why staffing failed.
        """
        print("\n--- CSP BOTTLENECK DIAGNOSTIC ---")
        domain = self.translators_df.copy()

        # Language pair check
        pair = task_reqs.get('language_pair')
        if pair not in domain.columns:
            print(f"FAILED: Nobody speaks {pair}.")
            return

        # Keep only people whose hourly rate for this language is NOT empty (NaN)
        domain = domain[domain[pair].notna()]
        print(f"Language ({pair}): {len(domain)} translators available.")
        if domain.empty: return

        # Budget check (Must be <= Client Budget)
        if 'max_hourly_rate' in task_reqs:
            domain = domain[domain[pair] <= task_reqs['max_hourly_rate']]
            print(f"Budget (<= ${task_reqs['max_hourly_rate']}): {len(domain)} translators left.")
            if domain.empty: return

        # Quality check
        if 'min_quality' in task_reqs:
            domain = domain[domain['AVERAGE_QUALITY'] >= task_reqs['min_quality']]
            print(f"Quality (>= {task_reqs['min_quality']}): {len(domain)} translators left.")
            if domain.empty: return

        # On-Time Delivery check
        if 'min_on_time_score' in task_reqs:
            domain = domain[domain['ON_TIME_SCORE'] >= task_reqs['min_on_time_score']]
            print(f"On-Time (>= {task_reqs['min_on_time_score']}): {len(domain)} translators left.")
            if domain.empty: return

        # Day Schedule Availability check (e.g., Do they work on Mondays?)
        if 'task_date' in task_reqs:
            task_date = pd.to_datetime(task_reqs['task_date'])
            day_mapping = {
                'Monday': 'MON', 'Tuesday': 'TUES', 'Wednesday': 'WED',
                'Thursday': 'THURS', 'Friday': 'FRI', 'Saturday': 'SAT', 'Sunday': 'SUN'
            }
            schedule_col = day_mapping.get(task_date.day_name())
            if schedule_col in domain.columns:
                domain = domain[domain[schedule_col] == 1]
                print(f"Schedule (Works on {task_date.day_name()}): {len(domain)} translators left.")
                if domain.empty: return

        #  Hour Shift Capacity check (Do their hours cover the project window?)
        if 'task_length_hours' in task_reqs and 'task_start_time' in task_reqs:
            if 'START' in domain.columns and 'END' in domain.columns:
                # Clean periods out of time strings (e.g., '14.00' -> '1400')
                clean_start = domain['START'].astype(str).str.replace('.', '', regex=False).str.upper()
                clean_end = domain['END'].astype(str).str.replace('.', '', regex=False).str.upper()

                shift_starts = pd.to_datetime(clean_start, format='mixed', errors='coerce')
                shift_ends = pd.to_datetime(clean_end, format='mixed', errors='coerce')

                # Handle overnight shifts (if end time is earlier than start time, add 1 full day to end time)
                shift_ends = shift_ends.mask(shift_ends < shift_starts, shift_ends + pd.Timedelta(days=1))

                task_start = pd.to_datetime(task_reqs['task_start_time'])
                task_end = task_start + pd.Timedelta(hours=task_reqs['task_length_hours'])

                # Check Start Time: Translator must start before or exactly when the task starts
                domain = domain[shift_starts <= task_start]
                print(f"Shift Start (<= {task_start.strftime('%H:%M')}): {len(domain)} translators left.")
                if domain.empty: return

                # Check End Time: Translator must end after or exactly when the task ends.
                # .loc[domain.index] aligns the dataframes to prevent Pandas UserWarnings
                aligned_shift_ends = shift_ends.loc[domain.index]
                domain = domain[aligned_shift_ends >= task_end]
                print(f"Shift End (>= {task_end.strftime('%H:%M')}): {len(domain)} translators left.")
                if domain.empty: return

        # 3-Tier Hierarchical Expertise check
        if 'required_subindustry' in task_reqs and task_reqs['required_subindustry']:
            req_subs = task_reqs['required_subindustry']
            min_exp = task_reqs.get('min_subindustry_experience', 1.0)
            valid_sub_cols = [f"SUB_{s}" for s in req_subs if f"SUB_{s}" in domain.columns]

            if valid_sub_cols:
                mask = (domain[valid_sub_cols] >= min_exp).any(axis=1) # Checks if ANY required subindustry >= 1.0 hours
                domain = domain[mask]
                print(f"Sub-Industry Expertise (ANY of {req_subs} >= {min_exp} hrs): {len(domain)} translators left.")
                if domain.empty:
                    print(f"-> BOTTLENECK: Remaining translators lack specific Sub-Industry experience in any of {req_subs}.")
                    return
            else:
                print(f"FAILED: None of the required sub-industries {req_subs} exist in our historical data.")
                return

        # (If subindustry fails or isn't requested, it cascades down to Industry and Group in a similar fashion)
        elif 'required_industry' in task_reqs and task_reqs['required_industry']:
            req_inds = task_reqs['required_industry']
            min_exp = task_reqs.get('min_industry_experience', 1.0)
            valid_ind_cols = [f"IND_{i}" for i in req_inds if f"IND_{i}" in domain.columns]

            if valid_ind_cols:
                mask = (domain[valid_ind_cols] >= min_exp).any(axis=1)
                domain = domain[mask]
                print(f"Industry Expertise (ANY of {req_inds} >= {min_exp} hrs): {len(domain)} translators left.")
                if domain.empty:
                    print(f"-> BOTTLENECK: Remaining translators lack Industry experience in any of {req_inds}.")
                    return
            else:
                print(f"FAILED: None of the required industries {req_inds} exist in our historical data.")
                return

        elif 'required_industry_group' in task_reqs and task_reqs['required_industry_group']:
            req_grps = task_reqs['required_industry_group']
            min_exp = task_reqs.get('min_industry_group_experience', 1.0)
            valid_grp_cols = [f"GRP_{g}" for g in req_grps if f"GRP_{g}" in domain.columns]

            if valid_grp_cols:
                mask = (domain[valid_grp_cols] >= min_exp).any(axis=1)
                domain = domain[mask]
                print(f"Industry Group Expertise (ANY of {req_grps} >= {min_exp} hrs): {len(domain)} translators left.")
                if domain.empty:
                    print(f"-> BOTTLENECK: Remaining translators lack broad Industry Group experience in any of {req_grps}.")
                    return
            else:
                print(f"FAILED: None of the required industry groups {req_grps} exist in our historical data.")
                return

        print("SUCCESS: Translators are available.")

    def get_eligible_translators(self, task_reqs):
        """
        THE LOGIC CORE: Filters out translators based on requirements and dynamic TASK TYPE business rules.
        Returns a dataframe of all candidates who mathematically pass all tests.
        """
        domain = self.translators_df.copy()

        # ==========================================
        # PRE-PROCESSING: DYNAMIC TASK TYPE RULES
        # ==========================================
        working_reqs = task_reqs.copy()
        task_type = working_reqs.get('task_type', 'Translation')
        followed_by = working_reqs.get('followed_by', None)
        prev_exp = working_reqs.get('previous_translator_experience', 0.0)

        # Apply specific business logic based on the task classification
        if task_type == 'TEST':
            # "TEST": Ignore budget/price so we can find the absolute best talent.
            if 'max_hourly_rate' in working_reqs: del working_reqs['max_hourly_rate']

        elif task_type == 'Training':
            # "Training": Quality doesn't matter, and no past experience is required.
            if 'min_quality' in working_reqs: del working_reqs['min_quality']
            working_reqs['min_subindustry_experience'] = 0
            working_reqs['min_industry_experience'] = 0
            working_reqs['min_industry_group_experience'] = 0

        elif task_type == 'Translation' and followed_by == 'ProofReading':
            # "Translation (with Proofing)": We can accept a slightly lower quality translator
            # because a superior proofreader will catch mistakes later, saving the client money.
            if 'min_quality' in working_reqs:
                working_reqs['min_quality'] = max(0, working_reqs['min_quality'] - 1.0)

        # Ensure the candidate has at least *some* experience in the specific task type (e.g. DTP)
        if task_type != 'Training':
            task_exp_col = f"{task_type}_experience"
            if task_exp_col in domain.columns:
                domain = domain[domain[task_exp_col] > 0]

        # ==========================================
        # LANGUAGE & FINANCIAL METRICS
        # ==========================================
        pair = working_reqs.get('language_pair')
        if pair not in domain.columns: return pd.DataFrame()
        domain = domain[domain[pair].notna()]

        # Filter by Budget, Quality, and On-Time
        if 'max_hourly_rate' in working_reqs: domain = domain[domain[pair] <= working_reqs['max_hourly_rate']]
        if 'min_quality' in working_reqs: domain = domain[domain['AVERAGE_QUALITY'] >= working_reqs['min_quality']]
        if 'min_on_time_score' in working_reqs: domain = domain[domain['ON_TIME_SCORE'] >= working_reqs['min_on_time_score']]

        # ==========================================
        # 2. SCHEDULE & ASYNCHRONOUS CAPACITY
        # ==========================================
        window_days = working_reqs.get('window_days', 1)

        if 'task_date' in working_reqs:
            start_date = pd.to_datetime(working_reqs['task_date'])
            day_mapping = {'Monday': 'MON', 'Tuesday': 'TUES', 'Wednesday': 'WED', 'Thursday': 'THURS', 'Friday': 'FRI', 'Saturday': 'SAT', 'Sunday': 'SUN'}

            # Check if they work on ANY of the available days in the deadline window
            works_any_day = pd.Series(False, index=domain.index)
            for i in range(window_days):
                current_date = start_date + pd.Timedelta(days=i)
                schedule_col = day_mapping.get(current_date.day_name())
                if schedule_col in domain.columns:
                    works_any_day = works_any_day | (domain[schedule_col] == 1)

            domain = domain[works_any_day]

        if 'task_length_hours' in working_reqs and 'START' in domain.columns and 'END' in domain.columns:
            clean_start = domain['START'].astype(str).str.replace('.', '', regex=False).str.upper()
            clean_end = domain['END'].astype(str).str.replace('.', '', regex=False).str.upper()

            shift_starts = pd.to_datetime(clean_start, format='mixed', errors='coerce')
            shift_ends = pd.to_datetime(clean_end, format='mixed', errors='coerce')
            shift_ends = shift_ends.mask(shift_ends < shift_starts, shift_ends + pd.Timedelta(days=1))

            # Calculate their total flexible bandwidth for a single day
            shift_length = (shift_ends - shift_starts).dt.total_seconds() / 3600
            domain['DAILY_CAPACITY'] = shift_length.fillna(0).apply(lambda x: x + 24 if x < 0 else x)

            # Math: If a task is 2 hours and they have 3 days, they only need 0.66 hours of free time a day.
            required_daily_capacity = working_reqs['task_length_hours'] / window_days
            domain = domain[domain['DAILY_CAPACITY'] >= required_daily_capacity]

        # ==========================================
        # 3-TIER HIERARCHICAL EXPERTISE
        # ==========================================
        def filter_by_list(domain_df, req_list, prefix, min_exp):
            """Helper function to filter dataframe based on a list of acceptable industries."""
            valid_cols = [f"{prefix}_{req}" for req in req_list if f"{prefix}_{req}" in domain_df.columns]
            if not valid_cols: return pd.DataFrame()

            # NEW BUSINESS RULE: Dependency Override for Review Tasks
            # Proofreaders and Spotcheckers MUST have more experience than the original translator
            if task_type in ['ProofReading', 'Spotcheck'] and prev_exp > 0:
                required_exp = max(min_exp, prev_exp + 0.1)
            else:
                required_exp = min_exp

            mask = (domain_df[valid_cols] >= required_exp).any(axis=1)
            return domain_df[mask]

        # Process the tiers from strictest (Sub-Industry) to broadest (Group)
        if 'required_subindustry' in working_reqs and working_reqs['required_subindustry']:
            domain = filter_by_list(domain, working_reqs['required_subindustry'], 'SUB', working_reqs.get('min_subindustry_experience', 1.0))
            if domain.empty: return domain

        elif 'required_industry' in working_reqs and working_reqs['required_industry']:
            domain = filter_by_list(domain, working_reqs['required_industry'], 'IND', working_reqs.get('min_industry_experience', 1.0))
            if domain.empty: return domain

        elif 'required_industry_group' in working_reqs and working_reqs['required_industry_group']:
            domain = filter_by_list(domain, working_reqs['required_industry_group'], 'GRP', working_reqs.get('min_industry_group_experience', 1.0))
            if domain.empty: return domain

        return domain

    def split_task_across_days(self, task_reqs):
        """
        Dynamically splits a task across the exact number of days between the start date and the deadline.
        Ignores strict start hours and focuses purely on Daily Capacity.
        """
        start_date = pd.to_datetime(task_reqs['task_date'])

        if 'task_deadline' in task_reqs and pd.notna(task_reqs['task_deadline']):
            end_date = pd.to_datetime(task_reqs['task_deadline'])
            num_days = max(2, (end_date - start_date).days + 1)
        else:
            num_days = 2
            end_date = start_date + pd.Timedelta(days=1)

        print(f"\n--- INITIATING {num_days}-DAY TASK SPLIT (Deadline: {end_date.strftime('%Y-%m-%d')}) ---")
        domain = self.translators_df.copy()

        # Apply Base Constraints
        pair = task_reqs.get('language_pair')
        if pair in domain.columns: domain = domain[domain[pair].notna()]
        if 'max_hourly_rate' in task_reqs: domain = domain[domain[pair] <= task_reqs['max_hourly_rate']]
        if 'min_quality' in task_reqs: domain = domain[domain['AVERAGE_QUALITY'] >= task_reqs['min_quality']]
        if 'min_on_time_score' in task_reqs: domain = domain[domain['ON_TIME_SCORE'] >= task_reqs['min_on_time_score']]

        # Apply Hierarchical Expertise limits
        def filter_by_list(domain_df, req_list, prefix, min_exp):
            valid_cols = [f"{prefix}_{req}" for req in req_list if f"{prefix}_{req}" in domain_df.columns]
            if not valid_cols: return pd.DataFrame()
            mask = (domain_df[valid_cols] >= min_exp).any(axis=1)
            return domain_df[mask]

        if 'required_subindustry' in task_reqs and task_reqs['required_subindustry']:
            domain = filter_by_list(domain, task_reqs['required_subindustry'], 'SUB', task_reqs.get('min_subindustry_experience', 1.0))
        elif 'required_industry' in task_reqs and task_reqs['required_industry']:
            domain = filter_by_list(domain, task_reqs['required_industry'], 'IND', task_reqs.get('min_industry_experience', 1.0))
        elif 'required_industry_group' in task_reqs and task_reqs['required_industry_group']:
            domain = filter_by_list(domain, task_reqs['required_industry_group'], 'GRP', task_reqs.get('min_industry_group_experience', 1.0))

        if domain.empty: return domain

        # SCHEDULE AVAILABILITY (Must be available for the entire window)
        day_mapping = {
            'Monday': 'MON', 'Tuesday': 'TUES', 'Wednesday': 'WED',
            'Thursday': 'THURS', 'Friday': 'FRI', 'Saturday': 'SAT', 'Sunday': 'SUN'
        }
        for i in range(num_days):
            current_date = start_date + pd.Timedelta(days=i)
            schedule_col = day_mapping.get(current_date.day_name())
            if schedule_col in domain.columns:
                domain = domain[domain[schedule_col] == 1]

        print(f">> Verified consecutive availability from {start_date.day_name()} to {end_date.day_name()}.")

        # MULTI-DAY SHIFT CAPACITY (Ignoring strict start/end hours!)
        if 'START' in domain.columns and 'END' in domain.columns:
            clean_start = domain['START'].astype(str).str.replace('.', '', regex=False).str.upper()
            clean_end = domain['END'].astype(str).str.replace('.', '', regex=False).str.upper()
            start_times = pd.to_datetime(clean_start, format='mixed', errors='coerce')
            end_times = pd.to_datetime(clean_end, format='mixed', errors='coerce')

            # Calculate their total daily bandwidth
            shift_length = (end_times - start_times).dt.total_seconds() / 3600
            domain['DAILY_CAPACITY'] = shift_length.fillna(0).apply(lambda x: x + 24 if x < 0 else x)

            # Divide the total volume of work by the number of days allowed
            required_daily_capacity = task_reqs.get('task_length_hours', 8) / num_days
            print(f">> Bypassing strict start-time constraints. Task requires {required_daily_capacity:.2f} hours/day of flexible bandwidth.")

            # Filter strictly by bandwidth
            domain = domain[domain['DAILY_CAPACITY'] >= required_daily_capacity]

        if not domain.empty:
            print(f"SUCCESS: Found {len(domain)} translators who have the daily bandwidth to finish this before the deadline.")
        else:
            print(f"FAILED: No translators have enough flexible daily bandwidth to finish this before the deadline.")

        return domain

    def split_task_across_translators(self, task_reqs, num_translators=2):
        """
        Splits a task so multiple translators can work on it SIMULTANEOUSLY.
        E.g., An 8-hour task needs 2 translators working 4 hours each.
        """
        print(f"\n--- INITIATING PARALLEL SPLIT: {num_translators} TRANSLATORS ---")
        split_reqs = task_reqs.copy()

        # Update capacity requirements for parallel work
        if 'task_length_hours' in split_reqs:
            split_reqs['task_length_hours'] = split_reqs['task_length_hours'] / num_translators

            # Show the exact time window if task_start_time is used
            if 'task_start_time' in split_reqs:
                try:
                    task_start = pd.to_datetime(split_reqs['task_start_time'])
                    task_end = task_start + pd.Timedelta(hours=split_reqs['task_length_hours'])
                    print(f">> Reduced required shift to {split_reqs['task_length_hours']:.2f} hours per translator (between {task_start.strftime('%H:%M')} and {task_end.strftime('%H:%M')}).")
                except Exception:
                    # Fallback just in case datetime parsing fails
                    print(f">> Reduced required shift to {split_reqs['task_length_hours']:.2f} hours per translator.")
            else:
                print(f">> Reduced required daily capacity to {split_reqs['task_length_hours']:.2f} hours per translator.")

        # Let the robust get_eligible_translators method handle all the complex filtering
        domain = self.get_eligible_translators(split_reqs)

        # Check if we have enough translators to form the required team size
        if len(domain) >= num_translators:
            print(f"SUCCESS: Found {len(domain)} available translators. Forming team of {num_translators}.")
            return domain
        else:
            print(f"FAILED: Need {num_translators} translators, but only found {len(domain)}.")
            return pd.DataFrame()

    def get_translators_with_fallback(self, task_reqs):
        """
        THE ESCALATION PIPELINE:
        Attempts Strict -> Industry -> Group -> Wildcard -> Global.
        """
        # --- NEW: REQUIRED DAILY CAPACITY BYPASS ---
        task_effort = task_reqs.get('task_length_hours', 0)
        window_days = task_reqs.get('window_days', 1)
        required_daily = task_effort / window_days

        if required_daily > 10.0:
            print(f"\n[SYSTEM BYPASS] Task requires {required_daily:.2f} hours/day. Bypassing single search and forcing Team Assembly.")
            return pd.DataFrame()

        print("\n--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---")
        eligible = self.get_eligible_translators(task_reqs)

        if not eligible.empty:
            print(f"SUCCESS: Found {len(eligible)} specialists matching Sub-Industry.")
            return eligible

        print("FAILED: No Sub-Industry specialists found. Initiating Fallback...")
        relaxed_reqs = task_reqs.copy()

        # --- ATTEMPT 2: RELAX TO INDUSTRY ---
        if 'required_subindustry' in relaxed_reqs and relaxed_reqs['required_subindustry'] and 'required_industry' in relaxed_reqs and relaxed_reqs['required_industry']:
            print(f"\n--- ATTEMPT 2: Relaxing to Mid-Level Industry ---")
            del relaxed_reqs['required_subindustry']

            lvl2_eligible = self.get_eligible_translators(relaxed_reqs)
            if not lvl2_eligible.empty:
                print(f"COMPROMISE SUCCESS: Found {len(lvl2_eligible)} mid-level specialists.")
                return lvl2_eligible
            print("FAILED: Mid-level Industry search didn't yield enough translators.")

        # --- ATTEMPT 3: RELAX TO INDUSTRY GROUP ---
        if 'required_industry' in relaxed_reqs and relaxed_reqs['required_industry'] and 'required_industry_group' in relaxed_reqs and relaxed_reqs['required_industry_group']:
            print(f"\n--- ATTEMPT 3: Relaxing to Broad Industry Group ---")
            del relaxed_reqs['required_industry']

            lvl3_eligible = self.get_eligible_translators(relaxed_reqs)
            if not lvl3_eligible.empty:
                print(f"COMPROMISE SUCCESS: Found {len(lvl3_eligible)} generalists in the Industry Group.")
                return lvl3_eligible
            print("FAILED: Broad Industry Group search failed.")

        # --- ATTEMPT 4: TARGETED WILDCARD RELAXATION ---
        wildcard = relaxed_reqs.get('wildcard', 'balanced')
        print(f"\n--- ATTEMPT 4: Targeted Wildcard Relaxation ({wildcard.upper()}) ---")

        wildcard_reqs = relaxed_reqs.copy()

        if wildcard == 'quality':
            wildcard_reqs['min_quality'] = max(0, wildcard_reqs['min_quality'] - 1.5)
            print(f">> Wildcard Triggered: Lowered minimum quality significantly to {wildcard_reqs['min_quality']}")

        elif wildcard == 'price':
            wildcard_reqs['max_hourly_rate'] = wildcard_reqs['max_hourly_rate'] * 1.25 # 25% budget boost
            print(f">> Wildcard Triggered: Increased budget threshold by 25% to ${wildcard_reqs['max_hourly_rate']:.2f}")

        elif wildcard == 'deadline' or wildcard == 'time':
            wildcard_reqs['min_on_time_score'] = max(0, wildcard_reqs['min_on_time_score'] - 0.20)
            wildcard_reqs['capacity_tolerance'] = 0.70
            print(f">> Wildcard Triggered: Relaxed On-Time score to {wildcard_reqs['min_on_time_score']} and allowed 30% schedule shift")
        else:
            print(">> No specific wildcard provided or recognized. Moving to global relaxation.")

        if wildcard in ['quality', 'price', 'deadline']:
            wildcard_eligible = self.get_eligible_translators(wildcard_reqs)
            if not wildcard_eligible.empty:
                print(f"COMPROMISE SUCCESS: Found {len(wildcard_eligible)} translators by flexing the client's {wildcard.upper()} preference.")
                return wildcard_eligible
            print(f"FAILED: Flexing the {wildcard.upper()} was not enough to find a candidate.")

        # --- ATTEMPT 5: GLOBAL RELAXATION ---
        final_eligible = self.get_eligible_translators(relaxed_reqs)

        if not final_eligible.empty:
            print(f"COMPROMISE SUCCESS: Found {len(final_eligible)} translators using global relaxation.")
            return final_eligible
        else:
            print("\nCRITICAL FAILURE: Maximum global relaxation reached. No translators available.")
            return pd.DataFrame()


    def get_workflow_candidates(self, company_name, clients_df, historical_df, task_date, task_start_time,
                                translation_hours, proofreading_hours, language_pair,
                                base_task_type='Translation', selected_translator_name=None):
        """
        THE WORKFLOW PIPELINE: Handles dependent tasks (e.g. Translation followed by Proofreading).

        Because a Proofreader MUST have more experience than the initial Translator,
        we must break this into a Two-Step Function (like an API waiting for UI input).

        Step 1. If 'selected_translator_name' is None: Run the base task and return eligible translators.
        Step 2. If 'selected_translator_name' is provided: Run the proofreading task, calculate the time
                offset, and ensure the proofreader beats the translator's experience score.
        """
        print(f"\n=======================================================")
        print(f"  WORKFLOW ENGINE: {base_task_type.upper()} -> PROOFREADING")
        print(f"=======================================================")

        # ---------------------------------------------------------
        # STEP 1: GET BASE CANDIDATES
        # ---------------------------------------------------------
        base_reqs = self.build_client_requirements(
            company_name=company_name, clients_df=clients_df, historical_df=historical_df,
            task_date=task_date, task_start_time=task_start_time, task_length_hours=translation_hours,
            language_pair=language_pair, task_type=base_task_type
        )

        base_candidates = self.get_translators_with_fallback(base_reqs)

        if base_candidates.empty:
            print(f"\n[SYSTEM ERROR] Cannot staff the {base_task_type}. Aborting workflow.")
            return pd.DataFrame(), pd.DataFrame()

        # Phase 1 Stop: If the PM hasn't picked anyone yet, return the list so they can choose!
        if selected_translator_name is None:
            print(f"\n[SYSTEM] Found {len(base_candidates)} base candidates. Awaiting PM selection to generate ProofReaders.")
            return base_candidates, pd.DataFrame()

        # ---------------------------------------------------------
        # STEP 2: EXTRACT DATA FOR THE CHOSEN TRANSLATOR
        # ---------------------------------------------------------
        chosen_data = base_candidates[base_candidates['NAME'] == selected_translator_name]

        if chosen_data.empty:
            print(f"\n[SYSTEM ERROR] Translator '{selected_translator_name}' is not in the eligible list!")
            return base_candidates, pd.DataFrame()

        chosen_translator = chosen_data.iloc[0]

        # Loop through their stats to find exactly how much experience they have in the required industry.
        # This will be the score the Proofreader must beat.
        exp_score = 0.0
        for level, prefix in [('required_subindustry', 'SUB'), ('required_industry', 'IND'), ('required_industry_group', 'GRP')]:
            if level in base_reqs and base_reqs[level]:
                for item in base_reqs[level]:
                    col_name = f"{prefix}_{item}"
                    if col_name in chosen_translator.index:
                        exp_score = max(exp_score, chosen_translator[col_name])
                if exp_score > 0:
                    break

        # ---------------------------------------------------------
        # STEP 3: AUTO-SCHEDULE & GET PROOFREADERS
        # ---------------------------------------------------------
        # Time Offset Math: If Translation starts at 9am and takes 4 hours, Proofreading MUST start at 1pm.
        base_start_dt = pd.to_datetime(f"{task_date} {task_start_time}")
        proof_start_dt = base_start_dt + pd.Timedelta(hours=translation_hours)

        print(f"\n=======================================================")
        print(f"  PHASE 2: {selected_translator_name.upper()} SELECTED FOR {base_task_type.upper()}")
        print(f"  >> Their Sector Experience: {exp_score:.2f} hours")
        print(f"  >> Finding ProofReaders for {proof_start_dt.strftime('%H:%M')} (Must beat {exp_score:.2f} hrs)")
        print(f"=======================================================")

        # Build new requirements specifically for the Proofreader
        proof_reqs = self.build_client_requirements(
            company_name=company_name, clients_df=clients_df, historical_df=historical_df,
            task_date=proof_start_dt.strftime('%Y-%m-%d'),
            task_start_time=proof_start_dt.strftime('%H:%M'),
            task_length_hours=proofreading_hours,
            language_pair=language_pair,
            task_type='ProofReading',
            previous_translator_experience=exp_score
        )

        proof_candidates = self.get_translators_with_fallback(proof_reqs)

        if not proof_candidates.empty:
            # Business Logic: A translator cannot proofread their own work. Remove them from the list.
            proof_candidates = proof_candidates[proof_candidates['NAME'] != selected_translator_name]

        return base_candidates, proof_candidates

# =========================================================================================
# EXECUTION AND TESTING: TWO-PHASE WORKFLOW
# =========================================================================================

# Initialize Solver
csp_solver = TaskAssignmentCSP(translators_df)

# DEFINE PIPELINE PARAMETERS
company_name = "Accesstra"
task_date = "2023-04-24"
task_deadline = "2023-04-26"    # Deadline Date (Allows for Asynchronous Multi-Day work)
task_start_time = "09:00"
task_end_time = "17:00"
task_hours = 4.0                # ACTUAL EFFORT (e.g. 4 hours of actual typing)
proofreading_hours = 2.0        # ACTUAL EFFORT for Proofreader
language = "English_Spanish (Iberian)"

print("\n" + "="*60)
print(f"  PHASE 1: PROCESSING THE BASE TRANSLATION TASK")
print("="*60)

# --- 2. PHASE 1: EXECUTE BASE TASK ---
task_requirements = csp_solver.build_client_requirements(
    company_name=company_name,
    clients_df=df3,
    historical_df=df1,
    task_date=task_date,
    task_deadline=task_deadline,
    task_start_time=task_start_time,
    task_end_time=task_end_time,
    task_length_hours=task_hours,   # <-- EXACT EFFORT PASSED HERE
    language_pair=language,
    task_type="Translation",
    followed_by="ProofReading"
)

if task_requirements:
    # Attempt to assign the task normally (escalating if necessary)
    final_candidates = csp_solver.get_translators_with_fallback(task_requirements)

    # --- WILDCARD-DRIVEN SPLIT STRATEGY ---
    # If the standard search fails, it decides how to split the task based on the client's Wildcard.
    if final_candidates.empty:
        wildcard = task_requirements.get('wildcard', 'balanced').lower()

        # Scenario A: Client is flexible on time. Priority -> Extend the deadline across multiple days to save costs.
        if wildcard in ['deadline']:
            print(f"\n[SYSTEM] Wildcard is {wildcard.upper()}. Prioritizing Multi-Day Split to save costs.")
            final_candidates = csp_solver.split_task_across_days(task_requirements) # It calculates days automatically!

            if final_candidates.empty:
                final_candidates = csp_solver.split_task_across_translators(task_requirements, num_translators=2)

        # Scenario B: Client is flexible on Price/Quality but Strict on Deadline. Priority -> Build a Team.
        else:
            print(f"\n[SYSTEM] Wildcard is {wildcard.upper()} (Deadline strict). Prioritizing Team Assembly.")
            final_candidates = csp_solver.split_task_across_translators(task_requirements, num_translators=2)

            if final_candidates.empty:
                final_candidates = csp_solver.split_task_across_days(task_requirements) # It calculates days automatically!


    # --- DISPLAY PHASE 1 RESULTS ---
    if not final_candidates.empty:
        print(f"\n--- FOUND {len(final_candidates)} ELIGIBLE TRANSLATORS ---")
        desired_columns = ['NAME', language, 'DAILY_CAPACITY', 'AVERAGE_QUALITY', 'ON_TIME_SCORE']

        # Dynamically append the correct Expertise column so the PM can verify their experience
        if 'required_subindustry' in task_requirements and task_requirements['required_subindustry']:
            desired_columns.append(f"SUB_{task_requirements['required_subindustry'][0]}")
        elif 'required_industry' in task_requirements and task_requirements['required_industry']:
            desired_columns.append(f"IND_{task_requirements['required_industry'][0]}")
        elif 'required_industry_group' in task_requirements and task_requirements['required_industry_group']:
            desired_columns.append(f"GRP_{task_requirements['required_industry_group'][0]}")

        # Safe Filtering: Only print columns that actually exist to avoid Pandas KeyErrors
        final_cols = [col for col in desired_columns if col in final_candidates.columns]
        print(final_candidates[final_cols].head(10)) # Print top 10 for neatness
    else:
        print("\n[SYSTEM FATAL ERROR] Impossible constraints.")
        csp_solver.diagnose_bottleneck(task_requirements) # Run the diagnostic to figure out why it failed!


# PHASE 2: DEPENDENT TASK WORKFLOW (E.g. PostEditing or Proofreading)
# If Phase 1 succeeded, the UI/Project Manager would select a translator.
# Here, we simulate that selection algorithmically.
if not final_candidates.empty:

    # Simulate picking the highest quality translator from the generated list
    selected_translator = final_candidates.sort_values(by='AVERAGE_QUALITY', ascending=False).iloc[0]
    selected_name = selected_translator['NAME']

    # Dynamically extract their exact experience score so the Proofreader can beat it
    exp_score = 0.0
    for level, prefix in [('required_subindustry', 'SUB'), ('required_industry', 'IND'), ('required_industry_group', 'GRP')]:
        if level in task_requirements and task_requirements[level]:
            for item in task_requirements[level]:
                col_name = f"{prefix}_{item}"
                if col_name in selected_translator.index:
                    exp_score = max(exp_score, selected_translator[col_name])
            if exp_score > 0: break

    # Calculate exact time offset for the Proofreader
    base_start_dt = pd.to_datetime(f"{task_date} {task_start_time}")
    proof_start_dt = base_start_dt + pd.Timedelta(hours=task_hours)

    # NEW: Calculate exactly when the Proofreader must finish
    proof_end_dt = proof_start_dt + pd.Timedelta(hours=proofreading_hours)

    print("\n\n" + "="*60)
    print(f"  PHASE 2: CHECKING PROOFREADER FOR {selected_name.upper()}")
    print(f"  >> Extracted Sector Experience: {exp_score:.2f} hours")
    print(f"  >> Proofing starts at {proof_start_dt.strftime('%H:%M')} and ends at {proof_end_dt.strftime('%H:%M')}")
    print("="*60)

    # Build the requirements for the Proofreader using the new Date/Time arguments!
    proof_requirements = csp_solver.build_client_requirements(
        company_name=company_name,
        clients_df=df3,
        historical_df=df1,
        task_date=proof_start_dt.strftime('%Y-%m-%d'),
        task_deadline=proof_end_dt.strftime('%Y-%m-%d'),  # NEW
        task_start_time=proof_start_dt.strftime('%H:%M'),
        task_end_time=proof_end_dt.strftime('%H:%M'),     # NEW
        task_length_hours=proofreading_hours,
        language_pair=language,
        task_type="ProofReading",
        previous_translator_experience=exp_score
    )

    if proof_requirements:
        proof_candidates = csp_solver.get_translators_with_fallback(proof_requirements)

        # Enforce Conflict of Interest Rule (Cannot proofread your own work)
        if not proof_candidates.empty:
            proof_candidates = proof_candidates[proof_candidates['NAME'] != selected_name]

        # DISPLAY PHASE 2 RESULTS
        if not proof_candidates.empty:
            print(f"\n--- FOUND {len(proof_candidates)} SUPERIOR PROOFREADERS ---")
            proof_cols = [col for col in desired_columns if col in proof_candidates.columns]
            print(proof_candidates[proof_cols].head(10))
        else:
            print(f"\n[SYSTEM WARNING] No ProofReaders found who have more than {exp_score:.2f} hours of experience and are available at {proof_start_dt.strftime('%H:%M')}.")
            csp_solver.diagnose_bottleneck(proof_requirements)

============================================================
  PHASE 1: PROCESSING THE BASE TRANSLATION TASK
============================================================

--- AUTO-LOADED PROFILE FOR: Accesstra ---
>> Task Effort: 4.00 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 70 specialists matching Sub-Industry.

--- FOUND 70 ELIGIBLE TRANSLATORS ---
                NAME  English_Spanish (Iberian)  DAILY_CAPACITY  \
5           Abelardo                       17.0            10.0
26            Agueda                       13.0            10.0
47         Alejandro                       16.0            10.0
49      Alejo Esdras                       17.0            10.0
64           Alfredo                       12.0            10.0
82          Ambrosia                       18.0            10.0
83     Ambrosia Adon                       17.0            10.0
106      Ana Marcela                       14.0            10.0
130    Aniano Julian                       19.0            10.0
153  Ariadna Laurina                       15.0            10.0

     AVERAGE_QUALITY  ON_TIME_SCORE  SUB_Apparel, Accessories & Luxury Goods
5           6.860231       0.944696                                47.343611
26          7.172670       0.943680                                 9.350556
47          7.483035       0.735498                               797.048889
49          7.163842       0.956685                               102.507500
64          6.857687       0.804320                                 4.875833
82          6.737430       0.681564                                 4.328056
83          6.973302       0.911829                                 1.471667
106         7.537084       0.992327                                30.896389
130         7.291150       0.707080                              1090.666111
153         7.194407       0.918342                                12.784444


============================================================
  PHASE 2: CHECKING PROOFREADER FOR CELTON
  >> Extracted Sector Experience: 1.89 hours
  >> Proofing starts at 13:00 and ends at 15:00
============================================================

--- AUTO-LOADED PROFILE FOR: Accesstra ---
>> Task Effort: 2.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 7 specialists matching Sub-Industry.

--- FOUND 7 SUPERIOR PROOFREADERS ---
              NAME  English_Spanish (Iberian)  DAILY_CAPACITY  \
106    Ana Marcela                       14.0            10.0
157        Armando                       15.0            10.0
279        Clarice                       20.0            10.0
323  David Antonio                       18.0            10.0
591    Juan Rafael                       15.0            10.0
892         Samuel                       14.0            10.0
916         Sophie                       16.0            10.0

     AVERAGE_QUALITY  ON_TIME_SCORE  SUB_Apparel, Accessories & Luxury Goods
106         7.537084       0.992327                                30.896389
157         7.619233       0.951267                                 3.416389
279         7.895639       0.834891                                 3.927222
323         7.561746       0.649052                               208.406111
591         7.610169       0.831093                               106.649722
892         7.913043       0.923913                                 2.578333
916         7.513514       0.810811                                12.639167

# Dynamic Weighted Score model

While the Constraint Satisfaction Problem (CSP) solver is responsible for Feasibility (filtering out translators who strictly cannot perform the task), the system requires an Objective Function to handle Optimization (determining who is the absolute best choice among the survivors).

To achieve this, we transition from strict Boolean filtering to a Multi-Criteria Decision Analysis (MCDA) model. Every eligible candidate is graded on a 100-point scale.

However, rather than using a static formula, the system employs Context-Aware Dynamic Weighting. The algorithm intelligently shifts the mathematical weight of each variable based on the specific client's business priorities (the "Wildcard") and the structural nature of the task.

- **The Mathematical Model**

    The final Suitability Score is a linear combination of four normalized metrics, multiplied by their dynamic context weights: $Score = (N_{quality} \times W_q) + (N_{reliability} \times W_r) + (N_{margin} \times W_m) + (N_{expertise} \times W_e)$

    Where $\sum W = 100$

- **Feature Normalization ($N$)**
    
    Because our raw data operates on entirely different scales (e.g., a quality score out of 10 vs. an hourly rate in dollars vs. experience in hours), we must first normalize every variable to a standard scale of $0.0$ to $1.0$.
    - $N_{quality}$ (Quality Vector): Extracted directly from their historical average. A score of $8.5$ becomes $0.85$.
    - $N_{reliability}$ (Reliability Vector): Extracted from their on-time delivery ratio. A perfect historical delivery rate is already a $1.0$.
    - $N_{margin}$ (Profit Margin Vector): This measures how much money the agency saves by hiring this translator compared to the client's maximum budget.
    
      Formula: $\frac{MaxBudget - TranslatorRate}{MaxBudget}$
      
      Example: If the client pays 20€/hr and the translator costs 15€/hr, the normalized score is 0.25€ (a 25% profit margin).
    - $N_{expertise}$ (Specialization Vector): We calculate their cumulative hours in the requested sub-industry/industry. We apply a diminishing returns cap at 50 hours (representing full mastery).
    
      Formula: $\min\left(1.0, \frac{Logged Hours}{50}\right)$

- **Dynamic Weights ($W$)**

    The true power of the algorithm lies in how the weights dynamically shift. The baseline weight distribution is Balanced (40% Quality, 30% Reliability, 20% Profit, 10% Expertise). However, the engine intercepts the Client's WILDCARD preference to rewrite the objective function in real-time:

    - If *Wildcard* = PRICE: The system recognizes a highly price-sensitive environment. It drops the Quality and Reliability weights to 20% each, and surges the Profit Margin weight to 50%. The algorithm will now actively hunt for the cheapest viable translator to maximize agency margins without violating the baseline CSP constraints.

    - If *Wildcard* = DEADLINE: The system anticipates an urgent, time-sensitive delivery. It drops the Quality and Profit weights, and surges the Reliability weight to 60%. The algorithm actively punishes any translator with a history of late deliveries, regardless of how cheap or high-quality they are.

    - If *Task Type* = TEST: The system applies a Hard Override. Profit Margin and Reliability weights are forced to 0%, and Quality is surged to 80%. Because this is a client qualification test, the algorithm knows the agency must absorb the financial cost to submit the highest quality text possible to win the long-term contract.

In [93]:
def rank_candidates(candidates_df, task_reqs):
    """
    POST-CSP OPTIMIZATION: Grades eligible translators on a 100-point scale.
    Features 'Resource Conservation Mode' to prevent wasting top-tier talent on low-tier tasks.
    """
    if candidates_df.empty:
        return candidates_df

    df = candidates_df.copy()

    # 1. DEFINE DYNAMIC WEIGHTS
    w_qual, w_rel, w_marg, w_exp = 40, 30, 20, 10

    wildcard = task_reqs.get('wildcard', 'balanced').lower()
    task_type = task_reqs.get('task_type', 'Translation')

    if wildcard == 'quality':
        w_qual, w_rel, w_marg, w_exp = 60, 20, 10, 10
    elif wildcard == 'price':
        w_qual, w_rel, w_marg, w_exp = 20, 20, 50, 10
    elif wildcard in ['deadline', 'time', 'schedule']:
        w_qual, w_rel, w_marg, w_exp = 20, 60, 10, 10

    if task_type == 'TEST':
        w_qual, w_rel, w_marg, w_exp = 80, 0, 0, 20

    # 2. CALCULATE NORMALIZED SCORES

    # --- NEW: RESOURCE CONSERVATION LOGIC ---
    min_quality = task_reqs.get('min_quality', 0.0)

    if wildcard == 'quality' or task_type == 'TEST':
        # PREMIUM MODE: The client wants the absolute best. Maximize the score.
        norm_quality = df['AVERAGE_QUALITY'] / 10.0
    else:
        # CONSERVATION MODE: Reward translators who are closest to the minimum requirement.
        # Penalize "Over-Specification" so we save top talent for harder jobs.
        excess_quality = (df['AVERAGE_QUALITY'] - min_quality).clip(lower=0)
        norm_quality = (1.0 - (excess_quality / 10.0)).clip(lower=0, upper=1.0)

    # Reliability (Already on a 0 to 1 scale)
    norm_reliability = df['ON_TIME_SCORE']

    # Margin (Cheaper = Higher Score)
    pair = task_reqs.get('language_pair')
    max_rate = task_reqs.get('max_hourly_rate', df[pair].max())
    if max_rate > 0:
        norm_margin = ((max_rate - df[pair]) / max_rate).clip(lower=0)
    else:
        norm_margin = 0

    # Expertise (Calculate total hours logged)
    exp_score = pd.Series(0, index=df.index)
    for level, prefix in [('required_subindustry', 'SUB'), ('required_industry', 'IND'), ('required_industry_group', 'GRP')]:
        if level in task_reqs and task_reqs[level]:
            for item in task_reqs[level]:
                col_name = f"{prefix}_{item}"
                if col_name in df.columns:
                    exp_score += df[col_name]
            break

    # Apply Conservation Logic to Expertise as well
    if wildcard == 'quality' or task_type == 'TEST':
        norm_expertise = (exp_score / 50.0).clip(upper=1.0)
    else:
        # If the task only requires 1 hour of experience, someone with 500 hours is overqualified
        min_exp = 1.0
        excess_exp = (exp_score - min_exp).clip(lower=0)
        norm_expertise = (1.0 - (excess_exp / 50.0)).clip(lower=0, upper=1.0)

    # 3. APPLY WEIGHTS TO GET FINAL 100-POINT SCORE
    df['SUITABILITY_SCORE'] = (
        (norm_quality * w_qual) +
        (norm_reliability * w_rel) +
        (norm_margin * w_marg) +
        (norm_expertise * w_exp)
    ).round(1)

    return df.sort_values(by='SUITABILITY_SCORE', ascending=False)

# --- DISPLAY PHASE 1 RESULTS ---
if not final_candidates.empty:
    # Pass the survivors into the standalone ranking function!
    final_candidates = rank_candidates(final_candidates, task_requirements)

    print(f"\n--- FOUND {len(final_candidates)} ELIGIBLE TRANSLATORS ---")

    # Add SUITABILITY_SCORE to the printout
    desired_columns = ['SUITABILITY_SCORE', 'NAME', language, 'DAILY_CAPACITY', 'AVERAGE_QUALITY', 'ON_TIME_SCORE']

    if 'required_subindustry' in task_requirements and task_requirements['required_subindustry']:
        desired_columns.append(f"SUB_{task_requirements['required_subindustry'][0]}")
    elif 'required_industry' in task_requirements and task_requirements['required_industry']:
        desired_columns.append(f"IND_{task_requirements['required_industry'][0]}")
    elif 'required_industry_group' in task_requirements and task_requirements['required_industry_group']:
        desired_columns.append(f"GRP_{task_requirements['required_industry_group'][0]}")

    final_cols = [col for col in desired_columns if col in final_candidates.columns]

    # Print the top 10 best-ranked options
    print(final_candidates[final_cols].head(10))
else:
    print("\n[SYSTEM FATAL ERROR] Impossible constraints.")
    csp_solver.diagnose_bottleneck(task_requirements)

if proof_requirements:
    proof_candidates = csp_solver.get_translators_with_fallback(proof_requirements)

    # Enforce Conflict of Interest Rule
    if not proof_candidates.empty:
        proof_candidates = proof_candidates[proof_candidates['NAME'] != selected_name]

    # --- DISPLAY PHASE 2 RESULTS ---
    if not proof_candidates.empty:
        # Rank the proofreaders using the standalone function
        proof_candidates = rank_candidates(proof_candidates, proof_requirements)

        print(f"\n--- FOUND {len(proof_candidates)} SUPERIOR PROOFREADERS ---")
        proof_cols = [col for col in desired_columns if col in proof_candidates.columns]
        print(proof_candidates[proof_cols].head(10))
    else:
        print(f"\n[SYSTEM WARNING] No ProofReaders found...")
        csp_solver.diagnose_bottleneck(proof_requirements)

--- FOUND 70 ELIGIBLE TRANSLATORS ---
     SUITABILITY_SCORE             NAME  English_Spanish (Iberian)  \
64                65.3          Alfredo                       12.0
26                64.7           Agueda                       13.0
855               62.3   Ramiro Josafat                       14.0
892               62.3           Samuel                       14.0
646               61.4       Lino Erico                       12.0
846               60.9         Priscila                       14.0
157               60.8          Armando                       15.0
940               58.8   Ubaldo Maitane                       14.0
106               58.8      Ana Marcela                       14.0
153               58.5  Ariadna Laurina                       15.0

     DAILY_CAPACITY  AVERAGE_QUALITY  ON_TIME_SCORE  \
64             10.0         6.857687       0.804320
26             10.0         7.172670       0.943680
855            10.0         7.160287       0.877644
892            10.0         7.913043       0.923913
646            10.0         6.799419       0.828488
846            10.0         7.112998       0.842587
157            10.0         7.619233       0.951267
940            10.0         6.984267       0.700098
106            10.0         7.537084       0.992327
153            10.0         7.194407       0.918342

     SUB_Apparel, Accessories & Luxury Goods
64                                  4.875833
26                                  9.350556
855                                 2.163333
892                                 2.578333
646                                26.822500
846                                 5.530278
157                                 3.416389
940                                 1.833611
106                                30.896389
153                                12.784444

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 7 specialists matching Sub-Industry.

--- FOUND 7 SUPERIOR PROOFREADERS ---
     SUITABILITY_SCORE           NAME  English_Spanish (Iberian)  \
892               62.3         Samuel                       14.0
157               60.8        Armando                       15.0
106               58.8    Ana Marcela                       14.0
916               53.9         Sophie                       16.0
591               48.9    Juan Rafael                       15.0
279               45.3        Clarice                       20.0
323               37.9  David Antonio                       18.0

     DAILY_CAPACITY  AVERAGE_QUALITY  ON_TIME_SCORE  \
892            10.0         7.913043       0.923913
157            10.0         7.619233       0.951267
106            10.0         7.537084       0.992327
916            10.0         7.513514       0.810811
591            10.0         7.610169       0.831093
279            10.0         7.895639       0.834891
323            10.0         7.561746       0.649052

     SUB_Apparel, Accessories & Luxury Goods
892                                 2.578333
157                                 3.416389
106                                30.896389
916                                12.639167
591                               106.649722
279                                 3.927222
323                               208.406111

In [94]:
#TESTING CSP

In [115]:
import math
import random
from tqdm import tqdm # Optional: for a progress bar if you have it installed

def get_failure_reason(translator_name, task_reqs, translators_df):
    """
    Specifically checks one translator against all constraints to find
    exactly where they failed.
    """
    person = translators_df[translators_df['NAME'] == translator_name]
    if person.empty: return "Not in Database"
    person = person.iloc[0]

    pair = task_reqs.get('language_pair')
    if pd.isna(person.get(pair)): return "Language Pair"

    max_rate = task_reqs.get('max_hourly_rate')
    if max_rate and person.get(pair, 0) > max_rate: return "Budget"

    if person.get('AVERAGE_QUALITY', 0) < task_reqs.get('min_quality', 0): return "Quality"
    if person.get('ON_TIME_SCORE', 0) < task_reqs.get('min_on_time_score', 0): return "On-Time Score"

    has_exp = False
    for level, prefix in [('required_subindustry', 'SUB'), ('required_industry', 'IND'), ('required_industry_group', 'GRP')]:
        if level in task_reqs and task_reqs[level]:
            valid_cols = [f"{prefix}_{req}" for req in task_reqs[level] if f"{prefix}_{req}" in translators_df.columns]
            if any(person.get(col, 0) >= 1.0 for col in valid_cols):
                has_exp = True; break
    if not has_exp: return "Expertise/Industry"

    window = task_reqs.get('window_days', 1)
    req_daily = task_reqs.get('task_length_hours', 8) / window
    if person.get('DAILY_CAPACITY', 0) < req_daily: return "Daily Capacity/Shift"

    return "Conflict/Other"

def run_bulk_backtest(n_samples, raw_historical_df, clients_df, translators_df, csp_solver):
    """
    Runs hundreds of backtests instantly and groups the failed Row Indexes by reason.
    """
    results = {"Correct": 0, "Incorrect": 0, "Reasons": {}}
    indices = random.sample(range(len(raw_historical_df)), n_samples)

    print(f"--- STARTING VALIDATION OF {n_samples} HISTORICAL ASSIGNMENTS ---")

    for idx in indices:
        row = raw_historical_df.iloc[idx]
        actual_name = str(row['TRANSLATOR']).strip()

        try:
            start_dt = pd.to_datetime(row['START'])
            end_dt = pd.to_datetime(row['END'])

            # --- NEW: EXTRACT ACTUAL EFFORT FROM THE 'HOURS' COLUMN ---
            if 'HOURS' in row and pd.notna(row['HOURS']):
                task_length = float(row['HOURS'])
            elif 'TRANSLATOR_WORKING_TIME' in row and pd.notna(row['TRANSLATOR_WORKING_TIME']):
                task_length = float(row['TRANSLATOR_WORKING_TIME'])
            else:
                task_length = max(0.5, (end_dt - start_dt).total_seconds() / 3600)

            task_reqs = csp_solver.build_client_requirements(
                company_name=str(row['MANUFACTURER']).strip(),
                clients_df=clients_df, historical_df=raw_historical_df,
                task_date=start_dt.strftime('%Y-%m-%d'), task_deadline=end_dt.strftime('%Y-%m-%d'),
                task_start_time=start_dt.strftime('%H:%M'), task_end_time=end_dt.strftime('%H:%M'),
                task_length_hours=task_length, # Passes the exact HOURS value to the solver
                language_pair=f"{str(row['SOURCE_LANG']).strip()}_{str(row['TARGET_LANG']).strip()}",
                task_type=str(row['TASK_TYPE']).strip()
            )
            if not task_reqs: continue
        except Exception: continue

        candidates = csp_solver.get_translators_with_fallback(task_reqs)

        if candidates.empty:
            candidates = csp_solver.split_task_across_days(task_reqs)
            if candidates.empty:
                splits = max(2, math.ceil(task_length / 8.0))
                candidates = csp_solver.split_task_across_translators(task_reqs, num_translators=splits)

        # Check Success
        if not candidates.empty and actual_name in candidates['NAME'].tolist():
            results["Correct"] += 1
        else:
            results["Incorrect"] += 1
            reason = get_failure_reason(actual_name, task_reqs, translators_df)

            # STORE THE ROW INDEX SO WE CAN AUDIT IT LATER
            if reason not in results["Reasons"]:
                results["Reasons"][reason] = []
            results["Reasons"][reason].append(idx)

    return results

from IPython.display import display

def generate_audit_comparison(actual_name, ai_top_row, task_reqs, translators_df):
    """
    Creates a clean, dynamic side-by-side comparison.
    Hides irrelevant metrics unless the human explicitly violated them.
    """
    actual_row = translators_df[translators_df['NAME'] == actual_name]

    if actual_row.empty:
        return pd.DataFrame({"Error": [f"Translator '{actual_name}' not found in Database"]})

    actual_row = actual_row.iloc[0]
    pair = task_reqs.get('language_pair')
    req_cap = task_reqs.get('task_length_hours', 8.0) / task_reqs.get('window_days', 1)

    # BASE METRICS (Always shown)
    metrics = ["Hourly Rate", "Avg Quality"]
    reqs = [
        f"<= ${task_reqs.get('max_hourly_rate', 0)}",
        f">= {task_reqs.get('min_quality', 0)}"
    ]
    human_vals = [
        f"${actual_row.get(pair, 0)}",
        round(actual_row.get('AVERAGE_QUALITY', 0), 2) # Cleaned up decimals!
    ]
    ai_vals = [
        f"${ai_top_row.get(pair, 0)}",
        round(ai_top_row.get('AVERAGE_QUALITY', 0), 2)
    ]

    # DYNAMIC METRIC: On-Time Score
    # (Only shows if the client specifically required > 0.0)
    if task_reqs.get('min_on_time_score', 0) > 0.0:
        metrics.append("On-Time Score")
        reqs.append(f">= {task_reqs.get('min_on_time_score')}")
        human_vals.append(round(actual_row.get('ON_TIME_SCORE', 0), 2))
        ai_vals.append(round(ai_top_row.get('ON_TIME_SCORE', 0), 2))

    # DYNAMIC METRIC: Daily Capacity
    # (Only shows if it caused the human to fail, e.g., they had 0.00 hours)
    human_cap = actual_row.get('DAILY_CAPACITY', 0)
    if human_cap < req_cap or req_cap > 1.0:
        metrics.append("Daily Capacity")
        reqs.append(f">= {req_cap:.2f} hrs/day")
        human_vals.append(f"{human_cap:.2f} hrs")
        ai_vals.append(f"{ai_top_row.get('DAILY_CAPACITY', 0):.2f} hrs")

    # Note: Suitability Score was entirely removed for the CSP check!

    # BUILD TABLE
    comparison_data = {
        "Metric": metrics,
        "Requirement": reqs,
        "Human Choice (Reality)": human_vals,
        "AI #1 Rank (Model)": ai_vals
    }

    comp_df = pd.DataFrame(comparison_data)

    return comp_df.style.set_caption(f"CSP AUDIT FOR ROW: {actual_name.upper()} vs. {ai_top_row['NAME'].upper()}")\
                        .set_properties(**{'border': '1px solid black', 'text-align': 'center'})\
                        .set_properties(subset=['AI #1 Rank (Model)'], **{'background-color': '#e6f2ff', 'font-weight': 'bold'})


def backtest_with_audit(row_index, raw_historical_df, clients_df, translators_df, csp_solver):
    """
    Runs a backtest on a specific row from history, applies the asynchronous effort logic,
    and returns an Audit Dashboard for manual database verification.
    """
    # Extract Task Data
    task_row = raw_historical_df.iloc[row_index]
    actual_name = str(task_row['TRANSLATOR']).strip()
    company_name = str(task_row['MANUFACTURER']).strip()

    # Safely parse Dates, Times, and Effort
    try:
        start_dt = pd.to_datetime(task_row['START'])
        end_dt = pd.to_datetime(task_row['END'])

        task_date = start_dt.strftime('%Y-%m-%d')
        task_start_time = start_dt.strftime('%H:%M')

        task_deadline = end_dt.strftime('%Y-%m-%d')
        task_end_time = end_dt.strftime('%H:%M')

        # --- EXTRACT ACTUAL EFFORT FROM THE 'HOURS' COLUMN ---
        if 'HOURS' in task_row and pd.notna(task_row['HOURS']):
            task_length = float(task_row['HOURS'])
        elif 'TRANSLATOR_WORKING_TIME' in task_row and pd.notna(task_row['TRANSLATOR_WORKING_TIME']):
            task_length = float(task_row['TRANSLATOR_WORKING_TIME'])
        else:
            task_length = max(0.5, (end_dt - start_dt).total_seconds() / 3600)

    except Exception as e:
        print(f"❌ ROW {row_index}: Skipping due to timestamp error. {e}")
        return None

    language_pair = f"{str(task_row['SOURCE_LANG']).strip()}_{str(task_row['TARGET_LANG']).strip()}"
    task_type = str(task_row['TASK_TYPE']).strip()

    print(f"\n" + "="*70)
    print(f"  BACKTESTING EXCEL ROW #{row_index}")
    print(f"  >> Client: {company_name} | Type: {task_type}")
    print(f"  >> Window: {task_date} to {task_deadline} | Effort: {task_length:.2f} hours")
    print(f"  >> Human PM Choice: {actual_name.upper()}")
    print("="*70)

    # Build Requirements
    task_reqs = csp_solver.build_client_requirements(
        company_name=company_name,
        clients_df=clients_df,
        historical_df=raw_historical_df,
        task_date=task_date,
        task_deadline=task_deadline,
        task_start_time=task_start_time,
        task_end_time=task_end_time,
        task_length_hours=task_length,
        language_pair=language_pair,
        task_type=task_type
    )

    if not task_reqs: return None

    # Run AI Search Pipeline
    candidates = csp_solver.get_translators_with_fallback(task_reqs)

    # Dynamic Split if base search fails
    if candidates.empty:
        print("\n[SYSTEM] Attempting Multi-Day Split...")
        candidates = csp_solver.split_task_across_days(task_reqs)

        if candidates.empty:
            optimal_splits = max(2, math.ceil(task_length / 8.0))
            print(f"\n[SYSTEM] Attempting Team Split ({optimal_splits} translators)...")
            candidates = csp_solver.split_task_across_translators(task_reqs, num_translators=optimal_splits)

    # Handle Results and Generate Audit
    if candidates.empty:
        print(f"\n❌ ROW {row_index} FAILED: The AI rejected everyone. The PM choice violated hard constraints.")
        csp_solver.diagnose_bottleneck(task_reqs)
        return None

    # Grade the survivors
    ranked = rank_candidates(candidates, task_reqs)

    # Check if the human PM was correct according to the AI
    eligible_names = ranked['NAME'].tolist()
    if actual_name in eligible_names:
        rank_pos = eligible_names.index(actual_name) + 1
        print(f"\n✅ ROW {row_index} SUCCESS: The AI validates the human PM's choice!")
        print(f"The PM picked the #{rank_pos} best option out of {len(eligible_names)} total candidates.")
    else:
        print(f"\n⚠️ ROW {row_index} DISCREPANCY: The AI found {len(eligible_names)} great options, but rejected the PM's choice.")
        print("Check the Audit Table below to see which rule the PM broke:")

    # Get the AI's absolute best choice
    ai_best = ranked.iloc[0]

    # Return the beautifully formatted audit table
    return generate_audit_comparison(actual_name, ai_best, task_reqs, translators_df)

# =========================================================
# EXECUTE THE DASHBOARD
# =========================================================

# Run the test on random historical tasks
test_solver = TaskAssignmentCSP(translators_df)
stats = run_bulk_backtest(1000, df_dict['Data'], df3, translators_df, test_solver)

print("\n" + "="*80)
print("                   MODEL VALIDATION REPORT")
print("="*80)
print(f"Total Tasks Tested:  {stats['Correct'] + stats['Incorrect']}")
print(f"Accurate Matches:    {stats['Correct']} ({(stats['Correct']/(stats['Correct']+stats['Incorrect']))*100:.1f}%)")
print(f"Model Discrepancies: {stats['Incorrect']}")
print("-" * 80)
print("REASONS FOR REJECTION (And which rows to audit):")

# Sort by the most common failure reason
for reason, rows in sorted(stats['Reasons'].items(), key=lambda x: len(x[1]), reverse=True):
    print(f"\n[{len(rows)} tasks] Failed due to '{reason.upper()}'.")
    print(f"Rows to Audit -> {rows}")
print("="*80)

Se han truncado las últimas 5000 líneas del flujo de salida.
--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 5 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AssemTech ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 12 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 9.60 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 257 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.56 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 13 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 1.86 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 8 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.64 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 257 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 1.04 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 75 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NextGen Engineering ---
>> Task Effort: 0.12 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 86 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Respiro Dynamics ---
>> Task Effort: 3.38 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 11 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.27 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (PRICE) ---
>> Wildcard Triggered: Increased budget threshold by 25% to $31.25
FAILED: Flexing the PRICE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- INITIATING 2-DAY TASK SPLIT (Deadline: 2014-11-26) ---

--- INITIATING PARALLEL SPLIT: 2 TRANSLATORS ---
>> Reduced required shift to 0.14 hours per translator (between 17:41 and 17:49).
FAILED: Need 2 translators, but only found 0.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.27 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 8 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: DesarrolloYa ---
>> Task Effort: 0.06 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 158 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.22 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 75 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 2.12 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 11 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Utopia Industrial ---
>> Task Effort: 4.56 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (PRICE) ---
>> Wildcard Triggered: Increased budget threshold by 25% to $25.00
FAILED: Flexing the PRICE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- INITIATING 3-DAY TASK SPLIT (Deadline: 2020-05-07) ---

--- INITIATING PARALLEL SPLIT: 2 TRANSLATORS ---
>> Reduced required shift to 2.28 hours per translator (between 09:18 and 11:34).
FAILED: Need 2 translators, but only found 0.

--- AUTO-LOADED PROFILE FOR: PixelLabs ---
>> Task Effort: 0.36 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 81 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: VitalityTech ---
>> Task Effort: 1.61 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 17 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NetWorx ---
>> Task Effort: 2.34 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 2 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: SmartLab ---
>> Task Effort: 11.46 hours of work
>> Project Window: 11 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 288 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Hogsmeade Realty Corporation ---
>> Task Effort: 0.01 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 25 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.15 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 6 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Agricultural Machinery ---
>> Task Effort: 0.25 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 8 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.08 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 13 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: InduNet Solutions ---
>> Task Effort: 0.03 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 11 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.87 hours of work
>> Project Window: 6 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 245 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Clickforce ---
>> Task Effort: 0.17 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 28 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.03 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.12 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (PRICE) ---
>> Wildcard Triggered: Increased budget threshold by 25% to $31.25
FAILED: Flexing the PRICE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- INITIATING 2-DAY TASK SPLIT (Deadline: 2019-04-23) ---

--- INITIATING PARALLEL SPLIT: 2 TRANSLATORS ---
>> Reduced required shift to 0.06 hours per translator (between 14:30 and 14:33).
FAILED: Need 2 translators, but only found 0.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: VitalSign Innovations ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 146 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: ProdigySoft ---
>> Task Effort: 1.79 hours of work
>> Project Window: 8 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 2 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.10 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.54 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 10 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: InduNet Solutions ---
>> Task Effort: 0.04 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 11 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 1.19 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 245 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: WaveMaster ---
>> Task Effort: 0.27 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 18 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.01 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 1 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AgroTech Industries ---
>> Task Effort: 15.63 hours of work
>> Project Window: 7 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 1 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: HealthyLife ---
>> Task Effort: 0.67 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 37 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 10.97 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 8 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.25 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 11 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroMech Industries ---
>> Task Effort: 4.14 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 1 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.50 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 256 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: QuantumLogic ---
>> Task Effort: 0.31 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 288 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.04 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 13 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: SmartMed Innovations ---
>> Task Effort: 1.00 hours of work
>> Project Window: 6 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 88 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.12 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: GreenNet ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 256 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: MindSpark Media ---
>> Task Effort: 0.38 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (DEADLINE) ---
>> Wildcard Triggered: Relaxed On-Time score to 0 and allowed 30% schedule shift
FAILED: Flexing the DEADLINE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- INITIATING 2-DAY TASK SPLIT (Deadline: 2020-06-17) ---

--- INITIATING PARALLEL SPLIT: 2 TRANSLATORS ---
>> Reduced required shift to 0.19 hours per translator (between 16:00 and 16:11).
FAILED: Need 2 translators, but only found 0.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 11.75 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 8 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TecnologíaTotal ---
>> Task Effort: 8.00 hours of work
>> Project Window: 5 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 96 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: PowerPlay Engineering ---
>> Task Effort: 0.06 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 96 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 1.24 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (PRICE) ---
>> Wildcard Triggered: Increased budget threshold by 25% to $31.25
FAILED: Flexing the PRICE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- INITIATING 2-DAY TASK SPLIT (Deadline: 2021-12-01) ---

--- INITIATING PARALLEL SPLIT: 2 TRANSLATORS ---
>> Reduced required shift to 0.62 hours per translator (between 10:43 and 11:20).
FAILED: Need 2 translators, but only found 0.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: MegaForge ---
>> Task Effort: 0.42 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 103 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 1.13 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 4 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 1.25 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 2 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.19 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (DEADLINE) ---
>> Wildcard Triggered: Relaxed On-Time score to 0 and allowed 30% schedule shift
FAILED: Flexing the DEADLINE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- INITIATING 2-DAY TASK SPLIT (Deadline: 2020-10-20) ---

--- INITIATING PARALLEL SPLIT: 2 TRANSLATORS ---
>> Reduced required shift to 0.10 hours per translator (between 09:27 and 09:32).
FAILED: Need 2 translators, but only found 0.

--- AUTO-LOADED PROFILE FOR: HealthyLife ---
>> Task Effort: 1.34 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 12 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Flux Fuel ---
>> Task Effort: 2.14 hours of work
>> Project Window: 6 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 188 specialists matching Sub-Industry.


In [116]:
raw_history = df_dict['Data']

# Let's audit one of the tasks that failed
audit_table = backtest_with_audit(
    row_index=63664,    # Edit for dataset row to check
    raw_historical_df=df_dict['Data'],
    clients_df=df3,
    translators_df=translators_df,
    csp_solver=csp_solver
)

if audit_table is not None:
    display(audit_table)

======================================================================
  BACKTESTING EXCEL ROW #63664
  >> Client: NextGen Industries | Type: ProofReading
  >> Window: 2021-10-19 to 2021-10-20 | Effort: 0.08 hours
  >> Human PM Choice: PETRONILA TEOFILA
======================================================================

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.08 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 3 specialists matching Sub-Industry.

⚠️ ROW 63664 DISCREPANCY: The AI found 3 great options, but rejected the PM's choice.
Check the Audit Table below to see which rule the PM broke:

# ML MODEL

##Target Variable & Data Generator

In [110]:
import xgboost as xgb
from sklearn.model_selection import train_test_split

def calculate_efficiency_score(task_reqs, candidate_row):
    """
    The Goldilocks Formula: Rewards high profit margin,
    but strictly penalizes Over-Specification (wasting premium talent).
    """
    # Margin Calculation
    budget = task_reqs.get('max_hourly_rate', 100)
    rate = candidate_row.get(task_reqs['language_pair'], budget)
    margin = max(0, budget - rate) / budget  # Normalized 0 to 1

    # Quality Over-Specification Penalty
    req_qual = task_reqs.get('min_quality', 0)
    trans_qual = candidate_row.get('AVERAGE_QUALITY', 0)

    # Calculate how many points ABOVE the minimum they are
    excess_quality = max(0, trans_qual - req_qual)

    # Penalty hyperparameter (e.g., lose 15% efficiency for every extra quality point)
    alpha = 0.15
    quality_efficiency = max(0, 1.0 - (alpha * excess_quality))

    # Final Weighted Score (60% Margin, 40% Conservation)
    score = (0.6 * margin) + (0.4 * quality_efficiency)
    return round(score, 4)

def generate_ml_training_data(n_samples, raw_historical_df, clients_df, translators_df, csp_solver):
    """
    Builds the Training Dataset. For every historical task, it extracts the features
    and calculates the Target Label (Y) for the XGBoost model.
    """
    print(f"--- GENERATING ML TRAINING DATA ({n_samples} TASKS) ---")
    training_data = []

    indices = np.random.choice(raw_historical_df.index, n_samples, replace=False)

    for idx in indices:
        row = raw_historical_df.loc[idx]

        # Build Requirements (Using your updated Asynchronous Logic)
        try:
            start_dt = pd.to_datetime(row['START'])
            end_dt = pd.to_datetime(row['END'])
            task_length = float(row.get('HOURS', row.get('TRANSLATOR_WORKING_TIME', 2.0)))
            window = max(1, (end_dt - start_dt).days + 1)

            task_reqs = csp_solver.build_client_requirements(
                company_name=str(row['MANUFACTURER']).strip(),
                clients_df=clients_df, historical_df=raw_historical_df,
                task_date=start_dt.strftime('%Y-%m-%d'), task_deadline=end_dt.strftime('%Y-%m-%d'),
                task_start_time=start_dt.strftime('%H:%M'), task_end_time=end_dt.strftime('%H:%M'),
                task_length_hours=task_length,
                language_pair=f"{str(row['SOURCE_LANG']).strip()}_{str(row['TARGET_LANG']).strip()}",
                task_type=str(row['TASK_TYPE']).strip()
            )
            if not task_reqs: continue
        except: continue

        # Get Eligible Candidates (The CSP is the Bouncer)
        candidates = csp_solver.get_eligible_translators(task_reqs)
        if candidates.empty: continue

        # For each candidate, extract Machine Learning Features
        for _, candidate in candidates.iterrows():
            # Interaction Features (The Gaps)
            budget = task_reqs.get('max_hourly_rate', 100)
            rate = candidate.get(task_reqs['language_pair'], budget)
            req_qual = task_reqs.get('min_quality', 0)
            trans_qual = candidate.get('AVERAGE_QUALITY', 0)

            features = {
                # Task Specs
                'req_quality': req_qual,
                'req_daily_capacity': task_length / window,
                'client_budget': budget,

                # Translator Specs
                'trans_quality': trans_qual,
                'trans_on_time': candidate.get('ON_TIME_SCORE', 0),
                'trans_rate': rate,
                'trans_daily_capacity': candidate.get('DAILY_CAPACITY', 0),

                # The "Magic" Interaction Features
                'quality_gap': trans_qual - req_qual,
                'margin_gap': budget - rate,

                # THE TARGET VARIABLE (Y)
                'TARGET_EFFICIENCY': calculate_efficiency_score(task_reqs, candidate)
            }
            training_data.append(features)

    df_train = pd.DataFrame(training_data)
    print(f"SUCCESS: Generated {len(df_train)} training rows.")
    return df_train

##Training

In [111]:
def train_xgboost_model(ml_dataset):
    """
    Trains the gradient boosting model to predict resource efficiency.
    """
    print("\n--- TRAINING XGBOOST MODEL ---")

    # Split into X (Features) and y (Target)
    X = ml_dataset.drop(columns=['TARGET_EFFICIENCY'])
    y = ml_dataset['TARGET_EFFICIENCY']

    # Train/Test Split (80% training, 20% validation)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize XGBoost Regressor
    model = xgb.XGBRegressor(
        objective='reg:squarederror',
        n_estimators=100,      # Number of trees
        learning_rate=0.1,     # Step size shrinkage
        max_depth=4,           # Depth of the tree (keeps it from overfitting)
        random_state=42
    )

    # Train the Model
    model.fit(
        X_train, y_train,
        eval_set=[(X_test, y_test)],
        verbose=10 # Prints progress every 10 steps
    )

    print("\n XGBoost Model successfully trained!")

    # Feature Importance (Shows what the AI cares about most)
    importance = pd.DataFrame({
        'Feature': X.columns,
        'Importance': model.feature_importances_
    }).sort_values(by='Importance', ascending=False)

    print("\n--- ML FEATURE IMPORTANCE ---")
    print(importance)

    return model

# Execute Training
# trained_ml_model = train_xgboost_model(ml_dataset)

##Ranker

In [112]:
def rank_candidates_ml(candidates_df, task_reqs, ml_model):
    """
    PRODUCTION RANKER: Uses the trained XGBoost model to instantly predict
    the 'Goldilocks' efficiency score for all eligible candidates.
    """
    if candidates_df.empty:
        return candidates_df

    df = candidates_df.copy()

    # Extract the exact same features we used in training
    budget = task_reqs.get('max_hourly_rate', 100)
    req_qual = task_reqs.get('min_quality', 0)
    window = task_reqs.get('window_days', 1)
    req_daily = task_reqs.get('task_length_hours', 8) / window

    pair = task_reqs.get('language_pair')

    # Construct the X matrix for predictions
    X_pred = pd.DataFrame({
        'req_quality': req_qual,
        'req_daily_capacity': req_daily,
        'client_budget': budget,
        'trans_quality': df['AVERAGE_QUALITY'],
        'trans_on_time': df['ON_TIME_SCORE'],
        'trans_rate': df[pair].fillna(budget),
        'trans_daily_capacity': df.get('DAILY_CAPACITY', 0),
        'quality_gap': df['AVERAGE_QUALITY'] - req_qual,
        'margin_gap': budget - df[pair].fillna(budget)
    })

    # Ask XGBoost to predict the Efficiency Score
    df['ML_PREDICTED_SCORE'] = ml_model.predict(X_pred)

    # Sort by the AI's prediction (Highest Score first)
    return df.sort_values(by='ML_PREDICTED_SCORE', ascending=False)


# =========================================================================================
# ML-ENHANCED EXECUTION BLOCK: TRAINING & LIVE DEPLOYMENT
# =========================================================================================
from IPython.display import display

# --- STEP 1: TRAIN THE MACHINE LEARNING MODEL ---
# In a real production system, you would only run this once a week or month.
# For this notebook, we will generate a dataset from 200 historical tasks.
print("\n" + "="*75)
print("  PHASE 0: TRAINING THE 'GOLDILOCKS' ML RANKER")
print("="*75)

# Generate the training data
# (If this takes too long, you can lower n_samples to 100)
ml_dataset = generate_ml_training_data(
    n_samples=200,
    raw_historical_df=df_dict['Data'],
    clients_df=df3,
    translators_df=translators_df,
    csp_solver=csp_solver
)

# Train the XGBoost Model
trained_ml_model = train_xgboost_model(ml_dataset)


# --- STEP 2: LIVE TASK DEPLOYMENT ---
print("\n\n" + "="*75)
print("  PHASE 1: LIVE TASK ASSIGNMENT (CSP + ML MATCHMAKING)")
print("="*75)

# Define a new, incoming task (Feel free to change these parameters!)
company_name = "ProdigySoft"
task_date = "2024-10-10"
task_deadline = "2024-10-12"
task_start_time = "09:00"
task_end_time = "17:00"
task_hours = 3.5       # Total effort required (PM inputs we cannot know)
language = "English_Spanish (Iberian)"

# Build Requirements using your Auto-Loader
task_requirements = csp_solver.build_client_requirements(
    company_name=company_name,
    clients_df=df3,
    historical_df=df_dict['Data'],
    task_date=task_date,
    task_deadline=task_deadline,
    task_start_time=task_start_time,
    task_end_time=task_end_time,
    task_length_hours=task_hours,
    language_pair=language,
    task_type="Translation"
)

if task_requirements:
    # THE BOUNCER (CSP): Filter out people who mathematically cannot do it
    final_candidates = csp_solver.get_translators_with_fallback(task_requirements)

    # Dynamic Split Strategy if no single person can do it
    import math
    if final_candidates.empty:
        optimal_splits = max(2, math.ceil(task_requirements.get('task_length_hours', 8.0) / 8.0))
        print(f"\n[SYSTEM] Attempting Multi-Day Split...")
        final_candidates = csp_solver.split_task_across_days(task_requirements)

        if final_candidates.empty:
            print(f"\n[SYSTEM] Attempting Team Assembly ({optimal_splits} translators)...")
            final_candidates = csp_solver.split_task_across_translators(task_requirements, num_translators=optimal_splits)

    # THE MATCHMAKER (ML Model): Rank the survivors for maximum efficiency
    if not final_candidates.empty:
        # Pass the survivors and the trained model into your new ML Ranker
        final_candidates = rank_candidates_ml(final_candidates, task_requirements, trained_ml_model)

        print(f"\n--- FOUND {len(final_candidates)} ELIGIBLE TRANSLATORS ---")
        print("Sorted by ML 'Goldilocks' Efficiency Prediction:")

        desired_columns = ['ML_PREDICTED_SCORE', 'NAME', language, 'DAILY_CAPACITY', 'AVERAGE_QUALITY', 'ON_TIME_SCORE']

        # Safe Filtering: Only print columns that actually exist
        final_cols = [col for col in desired_columns if col in final_candidates.columns]

        # Format the output for a clean, professional display
        display_df = final_candidates[final_cols].head(10).copy()
        if 'ML_PREDICTED_SCORE' in display_df.columns:
            display_df['ML_PREDICTED_SCORE'] = display_df['ML_PREDICTED_SCORE'].round(4)

        display(display_df)
    else:
        print("\n[SYSTEM FATAL ERROR] Impossible constraints. No eligible candidates found.")
        csp_solver.diagnose_bottleneck(task_requirements)

===========================================================================
  PHASE 0: TRAINING THE 'GOLDILOCKS' ML RANKER
===========================================================================
--- GENERATING ML TRAINING DATA (200 TASKS) ---

--- AUTO-LOADED PROFILE FOR: Voltcom Communications ---
>> Task Effort: 0.05 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: Clickforce ---
>> Task Effort: 0.16 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: Oasis Health ---
>> Task Effort: 0.00 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.87 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: InduNet Solutions ---
>> Task Effort: 0.08 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: LogicForge ---
>> Task Effort: 2.07 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: SunTech ---
>> Task Effort: 5.50 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TechPlanner ---
>> Task Effort: 0.52 hours of work
>> Project Window: 5 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 6.15 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: RoboIndus ---
>> Task Effort: 0.11 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: VidaCore Biotech ---
>> Task Effort: 6.31 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: Bold Ventures ---
>> Task Effort: 0.24 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: HealthyLife ---
>> Task Effort: 22.74 hours of work
>> Project Window: 6 days to deliver

--- AUTO-LOADED PROFILE FOR: VitalMed Equipments ---
>> Task Effort: 0.51 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.50 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: FutureX Enterprises ---
>> Task Effort: 0.62 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: Respiro Dynamics ---
>> Task Effort: 0.08 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: NexiGen ---
>> Task Effort: 5.01 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: Respiro Dynamics ---
>> Task Effort: 2.56 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: ProCall ---
>> Task Effort: 11.65 hours of work
>> Project Window: 6 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.11 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.50 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: MindSpark Media ---
>> Task Effort: 1.41 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.78 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroMech Industries ---
>> Task Effort: 0.50 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Voltwave ---
>> Task Effort: 0.16 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: SmartMed Innovations ---
>> Task Effort: 0.88 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.12 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Agrigenius ---
>> Task Effort: 0.97 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: StarLink ---
>> Task Effort: 0.18 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.06 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.20 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: MetalWorks ---
>> Task Effort: 4.89 hours of work
>> Project Window: 6 days to deliver

--- AUTO-LOADED PROFILE FOR: NanoWorks Research Corp ---
>> Task Effort: 0.25 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 2.51 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.04 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: SoftConnect ---
>> Task Effort: 4.50 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Hyperion Robotics ---
>> Task Effort: 0.66 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: InduNet Solutions ---
>> Task Effort: 0.17 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.15 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: SoftFactory ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Techmax Industries ---
>> Task Effort: 0.14 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: IntraIndustries ---
>> Task Effort: 0.13 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.05 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.08 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 1.90 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.02 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: HealthyLife ---
>> Task Effort: 0.70 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Agronome ---
>> Task Effort: 0.04 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: RoboIndus ---
>> Task Effort: 3.24 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.03 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.38 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.13 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: PixelWave ---
>> Task Effort: 0.50 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.09 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 1.12 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: AquaFoam Solutions ---
>> Task Effort: 2.95 hours of work
>> Project Window: 5 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.11 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AutoGenius ---
>> Task Effort: 0.08 hours of work
>> Project Window: 3 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.32 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: EquipNet ---
>> Task Effort: 0.21 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Nexa Materials ---
>> Task Effort: 0.44 hours of work
>> Project Window: 6 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Engineering ---
>> Task Effort: 6.80 hours of work
>> Project Window: 30 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.04 hours of work
>> Project Window: 3 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.50 hours of work
>> Project Window: 5 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.02 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: KineticWorks ---
>> Task Effort: 0.08 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.02 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.02 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.04 hours of work
>> Project Window: 6 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 1.40 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: GenomicSolutions ---
>> Task Effort: 0.60 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.02 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.80 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Flux Fuel ---
>> Task Effort: 0.00 hours of work
>> Project Window: 12 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.08 hours of work
>> Project Window: 3 days to deliver

--- AUTO-LOADED PROFILE FOR: Futurize ---
>> Task Effort: 0.88 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: Mercury Rail ---
>> Task Effort: 4.12 hours of work
>> Project Window: 5 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 1.58 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 2.02 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 1.38 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.36 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AlphaTech Industrial Services ---
>> Task Effort: 0.25 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: VirtuFactory ---
>> Task Effort: 0.18 hours of work
>> Project Window: 3 days to deliver

--- AUTO-LOADED PROFILE FOR: Global Trading Solutions ---
>> Task Effort: 0.06 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Mechanicore ---
>> Task Effort: 2.07 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.13 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: InnoSoft ---
>> Task Effort: 5.34 hours of work
>> Project Window: 3 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.25 hours of work
>> Project Window: 5 days to deliver

--- AUTO-LOADED PROFILE FOR: TechTrak ---
>> Task Effort: 4.00 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: Bold Ventures ---
>> Task Effort: 0.06 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.05 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 6 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.19 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.01 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 7 days to deliver

--- AUTO-LOADED PROFILE FOR: Penta Dynamics ---
>> Task Effort: 0.22 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.32 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: MegaForge ---
>> Task Effort: 0.78 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 26.87 hours of work
>> Project Window: 12 days to deliver

--- AUTO-LOADED PROFILE FOR: SysTrack ---
>> Task Effort: 2.72 hours of work
>> Project Window: 6 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.53 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Infusion Dynamics ---
>> Task Effort: 0.39 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.06 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 1.06 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 2.34 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: Workhorse Industries ---
>> Task Effort: 0.10 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: MindSpark Media ---
>> Task Effort: 0.40 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 1.34 hours of work
>> Project Window: 3 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.18 hours of work
>> Project Window: 5 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.07 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: HealthyLife ---
>> Task Effort: 0.08 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.01 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: SteelToe Footwear ---
>> Task Effort: 0.05 hours of work
>> Project Window: 3 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.29 hours of work
>> Project Window: 12 days to deliver

--- AUTO-LOADED PROFILE FOR: ConstructoTruck Industries ---
>> Task Effort: 7.32 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.57 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: MotorForge ---
>> Task Effort: 0.21 hours of work
>> Project Window: 5 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 1.35 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: Utopia Industrial ---
>> Task Effort: 10.00 hours of work
>> Project Window: 8 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.78 hours of work
>> Project Window: 7 days to deliver

--- AUTO-LOADED PROFILE FOR: Evergreen House ---
>> Task Effort: 1.77 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: ProdigyTech ---
>> Task Effort: 0.26 hours of work
>> Project Window: 11 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.17 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.13 hours of work
>> Project Window: 6 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.70 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Titan Heavy Industries ---
>> Task Effort: 2.50 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.02 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: CarePro Technologies ---
>> Task Effort: 0.17 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: NexisOne ---
>> Task Effort: 0.90 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Prodigy Manufacturing ---
>> Task Effort: 0.23 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 9.15 hours of work
>> Project Window: 5 days to deliver

--- AUTO-LOADED PROFILE FOR: QuantumLogic ---
>> Task Effort: 5.61 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.03 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 1.00 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.16 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.26 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: InterActive Concepts ---
>> Task Effort: 0.04 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.75 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: IndustrialFirst National Bank ---
>> Task Effort: 4.53 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.50 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 1.91 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: SunTech ---
>> Task Effort: 0.10 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.08 hours of work
>> Project Window: 4 days to deliver

--- AUTO-LOADED PROFILE FOR: FutureX Enterprises ---
>> Task Effort: 0.50 hours of work
>> Project Window: 28 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.02 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.80 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.17 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.13 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: InduNet Solutions ---
>> Task Effort: 0.01 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.05 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.49 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: Alliance Industrial ---
>> Task Effort: 0.07 hours of work
>> Project Window: 2 days to deliver

--- AUTO-LOADED PROFILE FOR: NexiGen ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: Legacy Industrial and Development Group ---
>> Task Effort: 0.09 hours of work
>> Project Window: 1 days to deliver

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.02 hours of work
>> Project Window: 1 days to deliver


,ML_PREDICTED_SCORE,NAME,English_Spanish (Iberian),DAILY_CAPACITY,AVERAGE_QUALITY,ON_TIME_SCORE
459,0.8286,Gregorio Monica,13.0,10.0,7.523535,0.983670
268,0.8267,Christopher,13.0,10.0,7.582278,0.784810
507,0.8092,Ines Aldana,14.0,10.0,7.628931,0.968553
712,0.8067,Maria Teresa,14.0,10.0,7.640000,0.973333
880,0.8033,Rufo,13.0,10.0,7.925417,0.966634
438,0.7925,Gaizka,13.0,10.0,8.150000,0.857143
344,0.7925,Eduardo,13.0,10.0,8.136054,0.770975
892,0.7912,Samuel,14.0,10.0,7.913043,0.923913
591,0.7904,Juan Rafael,15.0,10.0,7.610169,0.831093
157,0.7904,Armando,15.0,10.0,7.619233,0.951267

##Comparison

In [113]:
import numpy as np
import pandas as pd
from IPython.display import display

def generate_ml_audit_comparison(actual_name, ai_top_row, task_reqs, translators_df):
    """
    Creates a visual side-by-side comparison showing WHY the AI's choice
    is mathematically more efficient than the human's choice.
    """
    actual_row = translators_df[translators_df['NAME'] == actual_name]
    if actual_row.empty:
        return pd.DataFrame({"Error": [f"Translator '{actual_name}' not found"]})
    actual_row = actual_row.iloc[0]

    pair = task_reqs.get('language_pair')
    budget = task_reqs.get('max_hourly_rate', 100)
    req_qual = task_reqs.get('min_quality', 0)

    # Calculate Ground Truth Efficiency Scores for both
    human_efficiency = calculate_efficiency_score(task_reqs, actual_row)
    ai_efficiency = calculate_efficiency_score(task_reqs, ai_top_row)

    comparison_data = {
        "Metric": [
            "Hourly Rate (Cost)",
            "Profit Margin Gap",
            "Quality Score",
            "Quality Over-Specification",
            "Goldilocks Efficiency Score"
        ],
        "Task Requirement": [
            f"Budget: ${budget}",
            "Maximize",
            f"Minimum: {req_qual}",
            "Minimize Extra Quality",
            "Target: 1.00"
        ],
        "Human Choice (Reality)": [
            f"${actual_row.get(pair, 0)}",
            f"${max(0, budget - actual_row.get(pair, 0))}/hr",
            actual_row.get('AVERAGE_QUALITY', 'N/A'),
            f"+{max(0, actual_row.get('AVERAGE_QUALITY', 0) - req_qual):.2f} pts wasted",
            f"{human_efficiency:.2f}"
        ],
        "AI #1 Pick (ML Model)": [
            f"${ai_top_row.get(pair, 0)}",
            f"${max(0, budget - ai_top_row.get(pair, 0))}/hr",
            ai_top_row.get('AVERAGE_QUALITY', 'N/A'),
            f"+{max(0, ai_top_row.get('AVERAGE_QUALITY', 0) - req_qual):.2f} pts wasted",
            f"{ai_efficiency:.2f}"
        ]
    }

    comp_df = pd.DataFrame(comparison_data)

    return comp_df.style.set_caption(f"ML AUDIT: {actual_name.upper()} (Human) vs. {ai_top_row['NAME'].upper()} (AI)")\
                        .set_properties(**{'border': '1px solid black', 'text-align': 'center'})\
                        .set_properties(subset=['AI #1 Pick (ML Model)'], **{'background-color': '#e6ffe6', 'font-weight': 'bold'})\
                        .set_properties(subset=['Human Choice (Reality)'], **{'background-color': '#ffe6e6'})

def run_ml_performance_test(n_samples, raw_historical_df, clients_df, translators_df, csp_solver, ml_model):
    """
    Tests historical tasks to see how much more efficient the ML model is compared to human PMs.
    """
    print(f"--- STARTING ML OPTIMALITY TEST ({n_samples} TASKS) ---")

    stats = {
        "valid_tasks": 0,
        "human_avg_efficiency": 0.0,
        "ai_avg_efficiency": 0.0,
        "human_total_cost": 0.0,
        "ai_total_cost": 0.0,
        "ai_better_count": 0
    }

    indices = np.random.choice(raw_historical_df.index, n_samples, replace=False)
    audit_examples = []

    for idx in indices:
        row = raw_historical_df.loc[idx]
        actual_name = str(row['TRANSLATOR']).strip()

        try:
            start_dt, end_dt = pd.to_datetime(row['START']), pd.to_datetime(row['END'])
            task_length = float(row.get('HOURS', row.get('TRANSLATOR_WORKING_TIME', 2.0)))

            task_reqs = csp_solver.build_client_requirements(
                company_name=str(row['MANUFACTURER']).strip(),
                clients_df=clients_df, historical_df=raw_historical_df,
                task_date=start_dt.strftime('%Y-%m-%d'), task_deadline=end_dt.strftime('%Y-%m-%d'),
                task_start_time=start_dt.strftime('%H:%M'), task_end_time=end_dt.strftime('%H:%M'),
                task_length_hours=task_length,
                language_pair=f"{str(row['SOURCE_LANG']).strip()}_{str(row['TARGET_LANG']).strip()}",
                task_type=str(row['TASK_TYPE']).strip()
            )
            if not task_reqs: continue
        except: continue

        # Run CSP
        candidates = csp_solver.get_translators_with_fallback(task_reqs)
        if candidates.empty: continue # Skip if task is completely impossible

        # Get actual human data
        human_row = translators_df[translators_df['NAME'] == actual_name]
        if human_row.empty: continue
        human_row = human_row.iloc[0]

        # Rank with ML
        ranked_candidates = rank_candidates_ml(candidates, task_reqs, ml_model)
        ai_top_choice = ranked_candidates.iloc[0]

        # Calculate Ground Truth Efficiency
        human_score = calculate_efficiency_score(task_reqs, human_row)
        ai_score = calculate_efficiency_score(task_reqs, ai_top_choice)

        # Calculate Costs
        pair = task_reqs['language_pair']
        human_cost = human_row.get(pair, task_reqs.get('max_hourly_rate', 0)) * task_length
        ai_cost = ai_top_choice.get(pair, task_reqs.get('max_hourly_rate', 0)) * task_length

        # Log Stats
        stats["valid_tasks"] += 1
        stats["human_avg_efficiency"] += human_score
        stats["ai_avg_efficiency"] += ai_score
        stats["human_total_cost"] += human_cost
        stats["ai_total_cost"] += ai_cost

        if ai_score > human_score:
            stats["ai_better_count"] += 1
            # Save the row index so we can audit it later
            audit_examples.append((idx, actual_name, ai_top_choice, task_reqs))

    # Finalize Averages
    if stats["valid_tasks"] > 0:
        stats["human_avg_efficiency"] /= stats["valid_tasks"]
        stats["ai_avg_efficiency"] /= stats["valid_tasks"]

    return stats, audit_examples

# Run the test on 200 historical tasks
ml_stats, audit_list = run_ml_performance_test(
    n_samples=200,
    raw_historical_df=df_dict['Data'],
    clients_df=df3,
    translators_df=translators_df,
    csp_solver=csp_solver,
    ml_model=trained_ml_model # Pass the model you trained in the previous step
)

# Print the Dashboard
print("\n" + "="*70)
print("             MACHINE LEARNING ROI DASHBOARD")
print("="*70)
print(f"Valid Tasks Analyzed: {ml_stats['valid_tasks']}")
print("-" * 70)
print(f"Human Average Efficiency: {ml_stats['human_avg_efficiency']:.2f} / 1.00")
print(f"AI Average Efficiency:    {ml_stats['ai_avg_efficiency']:.2f} / 1.00")
print(f"AI Outperformed Human:    {ml_stats['ai_better_count']} times ({(ml_stats['ai_better_count']/ml_stats['valid_tasks'])*100:.1f}%)")
print("-" * 70)
print(f"Total Cost (Human PMs):   ${ml_stats['human_total_cost']:,.2f}")
print(f"Total Cost (AI Model):    ${ml_stats['ai_total_cost']:,.2f}")

savings = ml_stats['human_total_cost'] - ml_stats['ai_total_cost']
print(f"\n>> PROJECTED SAVINGS: ${savings:,.2f} on just {ml_stats['valid_tasks']} tasks!")
print("="*70)

# If the AI found a better choice, display the very first audit table as an example
if audit_list:
    example_idx, human_name, ai_choice, reqs = audit_list[0]
    print(f"\n[EXAMPLE AUDIT FOR ROW #{example_idx}]")
    display(generate_ml_audit_comparison(human_name, ai_choice, reqs, translators_df))

--- STARTING ML OPTIMALITY TEST (200 TASKS) ---

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.73 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 75 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.16 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: MotorForge ---
>> Task Effort: 0.11 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 130 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 9.04 hours of work
>> Project Window: 19 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 11 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.05 hours of work
>> Project Window: 7 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 75 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 11 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.17 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 75 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.56 hours of work
>> Project Window: 5 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 121 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.19 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 8 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AlphaTech Industrial Services ---
>> Task Effort: 0.17 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 245 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NextGen Engineering ---
>> Task Effort: 0.42 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 86 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 245 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: SmartMed Innovations ---
>> Task Effort: 0.08 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 92 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.00 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 8 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: InduNet Solutions ---
>> Task Effort: 0.17 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 10 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: PureEnergy Industries ---
>> Task Effort: 0.86 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
COMPROMISE SUCCESS: Found 1 generalists in the Industry Group.

--- AUTO-LOADED PROFILE FOR: DataHive ---
>> Task Effort: 1.01 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: SmartMed Innovations ---
>> Task Effort: 0.61 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 86 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 1.90 hours of work
>> Project Window: 5 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (DEADLINE) ---
>> Wildcard Triggered: Relaxed On-Time score to 0 and allowed 30% schedule shift
FAILED: Flexing the DEADLINE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Bluewave Semiconductors ---
>> Task Effort: 2.54 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 35 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.07 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 257 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: MegaForge ---
>> Task Effort: 2.50 hours of work
>> Project Window: 31 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 100 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 1.47 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 121 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.77 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 10 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 3.19 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (PRICE) ---
>> Wildcard Triggered: Increased budget threshold by 25% to $31.25
FAILED: Flexing the PRICE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.04 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 119 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: InspireWorks ---
>> Task Effort: 2.00 hours of work
>> Project Window: 5 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 201 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.50 hours of work
>> Project Window: 6 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 257 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.53 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 75 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.14 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 4 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 257 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: MindSpark Media ---
>> Task Effort: 1.40 hours of work
>> Project Window: 6 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 7 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.28 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Automatek ---
>> Task Effort: 14.73 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 38 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Zenith Engineering ---
>> Task Effort: 42.51 hours of work
>> Project Window: 17 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 2 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.01 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 75 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: Clickforce ---
>> Task Effort: 0.00 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 28 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: BioSolutions ---
>> Task Effort: 0.03 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 63 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 1.50 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 7 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: FrontierTech ---
>> Task Effort: 0.59 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 13 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NetBridge ---
>> Task Effort: 0.36 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 52 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.02 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 245 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: HealthyLife ---
>> Task Effort: 0.92 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 1 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: OmniDyne Dynamics ---
>> Task Effort: 0.21 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 80 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.50 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 8 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.12 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 72 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.25 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (PRICE) ---
>> Wildcard Triggered: Increased budget threshold by 25% to $31.25
FAILED: Flexing the PRICE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- AUTO-LOADED PROFILE FOR: Meridian Industrial ---
>> Task Effort: 1.79 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 14 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NextGen Industries ---
>> Task Effort: 0.01 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 3 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NexisOne ---
>> Task Effort: 0.18 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 45 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 2.95 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (PRICE) ---
>> Wildcard Triggered: Increased budget threshold by 25% to $31.25
FAILED: Flexing the PRICE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- AUTO-LOADED PROFILE FOR: Bold Ventures ---
>> Task Effort: 0.50 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 4 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.28 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 75 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: LifeGuard Equipments ---
>> Task Effort: 0.33 hours of work
>> Project Window: 11 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 225 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: MindSpark Media ---
>> Task Effort: 0.17 hours of work
>> Project Window: 6 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 6 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: VidaCore Biotech ---
>> Task Effort: 0.72 hours of work
>> Project Window: 5 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 40 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroMed ---
>> Task Effort: 1.58 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
FAILED: No Sub-Industry specialists found. Initiating Fallback...

--- ATTEMPT 2: Relaxing to Mid-Level Industry ---
FAILED: Mid-level Industry search didn't yield enough translators.

--- ATTEMPT 3: Relaxing to Broad Industry Group ---
FAILED: Broad Industry Group search failed.

--- ATTEMPT 4: Targeted Wildcard Relaxation (PRICE) ---
>> Wildcard Triggered: Increased budget threshold by 25% to $43.75
FAILED: Flexing the PRICE was not enough to find a candidate.

CRITICAL FAILURE: Maximum global relaxation reached. No translators available.

--- AUTO-LOADED PROFILE FOR: Infusion Dynamics ---
>> Task Effort: 12.87 hours of work
>> Project Window: 11 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 159 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.48 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 119 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: NexiSphere ---
>> Task Effort: 1.50 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 158 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: SteelToe Footwear ---
>> Task Effort: 2.56 hours of work
>> Project Window: 3 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 2 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: SunTech ---
>> Task Effort: 2.58 hours of work
>> Project Window: 31 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 20 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: InduNet Solutions ---
>> Task Effort: 0.03 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 11 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.08 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 2 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: TrueConnect ---
>> Task Effort: 0.08 hours of work
>> Project Window: 6 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 257 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.00 hours of work
>> Project Window: 1 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 1 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: VidaCore Biotech ---
>> Task Effort: 0.11 hours of work
>> Project Window: 4 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 39 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AeroSysTech ---
>> Task Effort: 0.25 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---
SUCCESS: Found 1 specialists matching Sub-Industry.

--- AUTO-LOADED PROFILE FOR: AccuVision ---
>> Task Effort: 2.53 hours of work
>> Project Window: 2 days to deliver

--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---