In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# DATA CLEANING

In [13]:
import pandas as pd
import numpy as np

file_path = "/content/drive/MyDrive/PROJECT SYNTHESIS I/260223_GrauIAI_data_mock.xlsx"    #with this we don't have to upload the data every time
df_dict = pd.read_excel(file_path, sheet_name=None)   #this creates a dictionary for our data where each key corresponds to a datasheet

df_dict.keys()

dict_keys(['Data', 'Schedules', 'Clients', 'TranslatorsCost+Pairs'])

In [14]:
#let's define a variable for each individual datasheet
df1 = df_dict['Data']
df2 = df_dict['Schedules']
df3 = df_dict['Clients']
df4 = df_dict['TranslatorsCost+Pairs']

df1.head()

,PROJECT_ID,PM,TASK_ID,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,TRANSLATOR,ASSIGNED,...,CLOSE,HOURS,HOURLY_RATE,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_SECTOR,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY
0,212331,PMT,10048285,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,Victor,2013-10-31 13:14:35,...,2013-10-31 13:18:34,0.00,13,0.00,5,SunTech,Information Technology,Technology Hardware & Equipment,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals"
1,211096,PMT,10048285,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,Severino,2012-10-26 17:25:26,...,2012-11-30 13:38:12,3.10,17,52.70,8,NexisOne,Technology Hardware,Technology,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals"
2,214198,KMT,10048285,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),Jeronimo,2015-09-09 17:31:52,...,2015-09-10 17:33:07,1.50,11,16.50,9,HealthyLife,Health Care,Health Care Providers,Health Care Facilities,Long-Term Care Facilities
3,213494,KMT,10048285,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),Estela,2014-11-26 16:34:23,...,2014-11-26 17:51:48,0.25,17,4.25,7,Coastal Cottage,Consumer Discretionary,Consumer Services,"Hotels, Restaurants & Leisure","Hotels, Resorts & Cruise Lines"
4,212331,PMT,10048286,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),Maria Alexandra,2013-10-31 13:14:35,...,2013-10-31 13:18:08,0.00,20,0.00,7,SunTech,Information Technology,Technology Hardware & Equipment,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals"

In [15]:
#we get rid of the columns we are not interested in
df1 = df1.drop(columns=['PROJECT_ID', 'PM', 'TASK_ID', "ASSIGNED", "RECEIVED", "CLOSE", "HOURS", "HOURLY_RATE","MANUFACTURER_SECTOR", "MANUFACTURER_INDUSTRY_GROUP",
                        "MANUFACTURER_INDUSTRY", "MANUFACTURER_SUBINDUSTRY"])

In [16]:
df1.head()

,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,TRANSLATOR,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER
0,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,Victor,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.00,5,SunTech
1,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,Severino,2012-10-26 17:25:41,2012-10-30 13:55:47,2012-11-30 12:57:37,52.70,8,NexisOne
2,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),Jeronimo,2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife
3,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),Estela,2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage
4,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),Maria Alexandra,2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.00,7,SunTech

In [17]:
#we put the "TRANSLATOR" column in first position just porque sino me da toc
cols = ['TRANSLATOR'] + [c for c in df1.columns if c != 'TRANSLATOR']
df1 = df1[cols]

df1.head()

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER
0,Victor,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.00,5,SunTech
1,Severino,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,2012-10-26 17:25:41,2012-10-30 13:55:47,2012-11-30 12:57:37,52.70,8,NexisOne
2,Jeronimo,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife
3,Estela,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage
4,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.00,7,SunTech

In [18]:
#this creates a new column corresponding to the task EXPECTED length (END-START) in hours
df1['START'] = pd.to_datetime(df1['START'])
df1['END'] = pd.to_datetime(df1['END'])

df1['TASK_LENGTH'] = (df1['END'] - df1['START']).dt.total_seconds() / 3600

#this creates a new column corresponding to the amount of hours the translator spent working on the task (paid work), (DELIVERED-WORKING)
df1['WORKING'] = pd.to_datetime(df1['WORKING'])
df1['DELIVERED'] = pd.to_datetime(df1['DELIVERED'])

df1['TRANSLATOR_WORKING_TIME'] = (df1['DELIVERED'] - df1['WORKING']).dt.total_seconds() / 3600

df1.head(10)

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER,TASK_LENGTH,TRANSLATOR_WORKING_TIME
0,Victor,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.00,5,SunTech,-18.216667,0.000556
1,Severino,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,2012-10-26 17:25:41,2012-10-30 13:55:47,2012-11-30 12:57:37,52.70,8,NexisOne,841.600000,743.030556
2,Jeronimo,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife,17.516667,23.109167
3,Estela,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage,4.900000,1.261111
4,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.00,7,SunTech,-18.216667,0.001389
5,Esteban Yoselin,2013-03-14 12:09:00,2013-03-31 19:00:00,Miscelaneous,English,Spanish (Iberian),2013-06-06 14:08:41,2013-06-06 14:08:44,2013-06-06 14:08:47,0.00,4,AeroSysTech,414.850000,0.000833
6,Felipe Aldana,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),2017-12-28 16:40:15,2017-12-29 08:39:39,2017-12-29 12:22:11,21.00,6,Zenith Tires & Engineering,22.583333,3.708889
7,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscelaneous,Catalan,Spanish (Global),2013-10-31 13:16:51,2013-10-31 13:16:54,2013-10-31 13:16:58,0.00,8,SunTech,-18.216667,0.001111
8,Ryan,2009-12-14 18:00:00,2009-12-19 19:00:00,Miscellaneous,Spanish (Iberian),English,2010-03-18 10:59:35,2010-03-20 16:34:08,2010-04-06 23:41:55,0.00,8,HealthyLife,121.000000,415.129722
9,Usula,2010-01-07 12:00:00,2010-01-07 18:00:00,ProofReading,English,Spanish (Iberian),2010-01-07 09:17:05,2010-01-07 13:10:51,2010-01-07 18:33:57,72.00,7,QuantumLogic,6.000000,5.385000

In [19]:
#we observe some inconsistencies. For example, that some task_length values are negative (shown below), some costs are 0, some TRANSLATOR_WORKING_TIME is
#too close to 0, or some source and target language being the same
df1[df1['TASK_LENGTH'] < 0]

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER,TASK_LENGTH,TRANSLATOR_WORKING_TIME
0,Victor,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.0,5,SunTech,-18.216667,0.000556
4,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.0,7,SunTech,-18.216667,0.001389
7,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscelaneous,Catalan,Spanish (Global),2013-10-31 13:16:51,2013-10-31 13:16:54,2013-10-31 13:16:58,0.0,8,SunTech,-18.216667,0.001111

In [22]:
#let's clean the data
df1 = df1[(df1['TASK_LENGTH'] > 0.01) & (df1['TRANSLATOR_WORKING_TIME'] > 0.01) & (df1['SOURCE_LANG'] != df1['TARGET_LANG']) & (df1['COST'] > 0)]

df1.head(10)

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER,TASK_LENGTH,TRANSLATOR_WORKING_TIME
1,Severino,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,2012-10-26 17:25:41,2012-10-30 13:55:47,2012-11-30 12:57:37,52.70,8,NexisOne,841.600000,743.030556
2,Jeronimo,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife,17.516667,23.109167
3,Estela,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage,4.900000,1.261111
6,Felipe Aldana,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),2017-12-28 16:40:15,2017-12-29 08:39:39,2017-12-29 12:22:11,21.00,6,Zenith Tires & Engineering,22.583333,3.708889
9,Usula,2010-01-07 12:00:00,2010-01-07 18:00:00,ProofReading,English,Spanish (Iberian),2010-01-07 09:17:05,2010-01-07 13:10:51,2010-01-07 18:33:57,72.00,7,QuantumLogic,6.000000,5.385000
10,Esteban Yoselin,2010-01-19 12:54:00,2010-01-21 15:00:00,ProofReading,English,Spanish (Iberian),2010-01-19 13:09:37,2010-01-20 13:00:58,2010-01-20 18:12:23,42.25,9,ZenithSoft,50.100000,5.190278
11,Almudena Fiamma,2009-12-31 12:04:00,2010-01-31 19:00:00,Miscellaneous,English,Spanish (Iberian),2010-01-04 12:54:36,2010-01-05 13:40:20,2010-01-31 12:18:37,45.00,7,Global Trading Solutions,750.933333,622.638056
12,Almudena Fiamma,2009-12-31 12:07:00,2010-01-31 19:00:00,Miscellaneous,English,Spanish (Iberian),2010-01-04 12:55:43,2010-01-17 19:00:09,2010-01-31 12:20:48,3.75,8,TruVision,750.883333,329.344167
13,Erico,2010-01-04 09:30:00,2010-01-04 16:00:00,Translation,English,Spanish (Iberian),2010-01-04 10:52:17,2010-01-04 15:06:05,2010-01-04 15:17:04,0.66,5,GenomicSolutions,6.500000,0.183056
14,Luis Felipe,2010-01-04 09:35:00,2010-01-05 12:00:00,ProofReading,English,Spanish (Iberian),2010-01-04 09:37:06,2010-01-04 10:11:55,2010-01-04 18:40:51,61.20,6,Global Trading Solutions,26.416667,8.482222

In [30]:
#finally let's create a new column to keep track of on-time/late deliveries
#there appears a warning due to pandas not knowing what it has to modifiy. If someone knows how to fix it do it please. Create a copy or whatever
df1['END'] = pd.to_datetime(df1['END'])
df1['DELIVERED'] = pd.to_datetime(df1['DELIVERED'])

df1['ON_TIME'] = (df1['END'] >= df1['DELIVERED']).astype(int)
df1.head()

/tmp/ipykernel_732/1179139526.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['END'] = pd.to_datetime(df1['END'])
/tmp/ipykernel_732/1179139526.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['DELIVERED'] = pd.to_datetime(df1['DELIVERED'])
/tmp/ipykernel_732/1179139526.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ON_TIME'] = (df1['END'] >= df1['DELIVERED']).astype(int)

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER,TASK_LENGTH,TRANSLATOR_WORKING_TIME,ON_TIME
1,Severino,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,2012-10-26 17:25:41,2012-10-30 13:55:47,2012-11-30 12:57:37,52.70,8,NexisOne,841.600000,743.030556,1
2,Jeronimo,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife,17.516667,23.109167,0
3,Estela,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage,4.900000,1.261111,0
6,Felipe Aldana,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),2017-12-28 16:40:15,2017-12-29 08:39:39,2017-12-29 12:22:11,21.00,6,Zenith Tires & Engineering,22.583333,3.708889,1
9,Usula,2010-01-07 12:00:00,2010-01-07 18:00:00,ProofReading,English,Spanish (Iberian),2010-01-07 09:17:05,2010-01-07 13:10:51,2010-01-07 18:33:57,72.00,7,QuantumLogic,6.000000,5.385000,0

# TRANSLATOR STATISTICS/INFORMATION DATASHEET

In [ ]:
#now, we'll use the data we have above to create a new datasheet with all the information we want for each translator

In [32]:
import pandas as pd

translators_df = pd.DataFrame()

In [43]:
#first we want to know the time availavility of each translator
cols = [c for c in df2.columns]
translators_df = df2[cols]

translators_df.head()

           NAME     START       END  MON  TUES  WED  THURS  FRI  SAT  SUN
0         Aaron  09:00:00  19:00:00    1     1    1      1    1    0    0
1         Abdon  10:00:00  20:00:00    1     1    1      1    1    1    1
2  Abdon Isaias  09:00:00  19:00:00    1     1    1      1    1    1    1
3    Abdon Luis  04:00:00  14:00:00    0     0    0      0    1    0    0
4    Abel Irene  07:00:00  17:00:00    0     0    0      1    0    0    0

In [44]:
#PROBLEM! before adding the source-target language information, let's check if all translators are in both df2 (which we used to create the column of trabnslators)
#and df4 (where the source-target language information is)
missing_in_df4 = set(df2['NAME']) - set(df4['TRANSLATOR'])
missing_in_df2 = set(df4['TRANSLATOR']) - set(df2['NAME'])

print("Missing in df4:", missing_in_df4)
print("Missing in df2:", missing_in_df2)

Missing in df4: {'Aitor', 'Amelie', 'Aldara', 'Alex', 'Alexandre', 'Ana Lilia', 'Alfonso Odon', 'Alfonso Leandro', 'Alphonse', 'Amelio Lazaro', 'Alexia Fernanda', 'Adalberto', 'Almudena Jorge', 'Adela Esteban', 'Aide Matias', 'Adam', 'Agueda', 'Ainhoa', 'Ana Gabriela', 'Akos', 'Amets', 'Addison', 'Alice', 'Alain', 'Amaro', 'Ana Flavia', 'Alejandria Leon', 'Akseli', 'Ana Barbara', 'Adelia', 'Ambrosia Marcelo', 'Ana Daniela', 'Almudena Dacio', 'Agostinho', 'Albina Adan', 'Alexandra', 'Amelio Laureano', 'Alipio Bernarda', 'Alexandru', 'Ana Pilar', 'Alvaro Borja', 'Amaru', 'Ana Clara', 'Amancio', 'Aide', 'Akira', 'Alba', 'Adrien', 'Ana Lucia', 'Amaiur Lucano', 'Ager', 'Alejandria Itzel', 'Adela', 'Alonso Dimas', 'Agathe', 'Aino', 'Alejo', 'Alejandro', 'Alessandro', 'Ambrosia Adon', 'Ambrosia', 'Agustina Greta', 'Alessio', 'Adan', 'Adele', 'Amaro Salma', 'Ana Marcela', 'Amelio Elias', 'Amalia', 'Alejo Esdras', 'Aline', 'Alfonso Felix', 'Alfredo', 'Alfonso', 'Ana Karen', 'Ana', 'Almudena Fiamma', 'Amelio Salvio', 'Ana Belen', 'Alfreda', 'Alexander', 'Agustina', 'Ana Jimena', 'Alban', 'Ana Laura', 'Adalberto Anatolio', 'Amadeo Eliseo', 'Aisha'}
Missing in df2: set()

In [ ]:
#it is normal that we're missing a lot of names in df4 (as we're currently using a small dataset)
#the important thing is that there are no missing names in df2

#now, I asked chatGPT this:
#"I want to do is to create new columns (or just one) for each translator in translators_df indicating which source-target language task
#they can manage. In the datasheet df4, many translators have multiple rows, one for each language pair, and each row has a different hourly_rate cost. How do I
#incorporate all that information in a single row for every translator in translators_df? Do I create a column for every possible language pair, do I create a single
#column which contains a dictionary for every translator where keys are language pairs and values are hourly_rate cost, or is it better to do another thing?"

#and it told me that for pandas, the best thing is to create a new column for each language pair, so that's what we're gonna do :D

In [45]:
df4['PAIR'] = df4['SOURCE_LANG'] + "_" + df4['TARGET_LANG']

pivot = df4.pivot_table(
    index='NAME',
    columns='PAIR',
    values='HOURLY_RATE',
    aggfunc='first')

pivot = pivot.reset_index()

translators_df = translators_df.merge(pivot, on='NAME', how='left')

translators_df.head()

KeyError: 'NAME'