In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# DATA CLEANING AND NEW FEATURES

In [ ]:
import pandas as pd
import numpy as np

file_path = "/content/drive/MyDrive/PROJECT SYNTHESIS I/260223_GrauIAI_data_mock.xlsx"    #with this we don't have to upload the data every time

df_dict = pd.read_excel(file_path, sheet_name=None)   #this creates a dictionary for our data where each key corresponds to a datasheet

df_dict.keys()

dict_keys(['Data', 'Schedules', 'Clients', 'TranslatorsCost+Pairs'])

In [ ]:
#lets define a variable for each individual datasheet
df1 = df_dict['Data']
df2 = df_dict['Schedules']
df3 = df_dict['Clients']
df4 = df_dict['TranslatorsCost+Pairs']

df1.head()

,PROJECT_ID,PM,TASK_ID,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,TRANSLATOR,ASSIGNED,...,CLOSE,HOURS,HOURLY_RATE,COST,QUALITY_EVALUATION,MANUFACTURER,MANUFACTURER_SECTOR,MANUFACTURER_INDUSTRY_GROUP,MANUFACTURER_INDUSTRY,MANUFACTURER_SUBINDUSTRY
0,216313,RMT,10048287,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),Felipe Aldana,2017-12-28 16:29:02,...,2017-12-29 12:29:35,1.50,14,21.00,6,Zenith Tires & Engineering,Consumer Staples,Tobacco,Tobacco,Tobacco
1,214198,KMT,10048285,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),Jeronimo,2015-09-09 17:31:52,...,2015-09-10 17:33:07,1.50,11,16.50,9,HealthyLife,Health Care,Health Care Providers,Health Care Facilities,Long-Term Care Facilities
2,213494,KMT,10048285,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),Estela,2014-11-26 16:34:23,...,2014-11-26 17:51:48,0.25,17,4.25,7,Coastal Cottage,Consumer Discretionary,Consumer Services,"Hotels, Restaurants & Leisure","Hotels, Resorts & Cruise Lines"
3,212331,PMT,10048285,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,Victor,2013-10-31 13:14:35,...,2013-10-31 13:18:34,0.00,13,0.00,5,SunTech,Information Technology,Technology Hardware & Equipment,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals"
4,212331,PMT,10048286,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),Maria Alexandra,2013-10-31 13:14:35,...,2013-10-31 13:18:08,0.00,20,0.00,7,SunTech,Information Technology,Technology Hardware & Equipment,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals"

In [ ]:
#we get rid of the columns we are not interested in
df1 = df1.drop(columns=['PROJECT_ID', 'PM', 'TASK_ID', "ASSIGNED", "RECEIVED", "CLOSE", "HOURS", "HOURLY_RATE", "MANUFACTURER_SECTOR"])

In [ ]:
df1.head()

,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,TRANSLATOR,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER
0,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),Felipe Aldana,2017-12-28 16:40:15,2017-12-29 08:39:39,2017-12-29 12:22:11,21.00,6,Zenith Tires & Engineering
1,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),Jeronimo,2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife
2,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),Estela,2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage
3,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,Victor,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.00,5,SunTech
4,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),Maria Alexandra,2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.00,7,SunTech

In [ ]:
#we put the "TRANSLATOR" column in first position
cols = ['TRANSLATOR'] + [c for c in df1.columns if c != 'TRANSLATOR']
df1 = df1[cols]

df1.head()

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER
0,Felipe Aldana,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),2017-12-28 16:40:15,2017-12-29 08:39:39,2017-12-29 12:22:11,21.00,6,Zenith Tires & Engineering
1,Jeronimo,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife
2,Estela,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage
3,Victor,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.00,5,SunTech
4,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.00,7,SunTech

In [ ]:
#this creates a new column corresponding to the task EXPECTED length (END-START) in hours
df1['START'] = pd.to_datetime(df1['START'], errors='coerce')
df1['END'] = pd.to_datetime(df1['END'], errors='coerce')

df1['TASK_LENGTH'] = (df1['END'] - df1['START']).dt.total_seconds() / 3600

#this creates a new column corresponding to the amount of hours the translator spent working on the task (paid work), (DELIVERED-WORKING)
df1['WORKING'] = pd.to_datetime(df1['WORKING'], errors='coerce')
df1['DELIVERED'] = pd.to_datetime(df1['DELIVERED'], errors='coerce')

df1['TRANSLATOR_WORKING_TIME'] = (df1['DELIVERED'] - df1['WORKING']).dt.total_seconds() / 3600

df1.head(10)

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER,TASK_LENGTH,TRANSLATOR_WORKING_TIME
0,Felipe Aldana,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),2017-12-28 16:40:15,2017-12-29 08:39:39,2017-12-29 12:22:11,21.00,6,Zenith Tires & Engineering,22.583333,3.708889
1,Jeronimo,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife,17.516667,23.109167
2,Estela,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage,4.900000,1.261111
3,Victor,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.00,5,SunTech,-18.216667,0.000556
4,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.00,7,SunTech,-18.216667,0.001389
5,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscelaneous,Catalan,Spanish (Global),2013-10-31 13:16:51,2013-10-31 13:16:54,2013-10-31 13:16:58,0.00,8,SunTech,-18.216667,0.001111
6,Esteban Yoselin,2013-03-14 12:09:00,2013-03-31 19:00:00,Miscelaneous,English,Spanish (Iberian),2013-06-06 14:08:41,2013-06-06 14:08:44,2013-06-06 14:08:47,0.00,4,AeroSysTech,414.850000,0.000833
7,Severino,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,2012-10-26 17:25:41,2012-10-30 13:55:47,2012-11-30 12:57:37,52.70,8,NexisOne,841.600000,743.030556
8,Esteban Yoselin,2010-01-19 12:54:00,2010-01-21 15:00:00,ProofReading,English,Spanish (Iberian),2010-01-19 13:09:37,2010-01-20 13:00:58,2010-01-20 18:12:23,42.25,9,ZenithSoft,50.100000,5.190278
9,Basileo,2010-01-12 10:00:00,2010-01-26 09:00:00,Translation,French,Spanish (Iberian),2010-01-11 16:15:50,2010-01-11 16:24:29,2010-01-26 08:01:48,821.80,9,EcoSolar,335.000000,351.621944

In [ ]:
#we observe some inconsistencies. For example, that some task_length values are negative (shown below), some costs are 0, some TRANSLATOR_WORKING_TIME is
#too close to 0, or some source and target language being the same
df1[df1['TASK_LENGTH'] < 0]

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER,TASK_LENGTH,TRANSLATOR_WORKING_TIME
3,Victor,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscellaneous,Catalan,Catalan,2013-10-31 13:18:25,2013-10-31 13:18:27,2013-10-31 13:18:29,0.0,5,SunTech,-18.216667,0.000556
4,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Management,Catalan,Spanish (Global),2013-10-31 13:17:56,2013-10-31 13:17:58,2013-10-31 13:18:03,0.0,7,SunTech,-18.216667,0.001389
5,Maria Alexandra,2013-11-01 13:13:00,2013-10-31 19:00:00,Miscelaneous,Catalan,Spanish (Global),2013-10-31 13:16:51,2013-10-31 13:16:54,2013-10-31 13:16:58,0.0,8,SunTech,-18.216667,0.001111

In [ ]:
#let's clean the data
df1 = df1[(df1['TASK_LENGTH'] > 0.01) & (df1['TRANSLATOR_WORKING_TIME'] > 0.01) & (df1['SOURCE_LANG'] != df1['TARGET_LANG']) & (df1['COST'] > 0)]

df1.head(10)

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER,TASK_LENGTH,TRANSLATOR_WORKING_TIME
0,Felipe Aldana,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),2017-12-28 16:40:15,2017-12-29 08:39:39,2017-12-29 12:22:11,21.00,6,Zenith Tires & Engineering,22.583333,3.708889
1,Jeronimo,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife,17.516667,23.109167
2,Estela,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage,4.900000,1.261111
7,Severino,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,2012-10-26 17:25:41,2012-10-30 13:55:47,2012-11-30 12:57:37,52.70,8,NexisOne,841.600000,743.030556
8,Esteban Yoselin,2010-01-19 12:54:00,2010-01-21 15:00:00,ProofReading,English,Spanish (Iberian),2010-01-19 13:09:37,2010-01-20 13:00:58,2010-01-20 18:12:23,42.25,9,ZenithSoft,50.100000,5.190278
9,Basileo,2010-01-12 10:00:00,2010-01-26 09:00:00,Translation,French,Spanish (Iberian),2010-01-11 16:15:50,2010-01-11 16:24:29,2010-01-26 08:01:48,821.80,9,EcoSolar,335.000000,351.621944
10,Juan Carlos,2010-01-12 09:00:00,2010-01-12 17:00:00,ProofReading,English,Spanish (Iberian),2010-01-12 09:12:59,2010-01-12 09:56:24,2010-01-12 17:39:40,66.30,8,FrontierTech,8.000000,7.721111
11,Erico,2010-01-11 10:00:00,2010-01-11 13:00:00,ProofReading,English,Spanish (Global),2010-01-11 10:06:26,2010-01-11 10:16:21,2010-01-11 11:56:11,12.76,7,SkyBridge Technologies,3.000000,1.663889
12,Marti,2010-01-11 09:00:00,2010-01-11 15:00:00,ProofReading,English,Spanish (Iberian),2010-01-11 09:25:54,2010-01-11 09:43:46,2010-01-11 14:29:49,44.33,8,HealthyLife,6.000000,4.767500
13,Esteban Yoselin,2010-01-11 09:00:00,2010-01-12 12:00:00,ProofReading,English,Spanish (Iberian),2010-01-08 09:23:51,2010-01-11 12:18:53,2010-01-12 09:50:17,37.96,6,Flux Fuel,27.000000,21.523333

In [ ]:
#finally let's create a new column to keep track of on-time/late deliveries
#there appears a warning due to pandas not knowing what it has to modifiy. If someone knows how to fix it do it please. Create a copy or whatever
df1['END'] = pd.to_datetime(df1['END'])
df1['DELIVERED'] = pd.to_datetime(df1['DELIVERED'])

df1['ON_TIME'] = (df1['END'] >= df1['DELIVERED']).astype(int)
df1.head()

,TRANSLATOR,START,END,TASK_TYPE,SOURCE_LANG,TARGET_LANG,READY,WORKING,DELIVERED,COST,QUALITY_EVALUATION,MANUFACTURER,TASK_LENGTH,TRANSLATOR_WORKING_TIME,ON_TIME
0,Felipe Aldana,2017-12-28 16:25:00,2017-12-29 15:00:00,Translation,English,Spanish (Iberian),2017-12-28 16:40:15,2017-12-29 08:39:39,2017-12-29 12:22:11,21.00,6,Zenith Tires & Engineering,22.583333,3.708889,1
1,Jeronimo,2015-09-09 17:29:00,2015-09-10 11:00:00,Engineering,English,Spanish (Iberian),2015-09-09 17:34:56,2015-09-09 17:35:48,2015-09-10 16:42:21,16.50,9,HealthyLife,17.516667,23.109167,0
2,Estela,2014-11-26 10:36:00,2014-11-26 15:30:00,Engineering,English,Portuguese (Brazil),2014-11-26 16:34:25,2014-11-26 16:34:27,2014-11-26 17:50:07,4.25,7,Coastal Cottage,4.900000,1.261111,0
7,Severino,2012-10-26 17:24:00,2012-11-30 19:00:00,Miscellaneous,English,Galician,2012-10-26 17:25:41,2012-10-30 13:55:47,2012-11-30 12:57:37,52.70,8,NexisOne,841.600000,743.030556,1
8,Esteban Yoselin,2010-01-19 12:54:00,2010-01-21 15:00:00,ProofReading,English,Spanish (Iberian),2010-01-19 13:09:37,2010-01-20 13:00:58,2010-01-20 18:12:23,42.25,9,ZenithSoft,50.100000,5.190278,1

# TRANSLATOR STATISTICS/INFORMATION DATASHEET

In [ ]:
#now, we'll use the data we have above to create a new datasheet with all the information we want for each translator

In [ ]:
import pandas as pd

translators_df = pd.DataFrame()

In [ ]:
#first we want to know the time availavility of each translator
cols = [c for c in df2.columns]
translators_df = df2[cols]

translators_df.head()

           NAME     START       END  MON  TUES  WED  THURS  FRI  SAT  SUN
0         Aaron  09:00:00  19:00:00    1     1    1      1    1    0    0
1         Abdon  10:00:00  20:00:00    1     1    1      1    1    1    1
2  Abdon Isaias  09:00:00  19:00:00    1     1    1      1    1    1    1
3    Abdon Luis  04:00:00  14:00:00    0     0    0      0    1    0    0
4    Abel Irene  07:00:00  17:00:00    0     0    0      1    0    0    0

In [ ]:
#PROBLEM! before adding the source-target language information, let's check if all translators are in both df2 (which we used to create the column of trabnslators)
#and df4 (where the source-target language information is)
missing_in_df4 = set(df2['NAME']) - set(df4['TRANSLATOR'])
missing_in_df2 = set(df4['TRANSLATOR']) - set(df2['NAME'])

print("Missing in df4:", missing_in_df4)
print("Missing in df2:", missing_in_df2)

Missing in df4: {'Akseli', 'Amaro Salma', 'Ana Daniela', 'Albina Adan', 'Alexandru', 'Ana Belen', 'Ambrosia', 'Alejo', 'Agathe', 'Adan', 'Ana Barbara', 'Agueda', 'Ana', 'Almudena Fiamma', 'Alexandra', 'Amancio', 'Alfonso', 'Alain', 'Alvaro Borja', 'Ana Karen', 'Alexander', 'Alban', 'Agostinho', 'Alfonso Odon', 'Alejandro', 'Amalia', 'Alexandre', 'Alfreda', 'Akos', 'Ana Lucia', 'Ager', 'Aide', 'Alba', 'Alice', 'Adam', 'Amaiur Lucano', 'Ana Clara', 'Aide Matias', 'Ana Flavia', 'Alfredo', 'Alphonse', 'Aisha', 'Alessandro', 'Aldara', 'Amelio Lazaro', 'Amelio Elias', 'Alejandria Leon', 'Alexia Fernanda', 'Agustina Greta', 'Alessio', 'Amelio Laureano', 'Ana Marcela', 'Aitor', 'Adelia', 'Amaro', 'Adele', 'Ambrosia Marcelo', 'Alejo Esdras', 'Ana Lilia', 'Amets', 'Alejandria Itzel', 'Ana Pilar', 'Addison', 'Ana Laura', 'Ana Gabriela', 'Amaru', 'Alfonso Leandro', 'Amadeo Eliseo', 'Ainhoa', 'Adela', 'Ambrosia Adon', 'Amelie', 'Adrien', 'Aline', 'Agustina', 'Alex', 'Aino', 'Almudena Jorge', 'Adalberto', 'Alfonso Felix', 'Alonso Dimas', 'Adalberto Anatolio', 'Ana Jimena', 'Adela Esteban', 'Alipio Bernarda', 'Amelio Salvio', 'Akira', 'Almudena Dacio'}
Missing in df2: set()

In [ ]:
#it is normal that we're missing a lot of names in df4 (as we're currently using a small dataset)
#the important thing is that there are no missing names in df2

#for pandas, the best thing is to create a new column for each language pair, so that's what we're gonna do :D

In [ ]:
# 1. Create language pair column in df4
df4['PAIR'] = df4['SOURCE_LANG'] + "_" + df4['TARGET_LANG']

# 2. Pivot df4 → one row per translator, one column per language pair
pivot = df4.pivot_table(
    index='TRANSLATOR',
    columns='PAIR',
    values='HOURLY_RATE',
    aggfunc='first'
).reset_index()

# 3. Merge into translators_df (NAME ↔ TRANSLATOR)
translators_df = translators_df.merge(
    pivot,
    left_on='NAME',
    right_on='TRANSLATOR',
    how='left'
)


translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Spanish (Iberian)_English (US),Spanish (Iberian)_French,Spanish (Iberian)_German,Spanish (Iberian)_Italian,Spanish (Iberian)_Norwegian,Spanish (Iberian)_Portuguese (Iberian),Spanish (Iberian)_Russian,Spanish (Iberian)_Spanish (Iberian),Spanish (Iberian)_Valencian,Spanish (LA)_Spanish (Iberian)
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdon Luis,04:00:00,14:00:00,0,0,0,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abel Irene,07:00:00,17:00:00,0,0,0,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#We chack that it's working
translators_df.loc[translators_df['NAME'] == 'Aaron', 'English_Spanish (Iberian)'].values[0]

np.float64(19.0)

In [ ]:
#this creates a column with the average quality of each translator
#the minimum of this column should be 0 and the maximum 10. If not data in df1 was found for the translator, the value is NaN
translators_df = translators_df.merge(
    df1.groupby('TRANSLATOR')['QUALITY_EVALUATION']
        .mean()
        .reset_index()
        .rename(columns={
            'TRANSLATOR': 'NAME',
            'QUALITY_EVALUATION': 'AVERAGE_QUALITY'
        }),
    on='NAME',
    how='left'
)

translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Spanish (Iberian)_French,Spanish (Iberian)_German,Spanish (Iberian)_Italian,Spanish (Iberian)_Norwegian,Spanish (Iberian)_Portuguese (Iberian),Spanish (Iberian)_Russian,Spanish (Iberian)_Spanish (Iberian),Spanish (Iberian)_Valencian,Spanish (LA)_Spanish (Iberian),AVERAGE_QUALITY
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.75
3,Abdon Luis,04:00:00,14:00:00,0,0,0,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abel Irene,07:00:00,17:00:00,0,0,0,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#this creates a column with the ON_TIME_SCORE of each translator
#the minimum of this column should be 0 and the maximum 1. If not data in df1 was found for the translator, the value is NaN
translators_df = translators_df.merge(
    df1.groupby('TRANSLATOR')['ON_TIME']
        .mean()
        .reset_index()
        .rename(columns={
            'TRANSLATOR': 'NAME',
            'ON_TIME': 'ON_TIME_SCORE'
        }),
    on='NAME',
    how='left'
)

translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Spanish (Iberian)_German,Spanish (Iberian)_Italian,Spanish (Iberian)_Norwegian,Spanish (Iberian)_Portuguese (Iberian),Spanish (Iberian)_Russian,Spanish (Iberian)_Spanish (Iberian),Spanish (Iberian)_Valencian,Spanish (LA)_Spanish (Iberian),AVERAGE_QUALITY,ON_TIME_SCORE
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.75,1.0
3,Abdon Luis,04:00:00,14:00:00,0,0,0,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abel Irene,07:00:00,17:00:00,0,0,0,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#this creates a column for the task experience of each translator (one column per task type)

df1['TASK_TYPE'] = df1['TASK_TYPE'] + "_experience"

#Pivot df1 → one row per translator, one column per task type
pivot = df1.pivot_table(
    index='TRANSLATOR',
    columns='TASK_TYPE',
    values='TRANSLATOR_WORKING_TIME',
    aggfunc='sum'
).reset_index()

# Rename TRANSLATOR → NAME BEFORE merging
pivot = pivot.rename(columns={'TRANSLATOR': 'NAME'})


# Merge cleanly (no _x / _y columns)
translators_df = translators_df.merge(
    pivot,
    on='NAME',
    how='left'
)

# Replace NaN with 0 ONLY in experience columns
exp_cols = [c for c in translators_df.columns if c.endswith('_experience')]
translators_df[exp_cols] = translators_df[exp_cols].fillna(0)

translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Spanish (Iberian)_Russian,Spanish (Iberian)_Spanish (Iberian),Spanish (Iberian)_Valencian,Spanish (LA)_Spanish (Iberian),AVERAGE_QUALITY,ON_TIME_SCORE,Engineering_experience,Miscellaneous_experience,ProofReading_experience,Translation_experience
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.000000
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.000000
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,7.75,1.0,0.0,535.076667,0.0,407.191111
3,Abdon Luis,04:00:00,14:00:00,0,0,0,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.000000
4,Abel Irene,07:00:00,17:00:00,0,0,0,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.000000

In [ ]:
#this create a column called TIME_TO_START, whose value will be calculated later when the task starting date is provided. The value of the column will be in how much time
# the translator will be available, calculated by comparing the task starting date and the translator schedules

translators_df["TIME_TO_START"] = np.nan

translators_df.head()

,NAME,START,END,MON,TUES,WED,THURS,FRI,SAT,SUN,...,Spanish (Iberian)_Spanish (Iberian),Spanish (Iberian)_Valencian,Spanish (LA)_Spanish (Iberian),AVERAGE_QUALITY,ON_TIME_SCORE,Engineering_experience,Miscellaneous_experience,ProofReading_experience,Translation_experience,TIME_TO_START
0,Aaron,09:00:00,19:00:00,1,1,1,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.000000,NaN
1,Abdon,10:00:00,20:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.000000,NaN
2,Abdon Isaias,09:00:00,19:00:00,1,1,1,1,1,1,1,...,NaN,NaN,NaN,7.75,1.0,0.0,535.076667,0.0,407.191111,NaN
3,Abdon Luis,04:00:00,14:00:00,0,0,0,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.000000,NaN
4,Abel Irene,07:00:00,17:00:00,0,0,0,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.000000,NaN

In [ ]:
# Checking the area of expertise of each translator (from more specific to less specific)

# Create Specific Subindustry Columns (e.g., 'SUB_Footwear')
df1['SUB_CLEAN'] = "SUB_" + df1['MANUFACTURER_SUBINDUSTRY'].astype(str)
sub_pivot = df1.pivot_table(index='TRANSLATOR', columns='SUB_CLEAN', values='TRANSLATOR_WORKING_TIME', aggfunc='sum').reset_index()
sub_pivot = sub_pivot.rename(columns={'TRANSLATOR': 'NAME'})
translators_df = translators_df.merge(sub_pivot, on='NAME', how='left')

# Create Specific Industry Columns (e.g., 'IND_Health Care Equipment & Devices')
df1['IND_CLEAN'] = "IND_" + df1['MANUFACTURER_INDUSTRY'].astype(str)
ind_pivot = df1.pivot_table(index='TRANSLATOR', columns='IND_CLEAN', values='TRANSLATOR_WORKING_TIME', aggfunc='sum').reset_index()
ind_pivot = ind_pivot.rename(columns={'TRANSLATOR': 'NAME'})
translators_df = translators_df.merge(ind_pivot, on='NAME', how='left')

# Create Broad Sector Columns (e.g., 'GRP_Health Care Equipment, Supplies & Technology')
df1['GRP_CLEAN'] = "GRP_" + df1['MANUFACTURER_INDUSTRY_GROUP'].astype(str)
grp_pivot = df1.pivot_table(index='TRANSLATOR', columns='GRP_CLEAN', values='TRANSLATOR_WORKING_TIME', aggfunc='sum').reset_index()
grp_pivot = grp_pivot.rename(columns={'TRANSLATOR': 'NAME'})
translators_df = translators_df.merge(grp_pivot, on='NAME', how='left')

# Clean up NaNs (Replace with 0 hours of experience for all prefixes)
exp_cols = [c for c in translators_df.columns if str(c).startswith('SUB_') or str(c).startswith('IND_') or str(c).startswith('GRP_')]
translators_df[exp_cols] = translators_df[exp_cols].fillna(0)

# CSP

In [ ]:
# ==========================================
# THE CSP SOLVER CLASS
# ==========================================

class TaskAssignmentCSP:
    """
    This class acts as the 'Decision Engine' that connects HR Data (translators_df),
    CRM Data (df3 / clients), and Historical Data (df1) to find the perfect match
    using hard constraints, schedule parsing, and automatic constraint relaxation.
    """
    def __init__(self, translators_df):
        # We create a safe copy of the translator database so we can filter and manipulate
        # the data without corrupting the original dataframe.
        self.translators_df = translators_df.copy()

    def build_client_requirements(self, company_name, clients_df, historical_df, task_date, task_start_time, task_length_hours, language_pair,
                                  task_type='Translation', followed_by=None, previous_translator_experience=0.0):
        """
        THE AUTO-LOADER: Scans the Clients database (df3) for budget/quality/wildcard, and scans the Historical
        database (df1) to automatically extract all industries. It creates a dictionary of constraints.
        """
        # STEP 1: Look up the company in the CRM database (df3)
        client_data = clients_df[clients_df['CLIENT_NAME'] == company_name]

        if client_data.empty:
            print(f"ERROR: Company '{company_name}' not found in the Clients database.")
            return None

        # Extract the strict billing and quality rules for this specific client
        max_rate = client_data['SELLING_HOURLY_PRICE'].iloc[0]
        min_quality = client_data['MIN_QUALITY'].iloc[0]

        # If the client has a strict on-time score requirement, use it. Otherwise, default to 80% (0.8).
        min_on_time = client_data['MIN_ON_TIME_SCORE'].iloc[0] if 'MIN_ON_TIME_SCORE' in client_data.columns else 0.8

        # Extract the "Wildcard" preference (e.g., 'price', 'deadline', 'quality').
        # This tells the system what the client is willing to sacrifice if we can't find a perfect match.
        if 'WILDCARD' in client_data.columns:
            wildcard = str(client_data['WILDCARD'].iloc[0]).strip().lower()
        else:
            wildcard = 'balanced' # Default if no wildcard exists

        # STEP 2: Cross-reference the Historical Database (df1) to find all industries this client operates in.
        company_history = historical_df[historical_df['MANUFACTURER'] == company_name]

        if company_history.empty:
            subindustries, industries, groups = [], [], []
        else:
            # Extract unique values and clean them (remove trailing spaces) to match our column names perfectly
            subindustries = [str(x).strip() for x in company_history['MANUFACTURER_SUBINDUSTRY'].dropna().unique()]
            industries = [str(x).strip() for x in company_history['MANUFACTURER_INDUSTRY'].dropna().unique()]
            groups = [str(x).strip() for x in company_history['MANUFACTURER_INDUSTRY_GROUP'].dropna().unique()]

        # STEP 3: Compile everything into the 'task_reqs' dictionary.
        # This dictionary is passed around to all other functions as the "Source of Truth" for the task.
        task_reqs = {
            'language_pair': language_pair,
            'task_date': task_date,
            'task_start_time': task_start_time,
            'task_length_hours': task_length_hours,
            'max_hourly_rate': max_rate,
            'min_quality': min_quality,
            'min_on_time_score': min_on_time,
            'wildcard': wildcard,

            # Task Type and Dependencies (e.g., Translation vs Proofreading)
            'task_type': task_type,
            'followed_by': followed_by,
            'previous_translator_experience': previous_translator_experience,

            # Expertise requirements (from strictest to broadest)
            'required_subindustry': subindustries,
            'required_industry': industries,
            'required_industry_group': groups,

            # Default minimum hours of experience needed to be considered "qualified"
            'min_subindustry_experience': 1.0,
            'min_industry_experience': 1.0,
            'min_industry_group_experience': 1.0
        }

        print(f"\n--- AUTO-LOADED PROFILE FOR: {company_name} ---")
        print(f">> Task Type: {task_type.upper()}")
        print(f">> Budget: ${max_rate}/hr | Min Quality: {min_quality}")

        return task_reqs

    def diagnose_bottleneck(self, task_reqs):
        """
        THE DIAGNOSTIC TOOL: This applies constraints one by one to print EXACTLY which rule
        eliminates candidates. It is used when the system returns a Fatal Error, allowing
        Project Managers to see why staffing failed.
        """
        print("\n--- CSP BOTTLENECK DIAGNOSTIC ---")
        domain = self.translators_df.copy()

        # Language pair check
        pair = task_reqs.get('language_pair')
        if pair not in domain.columns:
            print(f"FAILED: Nobody speaks {pair}.")
            return

        # Keep only people whose hourly rate for this language is NOT empty (NaN)
        domain = domain[domain[pair].notna()]
        print(f"Language ({pair}): {len(domain)} translators available.")
        if domain.empty: return

        # Budget check (Must be <= Client Budget)
        if 'max_hourly_rate' in task_reqs:
            domain = domain[domain[pair] <= task_reqs['max_hourly_rate']]
            print(f"Budget (<= ${task_reqs['max_hourly_rate']}): {len(domain)} translators left.")
            if domain.empty: return

        # Quality check
        if 'min_quality' in task_reqs:
            domain = domain[domain['AVERAGE_QUALITY'] >= task_reqs['min_quality']]
            print(f"Quality (>= {task_reqs['min_quality']}): {len(domain)} translators left.")
            if domain.empty: return

        # On-Time Delivery check
        if 'min_on_time_score' in task_reqs:
            domain = domain[domain['ON_TIME_SCORE'] >= task_reqs['min_on_time_score']]
            print(f"On-Time (>= {task_reqs['min_on_time_score']}): {len(domain)} translators left.")
            if domain.empty: return

        # Day Schedule Availability check (e.g., Do they work on Mondays?)
        if 'task_date' in task_reqs:
            task_date = pd.to_datetime(task_reqs['task_date'])
            day_mapping = {
                'Monday': 'MON', 'Tuesday': 'TUES', 'Wednesday': 'WED',
                'Thursday': 'THURS', 'Friday': 'FRI', 'Saturday': 'SAT', 'Sunday': 'SUN'
            }
            schedule_col = day_mapping.get(task_date.day_name())
            if schedule_col in domain.columns:
                domain = domain[domain[schedule_col] == 1]
                print(f"Schedule (Works on {task_date.day_name()}): {len(domain)} translators left.")
                if domain.empty: return

        #  Hour Shift Capacity check (Do their hours cover the project window?)
        if 'task_length_hours' in task_reqs and 'task_start_time' in task_reqs:
            if 'START' in domain.columns and 'END' in domain.columns:
                # Clean periods out of time strings (e.g., '14.00' -> '1400')
                clean_start = domain['START'].astype(str).str.replace('.', '', regex=False).str.upper()
                clean_end = domain['END'].astype(str).str.replace('.', '', regex=False).str.upper()

                shift_starts = pd.to_datetime(clean_start, format='mixed', errors='coerce')
                shift_ends = pd.to_datetime(clean_end, format='mixed', errors='coerce')

                # Handle overnight shifts (if end time is earlier than start time, add 1 full day to end time)
                shift_ends = shift_ends.mask(shift_ends < shift_starts, shift_ends + pd.Timedelta(days=1))

                task_start = pd.to_datetime(task_reqs['task_start_time'])
                task_end = task_start + pd.Timedelta(hours=task_reqs['task_length_hours'])

                # Check Start Time: Translator must start before or exactly when the task starts
                domain = domain[shift_starts <= task_start]
                print(f"Shift Start (<= {task_start.strftime('%H:%M')}): {len(domain)} translators left.")
                if domain.empty: return

                # Check End Time: Translator must end after or exactly when the task ends.
                # .loc[domain.index] aligns the dataframes to prevent Pandas UserWarnings
                aligned_shift_ends = shift_ends.loc[domain.index]
                domain = domain[aligned_shift_ends >= task_end]
                print(f"Shift End (>= {task_end.strftime('%H:%M')}): {len(domain)} translators left.")
                if domain.empty: return

        # 3-Tier Hierarchical Expertise check
        if 'required_subindustry' in task_reqs and task_reqs['required_subindustry']:
            req_subs = task_reqs['required_subindustry']
            min_exp = task_reqs.get('min_subindustry_experience', 1.0)
            valid_sub_cols = [f"SUB_{s}" for s in req_subs if f"SUB_{s}" in domain.columns]

            if valid_sub_cols:
                mask = (domain[valid_sub_cols] >= min_exp).any(axis=1) # Checks if ANY required subindustry >= 1.0 hours
                domain = domain[mask]
                print(f"Sub-Industry Expertise (ANY of {req_subs} >= {min_exp} hrs): {len(domain)} translators left.")
                if domain.empty:
                    print(f"-> BOTTLENECK: Remaining translators lack specific Sub-Industry experience in any of {req_subs}.")
                    return
            else:
                print(f"FAILED: None of the required sub-industries {req_subs} exist in our historical data.")
                return

        # (If subindustry fails or isn't requested, it cascades down to Industry and Group in a similar fashion)
        elif 'required_industry' in task_reqs and task_reqs['required_industry']:
            req_inds = task_reqs['required_industry']
            min_exp = task_reqs.get('min_industry_experience', 1.0)
            valid_ind_cols = [f"IND_{i}" for i in req_inds if f"IND_{i}" in domain.columns]

            if valid_ind_cols:
                mask = (domain[valid_ind_cols] >= min_exp).any(axis=1)
                domain = domain[mask]
                print(f"Industry Expertise (ANY of {req_inds} >= {min_exp} hrs): {len(domain)} translators left.")
                if domain.empty:
                    print(f"-> BOTTLENECK: Remaining translators lack Industry experience in any of {req_inds}.")
                    return
            else:
                print(f"FAILED: None of the required industries {req_inds} exist in our historical data.")
                return

        elif 'required_industry_group' in task_reqs and task_reqs['required_industry_group']:
            req_grps = task_reqs['required_industry_group']
            min_exp = task_reqs.get('min_industry_group_experience', 1.0)
            valid_grp_cols = [f"GRP_{g}" for g in req_grps if f"GRP_{g}" in domain.columns]

            if valid_grp_cols:
                mask = (domain[valid_grp_cols] >= min_exp).any(axis=1)
                domain = domain[mask]
                print(f"Industry Group Expertise (ANY of {req_grps} >= {min_exp} hrs): {len(domain)} translators left.")
                if domain.empty:
                    print(f"-> BOTTLENECK: Remaining translators lack broad Industry Group experience in any of {req_grps}.")
                    return
            else:
                print(f"FAILED: None of the required industry groups {req_grps} exist in our historical data.")
                return

        print("SUCCESS: Translators are available.")

    def get_eligible_translators(self, task_reqs):
        """
        THE LOGIC CORE: Filters out translators based on requirements and dynamic TASK TYPE business rules.
        Returns a dataframe of all candidates who mathematically pass all tests.
        """
        domain = self.translators_df.copy()

        # ==========================================
        # PRE-PROCESSING: DYNAMIC TASK TYPE RULES
        # ==========================================
        working_reqs = task_reqs.copy()
        task_type = working_reqs.get('task_type', 'Translation')
        followed_by = working_reqs.get('followed_by', None)
        prev_exp = working_reqs.get('previous_translator_experience', 0.0)

        # Apply specific business logic based on the task classification
        if task_type == 'TEST':
            # "TEST": Ignore budget/price so we can find the absolute best talent.
            if 'max_hourly_rate' in working_reqs: del working_reqs['max_hourly_rate']

        elif task_type == 'Training':
            # "Training": Quality doesn't matter, and no past experience is required.
            if 'min_quality' in working_reqs: del working_reqs['min_quality']
            working_reqs['min_subindustry_experience'] = 0
            working_reqs['min_industry_experience'] = 0
            working_reqs['min_industry_group_experience'] = 0

        elif task_type == 'Translation' and followed_by == 'ProofReading':
            # "Translation (with Proofing)": We can accept a slightly lower quality translator
            # because a superior proofreader will catch mistakes later, saving the client money.
            if 'min_quality' in working_reqs:
                working_reqs['min_quality'] = max(0, working_reqs['min_quality'] - 1.0)

        # Ensure the candidate has at least *some* experience in the specific task type (e.g. DTP)
        if task_type != 'Training':
            task_exp_col = f"{task_type}_experience"
            if task_exp_col in domain.columns:
                domain = domain[domain[task_exp_col] > 0]

        # ==========================================
        # 1. LANGUAGE & FINANCIAL METRICS
        # ==========================================
        pair = working_reqs.get('language_pair')
        if pair not in domain.columns: return pd.DataFrame()
        domain = domain[domain[pair].notna()]

        # Filter by Budget, Quality, and On-Time
        if 'max_hourly_rate' in working_reqs: domain = domain[domain[pair] <= working_reqs['max_hourly_rate']]
        if 'min_quality' in working_reqs: domain = domain[domain['AVERAGE_QUALITY'] >= working_reqs['min_quality']]
        if 'min_on_time_score' in working_reqs: domain = domain[domain['ON_TIME_SCORE'] >= working_reqs['min_on_time_score']]

        # ==========================================
        # 2. SCHEDULE & TIME WINDOW CAPACITY
        # ==========================================
        if 'task_date' in working_reqs:
            task_date = pd.to_datetime(working_reqs['task_date'])
            day_mapping = {'Monday': 'MON', 'Tuesday': 'TUES', 'Wednesday': 'WED', 'Thursday': 'THURS', 'Friday': 'FRI', 'Saturday': 'SAT', 'Sunday': 'SUN'}
            schedule_col = day_mapping.get(task_date.day_name())
            if schedule_col in domain.columns: domain = domain[domain[schedule_col] == 1]

        if 'task_length_hours' in working_reqs and 'task_start_time' in working_reqs:
            if 'START' in domain.columns and 'END' in domain.columns:
                clean_start = domain['START'].astype(str).str.replace('.', '', regex=False).str.upper()
                clean_end = domain['END'].astype(str).str.replace('.', '', regex=False).str.upper()

                shift_starts = pd.to_datetime(clean_start, format='mixed', errors='coerce')
                shift_ends = pd.to_datetime(clean_end, format='mixed', errors='coerce')
                shift_ends = shift_ends.mask(shift_ends < shift_starts, shift_ends + pd.Timedelta(days=1))

                task_start = pd.to_datetime(working_reqs['task_start_time'])
                task_end = task_start + pd.Timedelta(hours=working_reqs['task_length_hours'])

                # Combine both time conditions to avoid pandas index re-indexing warnings
                valid_time_window = (shift_starts <= task_start) & (shift_ends >= task_end)
                domain = domain[valid_time_window]

        # ==========================================
        # 3. 3-TIER HIERARCHICAL EXPERTISE
        # ==========================================
        def filter_by_list(domain_df, req_list, prefix, min_exp):
            """Helper function to filter dataframe based on a list of acceptable industries."""
            valid_cols = [f"{prefix}_{req}" for req in req_list if f"{prefix}_{req}" in domain_df.columns]
            if not valid_cols: return pd.DataFrame()

            # NEW BUSINESS RULE: Dependency Override for Review Tasks
            # Proofreaders and Spotcheckers MUST have more experience than the original translator
            if task_type in ['ProofReading', 'Spotcheck'] and prev_exp > 0:
                required_exp = max(min_exp, prev_exp + 0.1)
            else:
                required_exp = min_exp

            mask = (domain_df[valid_cols] >= required_exp).any(axis=1)
            return domain_df[mask]

        # Process the tiers from strictest (Sub-Industry) to broadest (Group)
        if 'required_subindustry' in working_reqs and working_reqs['required_subindustry']:
            domain = filter_by_list(domain, working_reqs['required_subindustry'], 'SUB', working_reqs.get('min_subindustry_experience', 1.0))
            if domain.empty: return domain

        elif 'required_industry' in working_reqs and working_reqs['required_industry']:
            domain = filter_by_list(domain, working_reqs['required_industry'], 'IND', working_reqs.get('min_industry_experience', 1.0))
            if domain.empty: return domain

        elif 'required_industry_group' in working_reqs and working_reqs['required_industry_group']:
            domain = filter_by_list(domain, working_reqs['required_industry_group'], 'GRP', working_reqs.get('min_industry_group_experience', 1.0))
            if domain.empty: return domain

        return domain

    def split_task_across_days(self, task_reqs, num_days=2):
        """
        Splits a very long task across consecutive days for a single translator.
        E.g., A 16-hour task becomes two 8-hour days.
        """
        print(f"\n--- INITIATING {num_days}-DAY TASK SPLIT ---")
        domain = self.translators_df.copy()

        # Apply Base Constraints
        pair = task_reqs.get('language_pair')
        if pair in domain.columns: domain = domain[domain[pair].notna()]
        if 'max_hourly_rate' in task_reqs: domain = domain[domain[pair] <= task_reqs['max_hourly_rate']]
        if 'min_quality' in task_reqs: domain = domain[domain['AVERAGE_QUALITY'] >= task_reqs['min_quality']]
        if 'min_on_time_score' in task_reqs: domain = domain[domain['ON_TIME_SCORE'] >= task_reqs['min_on_time_score']]

        # Apply Hierarchical Expertise limits
        def filter_by_list(domain_df, req_list, prefix, min_exp):
            valid_cols = [f"{prefix}_{req}" for req in req_list if f"{prefix}_{req}" in domain_df.columns]
            if not valid_cols:
                return pd.DataFrame()
            mask = (domain_df[valid_cols] >= min_exp).any(axis=1)
            return domain_df[mask]

        if 'required_subindustry' in task_reqs and task_reqs['required_subindustry']:
            domain = filter_by_list(domain, task_reqs['required_subindustry'], 'SUB', task_reqs.get('min_subindustry_experience', 1.0))
        elif 'required_industry' in task_reqs and task_reqs['required_industry']:
            domain = filter_by_list(domain, task_reqs['required_industry'], 'IND', task_reqs.get('min_industry_experience', 1.0))
        elif 'required_industry_group' in task_reqs and task_reqs['required_industry_group']:
            domain = filter_by_list(domain, task_reqs['required_industry_group'], 'GRP', task_reqs.get('min_industry_group_experience', 1.0))

        if domain.empty:
            print("FAILED: No translators have the required expertise to handle a split task.")
            return domain

        # SCHEDULE AVAILABILITY (Must be Consecutive Days)
        # We loop through X amount of days, continuously overwriting the domain (acting as an AND gate).
        # If they work Monday but not Tuesday, they get dropped in the second loop.
        if 'task_date' in task_reqs:
            start_date = pd.to_datetime(task_reqs['task_date'])
            day_mapping = {
                'Monday': 'MON', 'Tuesday': 'TUES', 'Wednesday': 'WED',
                'Thursday': 'THURS', 'Friday': 'FRI', 'Saturday': 'SAT', 'Sunday': 'SUN'
            }
            for i in range(num_days):
                current_date = start_date + pd.Timedelta(days=i)
                schedule_col = day_mapping.get(current_date.day_name())
                if schedule_col in domain.columns:
                    domain = domain[domain[schedule_col] == 1]

            end_date = start_date + pd.Timedelta(days=num_days - 1)
            print(f">> Verified consecutive availability from {start_date.day_name()} to {end_date.day_name()}.")

        # SHIFT CAPACITY / TIME WINDOW
        # If the task is 16 hours over 2 days, we now require 8 hours of capacity per day.
        if 'task_length_hours' in task_reqs and 'task_start_time' in task_reqs:
            if 'START' in domain.columns and 'END' in domain.columns:
                clean_start = domain['START'].astype(str).str.replace('.', '', regex=False).str.upper()
                clean_end = domain['END'].astype(str).str.replace('.', '', regex=False).str.upper()

                shift_starts = pd.to_datetime(clean_start, format='mixed', errors='coerce')
                shift_ends = pd.to_datetime(clean_end, format='mixed', errors='coerce')
                shift_ends = shift_ends.mask(shift_ends < shift_starts, shift_ends + pd.Timedelta(days=1))

                task_start = pd.to_datetime(task_reqs['task_start_time'])

                # Math: Split the required hours across the days
                required_daily_capacity = task_reqs['task_length_hours'] / num_days
                task_end = task_start + pd.Timedelta(hours=required_daily_capacity)

                valid_time_window = (shift_starts <= task_start) & (shift_ends >= task_end)
                domain = domain[valid_time_window]
                print(f">> Reduced required shift to {required_daily_capacity:.2f} hours/day (between {task_start.strftime('%H:%M')} and {task_end.strftime('%H:%M')}).")

        elif 'task_length_hours' in task_reqs and 'START' in domain.columns and 'END' in domain.columns:
            # Legacy fallback if no start_time was provided
            clean_start = domain['START'].astype(str).str.replace('.', '', regex=False).str.upper()
            clean_end = domain['END'].astype(str).str.replace('.', '', regex=False).str.upper()
            start_times = pd.to_datetime(clean_start, errors='coerce')
            end_times = pd.to_datetime(clean_end, errors='coerce')
            shift_length = (end_times - start_times).dt.total_seconds() / 3600
            domain['DAILY_CAPACITY'] = shift_length.fillna(0).apply(lambda x: x + 24 if x < 0 else x)

            required_daily_capacity = task_reqs['task_length_hours'] / num_days
            print(f">> Reduced required daily capacity to {required_daily_capacity:.2f} hours/day.")
            domain = domain[domain['DAILY_CAPACITY'] >= required_daily_capacity]

        if not domain.empty:
            print(f"SUCCESS: Found {len(domain)} translators who can handle this over {num_days} days.")
        else:
            print(f"FAILED: No translators can handle this, even when split over {num_days} days.")

        return domain

    def split_task_across_translators(self, task_reqs, num_translators=2):
        """
        Splits a task so multiple translators can work on it SIMULTANEOUSLY.
        E.g., An 8-hour task needs 2 translators working 4 hours each.
        """
        print(f"\n--- INITIATING PARALLEL SPLIT: {num_translators} TRANSLATORS ---")
        split_reqs = task_reqs.copy()

        # Update capacity requirements for parallel work
        if 'task_length_hours' in split_reqs:
            split_reqs['task_length_hours'] = split_reqs['task_length_hours'] / num_translators

            # Show the exact time window if task_start_time is used
            if 'task_start_time' in split_reqs:
                try:
                    task_start = pd.to_datetime(split_reqs['task_start_time'])
                    task_end = task_start + pd.Timedelta(hours=split_reqs['task_length_hours'])
                    print(f">> Reduced required shift to {split_reqs['task_length_hours']:.2f} hours per translator (between {task_start.strftime('%H:%M')} and {task_end.strftime('%H:%M')}).")
                except Exception:
                    # Fallback just in case datetime parsing fails
                    print(f">> Reduced required shift to {split_reqs['task_length_hours']:.2f} hours per translator.")
            else:
                print(f">> Reduced required daily capacity to {split_reqs['task_length_hours']:.2f} hours per translator.")

        # Let the robust get_eligible_translators method handle all the complex filtering
        domain = self.get_eligible_translators(split_reqs)

        # Check if we have enough translators to form the required team size
        if len(domain) >= num_translators:
            print(f"SUCCESS: Found {len(domain)} available translators. Forming team of {num_translators}.")
            return domain
        else:
            print(f"FAILED: Need {num_translators} translators, but only found {len(domain)}.")
            return pd.DataFrame()

    def get_translators_with_fallback(self, task_reqs):
        """
        THE ESCALATION PIPELINE:
        Attempts Strict (Level 1) -> Industry (Level 2) -> Group (Level 3) ->
        Targeted Wildcard Relaxation (Level 4) -> Global Relaxation (Level 5).
        """
        print("\n--- ATTEMPT 1: Strict Requirements (Sub-Industry Specialist Needed) ---")
        eligible = self.get_eligible_translators(task_reqs)

        if not eligible.empty:
            print(f"SUCCESS: Found {len(eligible)} specialists matching Sub-Industry.")
            return eligible

        print("FAILED: No Sub-Industry specialists found. Initiating Fallback...")
        relaxed_reqs = task_reqs.copy()

        # --- ATTEMPT 2: RELAX TO INDUSTRY ---
        # If we asked for "Solar Power" and failed, we relax it to "Utilities".
        if 'required_subindustry' in relaxed_reqs and relaxed_reqs['required_subindustry'] and 'required_industry' in relaxed_reqs and relaxed_reqs['required_industry']:
            print(f"\n--- ATTEMPT 2: Relaxing to Mid-Level Industry ---")
            del relaxed_reqs['required_subindustry']

            lvl2_eligible = self.get_eligible_translators(relaxed_reqs)
            if not lvl2_eligible.empty:
                print(f"COMPROMISE SUCCESS: Found {len(lvl2_eligible)} mid-level specialists.")
                return lvl2_eligible
            print("FAILED: Mid-level Industry search didn't yield enough translators.")

        # --- ATTEMPT 3: RELAX TO INDUSTRY GROUP ---
        # If "Utilities" failed, we relax to general "Energy".
        if 'required_industry' in relaxed_reqs and relaxed_reqs['required_industry'] and 'required_industry_group' in relaxed_reqs and relaxed_reqs['required_industry_group']:
            print(f"\n--- ATTEMPT 3: Relaxing to Broad Industry Group ---")
            del relaxed_reqs['required_industry']

            lvl3_eligible = self.get_eligible_translators(relaxed_reqs)
            if not lvl3_eligible.empty:
                print(f"COMPROMISE SUCCESS: Found {len(lvl3_eligible)} generalists in the Industry Group.")
                return lvl3_eligible
            print("FAILED: Broad Industry Group search failed.")

        # --- ATTEMPT 4: TARGETED WILDCARD RELAXATION ---
        # Uses the CRM Wildcard. "What is this client willing to sacrifice?"
        wildcard = relaxed_reqs.get('wildcard', 'balanced')
        print(f"\n--- ATTEMPT 4: Targeted Wildcard Relaxation ({wildcard.upper()}) ---")

        wildcard_reqs = relaxed_reqs.copy()

        if wildcard == 'quality':
            wildcard_reqs['min_quality'] = max(0, wildcard_reqs['min_quality'] - 1.5)
            print(f">> Wildcard Triggered: Lowered minimum quality significantly to {wildcard_reqs['min_quality']}")

        elif wildcard == 'price':
            wildcard_reqs['max_hourly_rate'] = wildcard_reqs['max_hourly_rate'] * 1.25 # 25% budget boost
            print(f">> Wildcard Triggered: Increased budget threshold by 25% to ${wildcard_reqs['max_hourly_rate']:.2f}")

        elif wildcard == 'deadline' or wildcard == 'time':
            wildcard_reqs['min_on_time_score'] = max(0, wildcard_reqs['min_on_time_score'] - 0.20)
            wildcard_reqs['capacity_tolerance'] = 0.70 # Give a massive 30% schedule tolerance
            print(f">> Wildcard Triggered: Relaxed On-Time score to {wildcard_reqs['min_on_time_score']} and allowed 30% schedule shift")
        else:
            print(">> No specific wildcard provided or recognized. Moving to global relaxation.")

        # Only check if a wildcard actually changed something
        if wildcard in ['quality', 'price', 'deadline', 'time']:
            wildcard_eligible = self.get_eligible_translators(wildcard_reqs)
            if not wildcard_eligible.empty:
                print(f"COMPROMISE SUCCESS: Found {len(wildcard_eligible)} translators by flexing the client's {wildcard.upper()} preference.")
                return wildcard_eligible
            print(f"FAILED: Flexing the {wildcard.upper()} was not enough to find a candidate.")


        final_eligible = self.get_eligible_translators(relaxed_reqs)

        if not final_eligible.empty:
            print(f"COMPROMISE SUCCESS: Found {len(final_eligible)} translators using global relaxation.")
            return final_eligible
        else:
            print("\nCRITICAL FAILURE: Maximum global relaxation reached. No translators available.")
            return pd.DataFrame()


    def get_workflow_candidates(self, company_name, clients_df, historical_df, task_date, task_start_time,
                                translation_hours, proofreading_hours, language_pair,
                                base_task_type='Translation', selected_translator_name=None):
        """
        THE WORKFLOW PIPELINE: Handles dependent tasks (e.g. Translation followed by Proofreading).

        Because a Proofreader MUST have more experience than the initial Translator,
        we must break this into a Two-Step Function (like an API waiting for UI input).

        Step 1. If 'selected_translator_name' is None: Run the base task and return eligible translators.
        Step 2. If 'selected_translator_name' is provided: Run the proofreading task, calculate the time
                offset, and ensure the proofreader beats the translator's experience score.
        """
        print(f"\n=======================================================")
        print(f"  WORKFLOW ENGINE: {base_task_type.upper()} -> PROOFREADING")
        print(f"=======================================================")

        # ---------------------------------------------------------
        # STEP 1: GET BASE CANDIDATES
        # ---------------------------------------------------------
        base_reqs = self.build_client_requirements(
            company_name=company_name, clients_df=clients_df, historical_df=historical_df,
            task_date=task_date, task_start_time=task_start_time, task_length_hours=translation_hours,
            language_pair=language_pair, task_type=base_task_type, followed_by='ProofReading'
        )

        base_candidates = self.get_translators_with_fallback(base_reqs)

        if base_candidates.empty:
            print(f"\n[SYSTEM ERROR] Cannot staff the {base_task_type}. Aborting workflow.")
            return pd.DataFrame(), pd.DataFrame()

        # Phase 1 Stop: If the PM hasn't picked anyone yet, return the list so they can choose!
        if selected_translator_name is None:
            print(f"\n[SYSTEM] Found {len(base_candidates)} base candidates. Awaiting PM selection to generate ProofReaders.")
            return base_candidates, pd.DataFrame()

        # ---------------------------------------------------------
        # STEP 2: EXTRACT DATA FOR THE CHOSEN TRANSLATOR
        # ---------------------------------------------------------
        chosen_data = base_candidates[base_candidates['NAME'] == selected_translator_name]

        if chosen_data.empty:
            print(f"\n[SYSTEM ERROR] Translator '{selected_translator_name}' is not in the eligible list!")
            return base_candidates, pd.DataFrame()

        chosen_translator = chosen_data.iloc[0]

        # Loop through their stats to find exactly how much experience they have in the required industry.
        # This will be the score the Proofreader must beat.
        exp_score = 0.0
        for level, prefix in [('required_subindustry', 'SUB'), ('required_industry', 'IND'), ('required_industry_group', 'GRP')]:
            if level in base_reqs and base_reqs[level]:
                for item in base_reqs[level]:
                    col_name = f"{prefix}_{item}"
                    if col_name in chosen_translator.index:
                        exp_score = max(exp_score, chosen_translator[col_name])
                if exp_score > 0:
                    break

        # ---------------------------------------------------------
        # STEP 3: AUTO-SCHEDULE & GET PROOFREADERS
        # ---------------------------------------------------------
        # Time Offset Math: If Translation starts at 9am and takes 4 hours, Proofreading MUST start at 1pm.
        base_start_dt = pd.to_datetime(f"{task_date} {task_start_time}")
        proof_start_dt = base_start_dt + pd.Timedelta(hours=translation_hours)

        print(f"\n=======================================================")
        print(f"  PHASE 2: {selected_translator_name.upper()} SELECTED FOR {base_task_type.upper()}")
        print(f"  >> Their Sector Experience: {exp_score:.2f} hours")
        print(f"  >> Finding ProofReaders for {proof_start_dt.strftime('%H:%M')} (Must beat {exp_score:.2f} hrs)")
        print(f"=======================================================")

        # Build new requirements specifically for the Proofreader
        proof_reqs = self.build_client_requirements(
            company_name=company_name, clients_df=clients_df, historical_df=historical_df,
            task_date=proof_start_dt.strftime('%Y-%m-%d'),
            task_start_time=proof_start_dt.strftime('%H:%M'),
            task_length_hours=proofreading_hours,
            language_pair=language_pair,
            task_type='ProofReading',
            previous_translator_experience=exp_score
        )

        proof_candidates = self.get_translators_with_fallback(proof_reqs)

        if not proof_candidates.empty:
            # Business Logic: A translator cannot proofread their own work. Remove them from the list.
            proof_candidates = proof_candidates[proof_candidates['NAME'] != selected_translator_name]

        return base_candidates, proof_candidates

# =========================================================================================
# EXECUTION AND TESTING: TWO-PHASE WORKFLOW
# =========================================================================================

# Initialize Solver
csp_solver = TaskAssignmentCSP(translators_df)

# DEFINE PIPELINE PARAMETERS
company_name = "Accesstra"
task_date = "2023-04-24"
task_start_time = "09:00"
task_hours = 4.0      # Length of the base task
proofreading_hours = 2.0     # Length of the subsequent task
language = "English_Spanish (Iberian)"

print("\n" + "="*60)
print(f"  PHASE 1: ASSIGNING THE BASE TRANSLATION TASK")
print("="*60)

# PHASE 1: EXECUTE BASE TASK
# We use build_client_requirements to pull Accesstra's CRM profile and create the base rules
task_requirements = csp_solver.build_client_requirements(
    company_name=company_name,
    clients_df=df3,
    historical_df=df1,
    task_date=task_date,
    task_start_time=task_start_time,
    task_length_hours=task_hours,
    language_pair=language,
    task_type="Miscellaneous",
    followed_by="ProofReading"
)

if task_requirements:
    # Attempt to assign the task normally (escalating if necessary)
    final_candidates = csp_solver.get_translators_with_fallback(task_requirements)

    # --- WILDCARD-DRIVEN SPLIT STRATEGY ---
    # If the standard search fails, it decides how to split the task based on the client's Wildcard.
    if final_candidates.empty:
        wildcard = task_requirements.get('wildcard', 'balanced').lower()

        # Scenario A: Client is flexible on time. Priority -> Extend the deadline across multiple days to save costs.
        if wildcard in ['deadline', 'time', 'schedule']:
            print(f"\n[SYSTEM] Wildcard is {wildcard.upper()}. Prioritizing Multi-Day Split to save costs.")
            final_candidates = csp_solver.split_task_across_days(task_requirements, num_days=2)

            # If that still fails, fall back to parallel translators
            if final_candidates.empty:
                final_candidates = csp_solver.split_task_across_translators(task_requirements, num_translators=2)

        # Scenario B: Client is flexible on Price/Quality but Strict on Deadline. Priority -> Build a Team.
        else:
            print(f"\n[SYSTEM] Wildcard is {wildcard.upper()} (Deadline strict). Prioritizing Team Assembly.")
            final_candidates = csp_solver.split_task_across_translators(task_requirements, num_translators=2)

            if final_candidates.empty:
                final_candidates = csp_solver.split_task_across_days(task_requirements, num_days=2)

    # --- DISPLAY PHASE 1 RESULTS ---
    if not final_candidates.empty:
        print(f"\n--- FOUND {len(final_candidates)} ELIGIBLE TRANSLATORS ---")
        desired_columns = ['NAME', language, 'DAILY_CAPACITY', 'AVERAGE_QUALITY', 'ON_TIME_SCORE']

        # Dynamically append the correct Expertise column so the PM can verify their experience
        if 'required_subindustry' in task_requirements and task_requirements['required_subindustry']:
            desired_columns.append(f"SUB_{task_requirements['required_subindustry'][0]}")
        elif 'required_industry' in task_requirements and task_requirements['required_industry']:
            desired_columns.append(f"IND_{task_requirements['required_industry'][0]}")
        elif 'required_industry_group' in task_requirements and task_requirements['required_industry_group']:
            desired_columns.append(f"GRP_{task_requirements['required_industry_group'][0]}")

        # Safe Filtering: Only print columns that actually exist to avoid Pandas KeyErrors
        final_cols = [col for col in desired_columns if col in final_candidates.columns]
        print(final_candidates[final_cols].head(10)) # Print top 10 for neatness
    else:
        print("\n[SYSTEM FATAL ERROR] Impossible constraints.")
        csp_solver.diagnose_bottleneck(task_requirements) # Run the diagnostic to figure out why it failed!

# =========================================================================================
# PHASE 2: DEPENDENT TASK WORKFLOW (E.g. PostEditing or Proofreading)
# =========================================================================================

# If Phase 1 succeeded, the UI/Project Manager would select a translator.
# Here, we simulate that selection algorithmically.
if not final_candidates.empty:

    # Simulate picking the highest quality translator from the generated list
    selected_translator = final_candidates.sort_values(by='AVERAGE_QUALITY', ascending=False).iloc[0]
    selected_name = selected_translator['NAME']

    # Dynamically extract their exact experience score so the Proofreader can beat it
    exp_score = 0.0
    for level, prefix in [('required_subindustry', 'SUB'), ('required_industry', 'IND'), ('required_industry_group', 'GRP')]:
        if level in task_requirements and task_requirements[level]:
            for item in task_requirements[level]:
                col_name = f"{prefix}_{item}"
                if col_name in selected_translator.index:
                    exp_score = max(exp_score, selected_translator[col_name])
            if exp_score > 0: break

    # Calculate exact time offset (Base Start Time + Base Translation Hours)
    base_start_dt = pd.to_datetime(f"{task_date} {task_start_time}")
    proof_start_dt = base_start_dt + pd.Timedelta(hours=translation_hours)

    print("\n\n" + "="*60)
    print(f"  PHASE 2: AUTO-SCHEDULING PROOFREADER FOR {selected_name.upper()}")
    print(f"  >> Extracted Sector Experience: {exp_score:.2f} hours")
    print(f"  >> Calculating offset... Proofing must start at {proof_start_dt.strftime('%H:%M')}")
    print("="*60)

    # Build the requirements for the Proofreader, enforcing the time-offset and experience rules
    proof_requirements = csp_solver.build_client_requirements(
        company_name=company_name,
        clients_df=df3,
        historical_df=df1,
        task_date=proof_start_dt.strftime('%Y-%m-%d'),
        task_start_time=proof_start_dt.strftime('%H:%M'),
        task_length_hours=proofreading_hours,
        language_pair=language,
        task_type="ProofReading",
        previous_translator_experience=exp_score
    )

    if proof_requirements:
        proof_candidates = csp_solver.get_translators_with_fallback(proof_requirements)

        # Enforce Conflict of Interest Rule (Cannot proofread your own work)
        if not proof_candidates.empty:
            proof_candidates = proof_candidates[proof_candidates['NAME'] != selected_name]

        # DISPLAY PHASE 2 RESULTS
        if not proof_candidates.empty:
            print(f"\n--- FOUND {len(proof_candidates)} SUPERIOR PROOFREADERS ---")
            proof_cols = [col for col in desired_columns if col in proof_candidates.columns]
            print(proof_candidates[proof_cols].head(10))
        else:
            print(f"\n[SYSTEM WARNING] No ProofReaders found who have more than {exp_score:.2f} hours of experience and are available at {proof_start_dt.strftime('%H:%M')}.")
            csp_solver.diagnose_bottleneck(proof_requirements)

Found 2 eligible translators:
             NAME  English_Spanish (Iberian)  AVERAGE_QUALITY  ON_TIME_SCORE
2    Abdon Isaias                       17.0         7.750000            1.0
11  Acacio Poncio                       19.0         7.142857            1.0

/tmp/ipykernel_9155/1465123491.py:100: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  start_times = pd.to_datetime(clean_start, errors='coerce')
/tmp/ipykernel_9155/1465123491.py:101: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  end_times = pd.to_datetime(clean_end, errors='coerce')

# Dynamic Weighted Score model

While the Constraint Satisfaction Problem (CSP) solver is responsible for Feasibility (filtering out translators who strictly cannot perform the task), the system requires an Objective Function to handle Optimization (determining who is the absolute best choice among the survivors).

To achieve this, we transition from strict Boolean filtering to a Multi-Criteria Decision Analysis (MCDA) model. Every eligible candidate is graded on a 100-point scale.

However, rather than using a static formula, the system employs Context-Aware Dynamic Weighting. The algorithm intelligently shifts the mathematical weight of each variable based on the specific client's business priorities (the "Wildcard") and the structural nature of the task.

- **The Mathematical Model**

    The final Suitability Score is a linear combination of four normalized metrics, multiplied by their dynamic context weights: $Score = (N_{quality} \times W_q) + (N_{reliability} \times W_r) + (N_{expertise} \times W_e)$

    Where $\sum W = 100$

- **Feature Normalization ($N$)**
    
    Because our raw data operates on entirely different scales (e.g., a quality score out of 10 vs. an hourly rate in dollars vs. experience in hours), we must first normalize every variable to a standard scale of $0.0$ to $1.0$.
    - $N_{quality}$ (Quality Vector): Extracted directly from their historical average. A score of $8.5$ becomes $0.85$.
    - $N_{reliability}$ (Reliability Vector): Extracted from their on-time delivery ratio. A perfect historical delivery rate is already a $1.0$.
    - $N_{margin}$ (Profit Margin Vector): This measures how much money the agency saves by hiring this translator compared to the client's maximum budget.
     
      Formula: $\frac{MaxBudget - TranslatorRate}{MaxBudget}$
      
      Example: If the client pays 20€/hr and the translator costs 15€/hr, the normalized score is 0.25€ (a 25% profit margin).
    - $N_{expertise}$ (Specialization Vector): We calculate their cumulative hours in the requested sub-industry/industry. We apply a diminishing returns cap at 50 hours (representing full mastery). Formula: $\min\left(1.0, \frac{Logged Hours}{50}\right)$

- **Context-Aware Dynamic Weights ($W$)**

    The true power of the algorithm lies in how the weights dynamically shift. The baseline weight distribution is Balanced (40% Quality, 30% Reliability, 20% Profit, 10% Expertise). However, the engine intercepts the Client's WILDCARD preference to rewrite the objective function in real-time:

    - If *Wildcard* = PRICE: The system recognizes a highly price-sensitive environment. It drops the Quality and Reliability weights to 20% each, and surges the Profit Margin weight to 50%. The algorithm will now actively hunt for the cheapest viable translator to maximize agency margins without violating the baseline CSP constraints.

    - If *Wildcard* = DEADLINE: The system anticipates an urgent, time-sensitive delivery. It drops the Quality and Profit weights, and surges the Reliability weight to 60%. The algorithm actively punishes any translator with a history of late deliveries, regardless of how cheap or high-quality they are.

    - If *Task Type* = TEST: The system applies a Hard Override. Profit Margin and Reliability weights are forced to 0%, and Quality is surged to 80%. Because this is a client qualification test, the algorithm knows the agency must absorb the financial cost to submit the highest quality text possible to win the long-term contract.

In [ ]:
def rank_candidates(candidates_df, task_reqs):
    """
    POST-CSP OPTIMIZATION: Grades eligible translators on a 100-point scale.
    The weights shift dynamically based on the task wildcard and type.
    This runs completely independent of the CSP solver.
    """
    if candidates_df.empty:
        return candidates_df

    df = candidates_df.copy()

    # 1. DEFINE DYNAMIC WEIGHTS
    # Default Weights (Balanced: 40% Quality, 30% Reliability, 20% Margin, 10% Expertise)
    w_qual, w_rel, w_marg, w_exp = 40, 30, 20, 10

    wildcard = task_reqs.get('wildcard', 'balanced').lower()
    task_type = task_reqs.get('task_type', 'Translation')

    # Shift weights based on the Client's Wildcard
    if wildcard == 'quality':
        w_qual, w_rel, w_marg, w_exp = 60, 20, 10, 10
    elif wildcard == 'price':
        w_qual, w_rel, w_marg, w_exp = 20, 20, 50, 10
    elif wildcard in ['time', 'deadline', 'schedule']:
        w_qual, w_rel, w_marg, w_exp = 20, 60, 10, 10

    # Hard Override based on Task Type
    if task_type == 'TEST':
        w_qual, w_rel, w_marg, w_exp = 80, 0, 0, 20 # Profit doesn't matter, just pass the test!

    # 2. CALCULATE NORMALIZED SCORES (0 to 1 scale for each metric)

    # Quality (Assume max scale is 10)
    norm_quality = df['AVERAGE_QUALITY'] / 10.0

    # Reliability (Already on a 0 to 1 scale)
    norm_reliability = df['ON_TIME_SCORE']

    # Margin (Cheaper = Higher Score)
    pair = task_reqs.get('language_pair')
    max_rate = task_reqs.get('max_hourly_rate', df[pair].max())
    if max_rate > 0:
        norm_margin = ((max_rate - df[pair]) / max_rate).clip(lower=0)
    else:
        norm_margin = 0

    # Expertise (Cap at 50 hours = 100% mastery)
    exp_score = pd.Series(0, index=df.index)
    for level, prefix in [('required_subindustry', 'SUB'), ('required_industry', 'IND'), ('required_industry_group', 'GRP')]:
        if level in task_reqs and task_reqs[level]:
            for item in task_reqs[level]:
                col_name = f"{prefix}_{item}"
                if col_name in df.columns:
                    exp_score += df[col_name]
            break # Stop at the most specific tier matched

    norm_expertise = (exp_score / 50.0).clip(upper=1.0)

    # 3. APPLY WEIGHTS TO GET FINAL 100-POINT SCORE
    df['SUITABILITY_SCORE'] = (
        (norm_quality * w_qual) +
        (norm_reliability * w_rel) +
        (norm_margin * w_marg) +
        (norm_expertise * w_exp)
    ).round(1)

    # Return sorted by best score first
    return df.sort_values(by='SUITABILITY_SCORE', ascending=False)

# --- DISPLAY PHASE 1 RESULTS ---
if not final_candidates.empty:
    # 1. Pass the survivors into the standalone ranking function!
    final_candidates = rank_candidates(final_candidates, task_requirements)

    print(f"\n--- FOUND {len(final_candidates)} ELIGIBLE TRANSLATORS ---")

    # 2. Add SUITABILITY_SCORE to the printout
    desired_columns = ['SUITABILITY_SCORE', 'NAME', language, 'DAILY_CAPACITY', 'AVERAGE_QUALITY', 'ON_TIME_SCORE']

    if 'required_subindustry' in task_requirements and task_requirements['required_subindustry']:
        desired_columns.append(f"SUB_{task_requirements['required_subindustry'][0]}")
    elif 'required_industry' in task_requirements and task_requirements['required_industry']:
        desired_columns.append(f"IND_{task_requirements['required_industry'][0]}")
    elif 'required_industry_group' in task_requirements and task_requirements['required_industry_group']:
        desired_columns.append(f"GRP_{task_requirements['required_industry_group'][0]}")

    final_cols = [col for col in desired_columns if col in final_candidates.columns]

    # 3. Print the top 10 best-ranked options
    print(final_candidates[final_cols].head(10))
else:
    print("\n[SYSTEM FATAL ERROR] Impossible constraints.")
    csp_solver.diagnose_bottleneck(task_requirements)

if proof_requirements:
    proof_candidates = csp_solver.get_translators_with_fallback(proof_requirements)

    # Enforce Conflict of Interest Rule
    if not proof_candidates.empty:
        proof_candidates = proof_candidates[proof_candidates['NAME'] != selected_name]

    # --- DISPLAY PHASE 2 RESULTS ---
    if not proof_candidates.empty:
        # Rank the proofreaders using the standalone function
        proof_candidates = rank_candidates(proof_candidates, proof_requirements)

        print(f"\n--- FOUND {len(proof_candidates)} SUPERIOR PROOFREADERS ---")
        proof_cols = [col for col in desired_columns if col in proof_candidates.columns]
        print(proof_candidates[proof_cols].head(10))
    else:
        print(f"\n[SYSTEM WARNING] No ProofReaders found...")
        csp_solver.diagnose_bottleneck(proof_requirements)

--- ATTEMPT 1: Strict Requirements ---
SUCCESS: Found 2 eligible translators perfectly matching requirements.

--- FINAL RECOMMENDED ASSIGNMENT ---
             NAME  DAILY_CAPACITY  AVERAGE_QUALITY  ON_TIME_SCORE  \
11  Acacio Poncio            10.0         7.142857            1.0
2    Abdon Isaias            10.0         7.750000            1.0

    OVERQUAL_SCORE
11        0.214286
2         0.275000

/tmp/ipykernel_9155/1465123491.py:100: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  start_times = pd.to_datetime(clean_start, errors='coerce')
/tmp/ipykernel_9155/1465123491.py:101: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  end_times = pd.to_datetime(clean_end, errors='coerce')